//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.SettingsPage.Notification {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.SettingsPage.Notification.Localization.SettingsPage.Notification", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 启用提醒 的本地化字符串。
        /// </summary>
        public static string EnableNotification {
            get {
                return ResourceManager.GetString("EnableNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用提醒后，将会在对重要事件发出醒目提醒。拖动提醒提供方以调整对应类型提醒的优先级。 的本地化字符串。
        /// </summary>
        public static string EnableNotificationDescription {
            get {
                return ResourceManager.GetString("EnableNotificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 提醒可能无法显示 的本地化字符串。
        /// </summary>
        public static string NotificationMayNotShowTitle {
            get {
                return ResourceManager.GetString("NotificationMayNotShowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您禁用了所有主界面行的提醒功能，这可能会导致所有提醒都无法显示。要修复此问题，您需要在【组件】页面至少为一个主界面行开启... 的本地化字符串。
        /// </summary>
        public static string NotificationMayNotShowMessage {
            get {
                return ResourceManager.GetString("NotificationMayNotShowMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 前往【组件】页面 的本地化字符串。
        /// </summary>
        public static string GoToComponentsPage {
            get {
                return ResourceManager.GetString("GoToComponentsPage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 提醒提供方 的本地化字符串。
        /// </summary>
        public static string NotificationProvidersTab {
            get {
                return ResourceManager.GetString("NotificationProvidersTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 提醒渠道 的本地化字符串。
        /// </summary>
        public static string NotificationChannelsHeader {
            get {
                return ResourceManager.GetString("NotificationChannelsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 高级设置 的本地化字符串。
        /// </summary>
        public static string AdvancedSettingsTab {
            get {
                return ResourceManager.GetString("AdvancedSettingsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用提醒语音 的本地化字符串。
        /// </summary>
        public static string EnableNotificationSpeech {
            get {
                return ResourceManager.GetString("EnableNotificationSpeech", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在发出提醒时用语音播报提醒内容。 的本地化字符串。
        /// </summary>
        public static string EnableNotificationSpeechDescription {
            get {
                return ResourceManager.GetString("EnableNotificationSpeechDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认启用 的本地化字符串。
        /// </summary>
        public static string EnableByDefault {
            get {
                return ResourceManager.GetString("EnableByDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 语音引擎 的本地化字符串。
        /// </summary>
        public static string SpeechEngine {
            get {
                return ResourceManager.GetString("SpeechEngine", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 语音音量 的本地化字符串。
        /// </summary>
        public static string SpeechVolume {
            get {
                return ResourceManager.GetString("SpeechVolume", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 测试朗读文本 的本地化字符串。
        /// </summary>
        public static string TestSpeechText {
            get {
                return ResourceManager.GetString("TestSpeechText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 测试语音 的本地化字符串。
        /// </summary>
        public static string TestSpeech {
            get {
                return ResourceManager.GetString("TestSpeech", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用提醒强调特效 的本地化字符串。
        /// </summary>
        public static string EnableNotificationEffect {
            get {
                return ResourceManager.GetString("EnableNotificationEffect", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，发出提醒时会播放全屏强调特效。 的本地化字符串。
        /// </summary>
        public static string EnableNotificationEffectDescription {
            get {
                return ResourceManager.GetString("EnableNotificationEffectDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 提醒特效渲染精度 的本地化字符串。
        /// </summary>
        public static string NotificationEffectRenderingScale {
            get {
                return ResourceManager.GetString("NotificationEffectRenderingScale", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 提醒特效渲染时的精度，使用较低的精度性能可以获得较好的性能。 的本地化字符串。
        /// </summary>
        public static string NotificationEffectRenderingScaleDescription {
            get {
                return ResourceManager.GetString("NotificationEffectRenderingScaleDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用提醒音效 的本地化字符串。
        /// </summary>
        public static string EnableNotificationSound {
            get {
                return ResourceManager.GetString("EnableNotificationSound", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，发出提醒时会播放音效。 的本地化字符串。
        /// </summary>
        public static string EnableNotificationSoundDescription {
            get {
                return ResourceManager.GetString("EnableNotificationSoundDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 音效音量 的本地化字符串。
        /// </summary>
        public static string NotificationSoundVolume {
            get {
                return ResourceManager.GetString("NotificationSoundVolume", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义音效 的本地化字符串。
        /// </summary>
        public static string CustomNotificationSound {
            get {
                return ResourceManager.GetString("CustomNotificationSound", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设置自定义音效，留空以禁用。如果音效长于提醒显示时间，多出来的部分会被截断。 的本地化字符串。
        /// </summary>
        public static string CustomNotificationSoundDescription {
            get {
                return ResourceManager.GetString("CustomNotificationSoundDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 （默认音效） 的本地化字符串。
        /// </summary>
        public static string NotificationSoundPathPlaceholder {
            get {
                return ResourceManager.GetString("NotificationSoundPathPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 置顶提醒 的本地化字符串。
        /// </summary>
        public static string TopmostNotification {
            get {
                return ResourceManager.GetString("TopmostNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在发出提醒时强制显示并置顶主界面。 的本地化字符串。
        /// </summary>
        public static string TopmostNotificationDescription {
            get {
                return ResourceManager.GetString("TopmostNotificationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 基本设置 的本地化字符串。
        /// </summary>
        public static string BasicSettingsTab {
            get {
                return ResourceManager.GetString("BasicSettingsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该提醒提供方没有设置。 的本地化字符串。
        /// </summary>
        public static string ProviderNoSettings {
            get {
                return ResourceManager.GetString("ProviderNoSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 对此提醒来源启用特殊高级设置 的本地化字符串。
        /// </summary>
        public static string EnablePerProviderAdvancedSettings {
            get {
                return ResourceManager.GetString("EnablePerProviderAdvancedSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，此处的设置将覆盖全局设置和提醒请求中要求的设置。 的本地化字符串。
        /// </summary>
        public static string EnablePerProviderAdvancedSettingsDescription {
            get {
                return ResourceManager.GetString("EnablePerProviderAdvancedSettingsDescription", resourceCulture);
            }
        }
    }
}
