//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.SettingsPage.Themes {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.SettingsPage.Themes.Localization.SettingsPage.Themes", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 错误信息 的本地化字符串。
        /// </summary>
        public static string ErrorInfoDrawerTitle {
            get {
                return ResourceManager.GetString("ErrorInfoDrawerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主题加载顺序 的本地化字符串。
        /// </summary>
        public static string ThemeLoadOrderTitle {
            get {
                return ResourceManager.GetString("ThemeLoadOrderTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主题将按照以下的顺序加载，后加载的主题可以覆盖前面主题的样式。拖动以对主题进行排序。 的本地化字符串。
        /// </summary>
        public static string ThemeLoadOrderDescription {
            get {
                return ResourceManager.GetString("ThemeLoadOrderDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在启用了支持的主题（如 Fluent）后，您可以在直接【外观】设置中开启【分体主界面】选项使主界面分开。在没有开启此选项... 的本地化字符串。
        /// </summary>
        public static string SeparateMainWindowInfoBar {
            get {
                return ResourceManager.GetString("SeparateMainWindowInfoBar", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 前往【外观】设置 的本地化字符串。
        /// </summary>
        public static string GoToAppearanceSettings {
            get {
                return ResourceManager.GetString("GoToAppearanceSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 市场 的本地化字符串。
        /// </summary>
        public static string TabMarket {
            get {
                return ResourceManager.GetString("TabMarket", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已安装 的本地化字符串。
        /// </summary>
        public static string TabInstalled {
            get {
                return ResourceManager.GetString("TabInstalled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 刷新市场 的本地化字符串。
        /// </summary>
        public static string RefreshMarket {
            get {
                return ResourceManager.GetString("RefreshMarket", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重载主题 的本地化字符串。
        /// </summary>
        public static string ReloadThemes {
            get {
                return ResourceManager.GetString("ReloadThemes", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开主题文件夹… 的本地化字符串。
        /// </summary>
        public static string OpenThemeFolder {
            get {
                return ResourceManager.GetString("OpenThemeFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 网站… 的本地化字符串。
        /// </summary>
        public static string WebsiteTooltip {
            get {
                return ResourceManager.GetString("WebsiteTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 加载此主题时发生错误 的本地化字符串。
        /// </summary>
        public static string ThemeErrorTooltip {
            get {
                return ResourceManager.GetString("ThemeErrorTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更多选项… 的本地化字符串。
        /// </summary>
        public static string MoreOptionsTooltip {
            get {
                return ResourceManager.GetString("MoreOptionsTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打包主题… 的本地化字符串。
        /// </summary>
        public static string PackageTheme {
            get {
                return ResourceManager.GetString("PackageTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 卸载主题 的本地化字符串。
        /// </summary>
        public static string UninstallTheme {
            get {
                return ResourceManager.GetString("UninstallTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 撤销卸载 的本地化字符串。
        /// </summary>
        public static string UndoUninstall {
            get {
                return ResourceManager.GetString("UndoUninstall", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 安装 的本地化字符串。
        /// </summary>
        public static string InstallTooltip {
            get {
                return ResourceManager.GetString("InstallTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string UpdateTooltip {
            get {
                return ResourceManager.GetString("UpdateTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重启以应用更改 的本地化字符串。
        /// </summary>
        public static string RestartToApplyTooltip {
            get {
                return ResourceManager.GetString("RestartToApplyTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string ThemesTitle {
            get {
                return ResourceManager.GetString("ThemesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 欢迎使用主题！主题可以修改甚至完全重塑 ClassFabric 主界面的外观。您可以使用主题功能打造出独一无二的 Cla... 的本地化字符串。
        /// </summary>
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 需要注意，主题以 XAML 样式的形式加载，可能存在与部分 ClassFabric 版本不兼容，甚至使应用完全无法使用的... 的本地化字符串。
        /// </summary>
        public static string SecurityWarning {
            get {
                return ResourceManager.GetString("SecurityWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 同意并开始使用主题 的本地化字符串。
        /// </summary>
        public static string AgreeAndStart {
            get {
                return ResourceManager.GetString("AgreeAndStart", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法刷新市场 的本地化字符串。
        /// </summary>
        public static string RefreshMarketFailedTitle {
            get {
                return ResourceManager.GetString("RefreshMarketFailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打包主题 的本地化字符串。
        /// </summary>
        public static string PackageThemePickerTitle {
            get {
                return ResourceManager.GetString("PackageThemePickerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 主题包 的本地化字符串。
        /// </summary>
        public static string ThemePackageTypeName {
            get {
                return ResourceManager.GetString("ThemePackageTypeName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法打开所选主题包文件。 的本地化字符串。
        /// </summary>
        public static string OpenSelectedThemePackageFailed {
            get {
                return ResourceManager.GetString("OpenSelectedThemePackageFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法打包主题 {0} 的本地化字符串。
        /// </summary>
        public static string PackageThemeFailed {
            get {
                return ResourceManager.GetString("PackageThemeFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您必须启用至少一个主题，以保证主界面有显示样式可用。 的本地化字符串。
        /// </summary>
        public static string MustKeepAtLeastOneTheme {
            get {
                return ResourceManager.GetString("MustKeepAtLeastOneTheme", resourceCulture);
            }
        }
    }
}
