//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Services.Plugins {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Services.Plugins.Localization.Services.Plugins", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 不兼容的 API 版本 {0}。插件的 API 版本需要至少为 2.0.0.0 才能被当前版本的 ClassFabric... 的本地化字符串。
        /// </summary>
        public static string IncompatibleApiVersionFmt {
            get {
                return ResourceManager.GetString("IncompatibleApiVersionFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件不兼容 的本地化字符串。
        /// </summary>
        public static string PluginIncompatibleDefault {
            get {
                return ResourceManager.GetString("PluginIncompatibleDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 找不到插件 {0}。 的本地化字符串。
        /// </summary>
        public static string PluginNotFoundFmt {
            get {
                return ResourceManager.GetString("PluginNotFoundFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 检测到循环依赖：{0} 的本地化字符串。
        /// </summary>
        public static string CircularDependencyDetectedFmt {
            get {
                return ResourceManager.GetString("CircularDependencyDetectedFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件 {0} 依赖的必选插件 {1} 不存在或处于无法加载状态。 的本地化字符串。
        /// </summary>
        public static string MissingDependencyFmt {
            get {
                return ResourceManager.GetString("MissingDependencyFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该插件可能基于不兼容的 UI 框架版本构建。请确认插件与当前 ClassFabric 版本兼容，或联系插件作者更新。 的本地化字符串。
        /// </summary>
        public static string IncompatibleUiFrameworkMessage {
            get {
                return ResourceManager.GetString("IncompatibleUiFrameworkMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该插件缺少必要的方法引用，可能是版本不兼容导致的。请联系插件作者进行更新。 的本地化字符串。
        /// </summary>
        public static string MissingMethodMessage {
            get {
                return ResourceManager.GetString("MissingMethodMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该插件缺少依赖的程序集。请确认插件完整性，或联系插件作者。 的本地化字符串。
        /// </summary>
        public static string MissingAssemblyMessage {
            get {
                return ResourceManager.GetString("MissingAssemblyMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该插件加载失败。请确认插件版本与当前 ClassFabric 版本兼容，或联系插件作者。 的本地化字符串。
        /// </summary>
        public static string LoadFailedMessage {
            get {
                return ResourceManager.GetString("LoadFailedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 === 插件清单 === 的本地化字符串。
        /// </summary>
        public static string DiagnosticsManifestHeader {
            get {
                return ResourceManager.GetString("DiagnosticsManifestHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件 ID: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsPluginIdFmt {
            get {
                return ResourceManager.GetString("DiagnosticsPluginIdFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件名称: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsPluginNameFmt {
            get {
                return ResourceManager.GetString("DiagnosticsPluginNameFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件版本: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsPluginVersionFmt {
            get {
                return ResourceManager.GetString("DiagnosticsPluginVersionFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 API 版本: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsApiVersionFmt {
            get {
                return ResourceManager.GetString("DiagnosticsApiVersionFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 入口程序集: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsEntranceAssemblyFmt {
            get {
                return ResourceManager.GetString("DiagnosticsEntranceAssemblyFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 === 插件加载失败诊断信息 === 的本地化字符串。
        /// </summary>
        public static string DiagnosticsFailureHeader {
            get {
                return ResourceManager.GetString("DiagnosticsFailureHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 === 运行时环境 === 的本地化字符串。
        /// </summary>
        public static string DiagnosticsRuntimeHeader {
            get {
                return ResourceManager.GetString("DiagnosticsRuntimeHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 版本: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsClassFabricVersionFmt {
            get {
                return ResourceManager.GetString("DiagnosticsClassFabricVersionFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Avalonia 版本: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsAvaloniaVersionFmt {
            get {
                return ResourceManager.GetString("DiagnosticsAvaloniaVersionFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 FluentAvalonia 版本: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsFluentAvaloniaVersionFmt {
            get {
                return ResourceManager.GetString("DiagnosticsFluentAvaloniaVersionFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 === 异常信息 === 的本地化字符串。
        /// </summary>
        public static string DiagnosticsExceptionHeader {
            get {
                return ResourceManager.GetString("DiagnosticsExceptionHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 异常类型: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsExceptionTypeFmt {
            get {
                return ResourceManager.GetString("DiagnosticsExceptionTypeFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 异常消息: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsExceptionMessageFmt {
            get {
                return ResourceManager.GetString("DiagnosticsExceptionMessageFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 === 堆栈跟踪 === 的本地化字符串。
        /// </summary>
        public static string DiagnosticsStackTraceHeader {
            get {
                return ResourceManager.GetString("DiagnosticsStackTraceHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 === 内部异常 === 的本地化字符串。
        /// </summary>
        public static string DiagnosticsInnerExceptionHeader {
            get {
                return ResourceManager.GetString("DiagnosticsInnerExceptionHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 类型: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsInnerTypeFmt {
            get {
                return ResourceManager.GetString("DiagnosticsInnerTypeFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 消息: {0} 的本地化字符串。
        /// </summary>
        public static string DiagnosticsInnerMessageFmt {
            get {
                return ResourceManager.GetString("DiagnosticsInnerMessageFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未加载 的本地化字符串。
        /// </summary>
        public static string NotLoadedLabel {
            get {
                return ResourceManager.GetString("NotLoadedLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string UnknownLabel {
            get {
                return ResourceManager.GetString("UnknownLabel", resourceCulture);
            }
        }
    }
}
