//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.SettingsPage.General {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.SettingsPage.General.Localization.SettingsPage.General", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   查找类似 中文(简体) 的本地化字符串。
        /// </summary>
        public static string LangName {
            get {
                return ResourceManager.GetString("LangName", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 界面语言 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 更改应用的显示语言，切换后需要重启应用才能生效。 的本地化字符串。
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 ClassFabric 是开源免费的软件，官方没有提供任何形式的付费支持服务，源代码仓库地址在 https://github.com/ClassIsland/ClassIsland/。如果您通过有偿协助等付费方式取得本应用，在遇到问题时请在与卖家约定的服务框架下，优先向卖家求助。如果卖家没有提供您预期的服务，请退款或通过其它形式积极维护您的合法权益。 的本地化字符串。
        /// </summary>
        public static string SellingAnnouncement {
            get {
                return ResourceManager.GetString("SellingAnnouncement", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 行为 的本地化字符串。
        /// </summary>
        public static string Behavior {
            get {
                return ResourceManager.GetString("Behavior", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 开机自启 的本地化字符串。
        /// </summary>
        public static string LoadOnBoot {
            get {
                return ResourceManager.GetString("LoadOnBoot", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 在您的系统启动时自动运行本应用。 的本地化字符串。
        /// </summary>
        public static string LoadOnBootDescription {
            get {
                return ResourceManager.GetString("LoadOnBootDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 注册 Url 协议 的本地化字符串。
        /// </summary>
        public static string RegURLProto {
            get {
                return ResourceManager.GetString("RegURLProto", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 允许第三方应用或网页通过 Url 协议 classfabric:// 调用本应用的部分功能，详见帮助文档。 的本地化字符串。
        /// </summary>
        public static string RegURLProtoDescription {
            get {
                return ResourceManager.GetString("RegURLProtoDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 学期开始时间 的本地化字符串。
        /// </summary>
        public static string SemesterStartDate {
            get {
                return ResourceManager.GetString("SemesterStartDate", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 设置学期首日，该日期将作为多周轮换课表的计算起点和每周的第一天。 的本地化字符串。
        /// </summary>
        public static string SemesterStartDateDescription {
            get {
                return ResourceManager.GetString("SemesterStartDateDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 最大多周轮换周数 的本地化字符串。
        /// </summary>
        public static string MaxMultiWeekRotationCycles {
            get {
                return ResourceManager.GetString("MaxMultiWeekRotationCycles", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 周 的本地化字符串。
        /// </summary>
        public static string WeekUnit {
            get {
                return ResourceManager.GetString("WeekUnit", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 调整多周轮换偏移… 的本地化字符串。
        /// </summary>
        public static string AdjustOffset {
            get {
                return ResourceManager.GetString("AdjustOffset", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 点击托盘图标行为 的本地化字符串。
        /// </summary>
        public static string TrayIconClickBehavior {
            get {
                return ResourceManager.GetString("TrayIconClickBehavior", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 鼠标左键点击/触屏单击本应用托盘图标时进行的操作。无论此设置处于何种选项，鼠标右键点击/触屏长按托盘图标总是会打开主菜单。 的本地化字符串。
        /// </summary>
        public static string TrayIconClickBehaviorDescription {
            get {
                return ResourceManager.GetString("TrayIconClickBehaviorDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 鼠标左键点击/触屏单击本应用托盘图标时进行的操作。无论此设置处于何种选项，鼠标右键点击/触屏长按托盘图标总是会打开主菜单。此选项可能因为桌面环境差异而无法工作。 的本地化字符串。
        /// </summary>
        public static string TrayIconClickBehaviorDescriptionLinux {
            get {
                return ResourceManager.GetString("TrayIconClickBehaviorDescriptionLinux", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 打开主菜单 的本地化字符串。
        /// </summary>
        public static string TrayIconClickActionOpenMainMenu {
            get {
                return ResourceManager.GetString("TrayIconClickActionOpenMainMenu", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 打开档案编辑窗口 的本地化字符串。
        /// </summary>
        public static string TrayIconClickActionOpenProfileEditor {
            get {
                return ResourceManager.GetString("TrayIconClickActionOpenProfileEditor", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 显示/隐藏主界面 的本地化字符串。
        /// </summary>
        public static string TrayIconClickActionToggleMainWindow {
            get {
                return ResourceManager.GetString("TrayIconClickActionToggleMainWindow", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 打开换课窗口 的本地化字符串。
        /// </summary>
        public static string TrayIconClickActionOpenClassChanging {
            get {
                return ResourceManager.GetString("TrayIconClickActionOpenClassChanging", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 打开设置窗口 的本地化字符串。
        /// </summary>
        public static string TrayIconClickActionOpenSettings {
            get {
                return ResourceManager.GetString("TrayIconClickActionOpenSettings", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 教学安全模式 的本地化字符串。
        /// </summary>
        public static string CriticalSafeMode {
            get {
                return ResourceManager.GetString("CriticalSafeMode", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 启用后，如果 ClassFabric 发生意外崩溃，将自动按照右侧选择的方法处理崩溃，以确保教学不受到影响。如果发生的是不可忽略的异常，应用将自动退出。您可以在日志记录中查看崩溃详情。 的本地化字符串。
        /// </summary>
        public static string CriticalSafeModeDescription {
            get {
                return ResourceManager.GetString("CriticalSafeModeDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 显示崩溃报告 的本地化字符串。
        /// </summary>
        public static string CriticalSafeModeMethodShowCrashReport {
            get {
                return ResourceManager.GetString("CriticalSafeModeMethodShowCrashReport", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 退出应用 的本地化字符串。
        /// </summary>
        public static string CriticalSafeModeMethodExitApp {
            get {
                return ResourceManager.GetString("CriticalSafeModeMethodExitApp", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 静默重启应用 的本地化字符串。
        /// </summary>
        public static string CriticalSafeModeMethodSilentRestart {
            get {
                return ResourceManager.GetString("CriticalSafeModeMethodSilentRestart", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 显示通知 的本地化字符串。
        /// </summary>
        public static string CriticalSafeModeMethodShowNotification {
            get {
                return ResourceManager.GetString("CriticalSafeModeMethodShowNotification", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 忽略（不推荐） 的本地化字符串。
        /// </summary>
        public static string CriticalSafeModeMethodIgnore {
            get {
                return ResourceManager.GetString("CriticalSafeModeMethodIgnore", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 显示启动加载界面 的本地化字符串。
        /// </summary>
        public static string ShowSplash {
            get {
                return ResourceManager.GetString("ShowSplash", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 启动时显示加载界面。注意：在不启用【禁用动画等待】的情况下，此功能会拖慢启动速度。 的本地化字符串。
        /// </summary>
        public static string ShowSplashDescription {
            get {
                return ResourceManager.GetString("ShowSplashDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 启动图标 的本地化字符串。
        /// </summary>
        public static string SplashCustomLogo {
            get {
                return ResourceManager.GetString("SplashCustomLogo", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 （默认图标） 的本地化字符串。
        /// </summary>
        public static string SplashCustomLogoPlaceholder {
            get {
                return ResourceManager.GetString("SplashCustomLogoPlaceholder", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 启动文字 的本地化字符串。
        /// </summary>
        public static string SplashCustomText {
            get {
                return ResourceManager.GetString("SplashCustomText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 正在启动… 的本地化字符串。
        /// </summary>
        public static string SplashCustomTextPlaceholder {
            get {
                return ResourceManager.GetString("SplashCustomTextPlaceholder", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 显示详细状态信息 的本地化字符串。
        /// </summary>
        public static string SplashDetailedStatus {
            get {
                return ResourceManager.GetString("SplashDetailedStatus", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 注意：在不启用【禁用动画等待】的情况下，此选项会拖慢启动速度。 的本地化字符串。
        /// </summary>
        public static string SplashDetailedStatusDescription {
            get {
                return ResourceManager.GetString("SplashDetailedStatusDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 自定义启动界面功能已被您所在的组织禁用。 的本地化字符串。
        /// </summary>
        public static string SplashCustomizeDisabledByPolicy {
            get {
                return ResourceManager.GetString("SplashCustomizeDisabledByPolicy", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 预览启动界面 的本地化字符串。
        /// </summary>
        public static string SplashPreview {
            get {
                return ResourceManager.GetString("SplashPreview", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 界面 的本地化字符串。
        /// </summary>
        public static string Interface {
            get {
                return ResourceManager.GetString("Interface", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 隐藏窗口 的本地化字符串。
        /// </summary>
        public static string HideWindow {
            get {
                return ResourceManager.GetString("HideWindow", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 将在以下选定的情况隐藏主界面，以防止遮挡屏幕影响授课。 的本地化字符串。
        /// </summary>
        public static string HideWindowDescription {
            get {
                return ResourceManager.GetString("HideWindowDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 基础模式 的本地化字符串。
        /// </summary>
        public static string HideWindowBasicMode {
            get {
                return ResourceManager.GetString("HideWindowBasicMode", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 上课时 的本地化字符串。
        /// </summary>
        public static string HideOnClass {
            get {
                return ResourceManager.GetString("HideOnClass", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 前台是最大化窗口时 的本地化字符串。
        /// </summary>
        public static string HideOnMaxWindow {
            get {
                return ResourceManager.GetString("HideOnMaxWindow", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 前台是全屏窗口时 的本地化字符串。
        /// </summary>
        public static string HideOnFullscreen {
            get {
                return ResourceManager.GetString("HideOnFullscreen", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 高级模式 的本地化字符串。
        /// </summary>
        public static string HideWindowAdvancedMode {
            get {
                return ResourceManager.GetString("HideWindowAdvancedMode", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 编辑规则集… 的本地化字符串。
        /// </summary>
        public static string EditRuleset {
            get {
                return ResourceManager.GetString("EditRuleset", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 动画级别 的本地化字符串。
        /// </summary>
        public static string AnimationLevel {
            get {
                return ResourceManager.GetString("AnimationLevel", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 控制应用界面的动画级别，禁用动画选项不适用于应用主界面和部分控件。 的本地化字符串。
        /// </summary>
        public static string AnimationLevelDescription {
            get {
                return ResourceManager.GetString("AnimationLevelDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string AnimationLevelDisabled {
            get {
                return ResourceManager.GetString("AnimationLevelDisabled", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        public static string AnimationLevelStandard {
            get {
                return ResourceManager.GetString("AnimationLevelStandard", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 华丽 的本地化字符串。
        /// </summary>
        public static string AnimationLevelFancy {
            get {
                return ResourceManager.GetString("AnimationLevelFancy", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 禁用动画等待 的本地化字符串。
        /// </summary>
        public static string DisableAnimationWait {
            get {
                return ResourceManager.GetString("DisableAnimationWait", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 默认情况下 ClassFabric 在进行阻塞 UI 线程的操作时，会确保动画播放完成。启用此选项后将不会等待动画播放完成，可以一定程度上地提升加载速度。 的本地化字符串。
        /// </summary>
        public static string DisableAnimationWaitDescription {
            get {
                return ResourceManager.GetString("DisableAnimationWaitDescription", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 降低主界面进度条精度 的本地化字符串。
        /// </summary>
        public static string ReduceProgressAccuracy {
            get {
                return ResourceManager.GetString("ReduceProgressAccuracy", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 启用后将降低主界面进度条精度，降低主界面更新频率，以减少应用的性能占用。 的本地化字符串。
        /// </summary>
        public static string ReduceProgressAccuracyDescription {
            get {
                return ResourceManager.GetString("ReduceProgressAccuracyDescription", resourceCulture);
            }
        }    }
}
