<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ClassIsland.Shared.IPC</AssemblyName>
    <RootNamespace>ClassIsland.Shared.IPC</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ClassFabric.Shared.IPC\ClassFabric.Shared.IPC.csproj" />
  </ItemGroup>
</Project>
