//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Controls.EditMode {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Controls.EditMode.Localization.Controls.EditMode", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 基本 的本地化字符串。
        /// </summary>
        public static string BasicSection {
            get {
                return ResourceManager.GetString("BasicSection", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 界面缩放 的本地化字符串。
        /// </summary>
        public static string UiScale {
            get {
                return ResourceManager.GetString("UiScale", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面的缩放大小。 的本地化字符串。
        /// </summary>
        public static string UiScaleDescription {
            get {
                return ResourceManager.GetString("UiScaleDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 背景颜色 的本地化字符串。
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面背景颜色，禁用时将根据应用主题自动选择颜色。 的本地化字符串。
        /// </summary>
        public static string BackgroundColorDescription {
            get {
                return ResourceManager.GetString("BackgroundColorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 背景不透明度 的本地化字符串。
        /// </summary>
        public static string BackgroundOpacity {
            get {
                return ResourceManager.GetString("BackgroundOpacity", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面背景的不透明度。 的本地化字符串。
        /// </summary>
        public static string BackgroundOpacityDescription {
            get {
                return ResourceManager.GetString("BackgroundOpacityDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 圆角半径 的本地化字符串。
        /// </summary>
        public static string CornerRadius {
            get {
                return ResourceManager.GetString("CornerRadius", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面圆角半径，调至最大数值时左右边缘为半圆。 的本地化字符串。
        /// </summary>
        public static string CornerRadiusDescription {
            get {
                return ResourceManager.GetString("CornerRadiusDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 行间隔 的本地化字符串。
        /// </summary>
        public static string LineSpacing {
            get {
                return ResourceManager.GetString("LineSpacing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面行间间隔。 的本地化字符串。
        /// </summary>
        public static string LineSpacingDescription {
            get {
                return ResourceManager.GetString("LineSpacingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 分体主界面 的本地化字符串。
        /// </summary>
        public static string SeparateMainWindow {
            get {
                return ResourceManager.GetString("SeparateMainWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后组件会分开。 的本地化字符串。
        /// </summary>
        public static string SeparateMainWindowMainDescription {
            get {
                return ResourceManager.GetString("SeparateMainWindowMainDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后主界面会分开。 的本地化字符串。
        /// </summary>
        public static string SeparateMainWindowLineDescription {
            get {
                return ResourceManager.GetString("SeparateMainWindowLineDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更多外观设置 的本地化字符串。
        /// </summary>
        public static string MoreAppearanceSettings {
            get {
                return ResourceManager.GetString("MoreAppearanceSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 将组件拖动到主界面上即可添加组件。 的本地化字符串。
        /// </summary>
        public static string DragToAddHint {
            get {
                return ResourceManager.GetString("DragToAddHint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择要添加的组件，或将组件拖动到主界面上即可添加组件。 的本地化字符串。
        /// </summary>
        public static string SelectOrDragToAddHint {
            get {
                return ResourceManager.GetString("SelectOrDragToAddHint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组件设置 的本地化字符串。
        /// </summary>
        public static string ComponentSettingsTab {
            get {
                return ResourceManager.GetString("ComponentSettingsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 高级设置 的本地化字符串。
        /// </summary>
        public static string AdvancedSettingsTab {
            get {
                return ResourceManager.GetString("AdvancedSettingsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑… 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑规则集… 的本地化字符串。
        /// </summary>
        public static string EditRulesetTip {
            get {
                return ResourceManager.GetString("EditRulesetTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 按规则隐藏 的本地化字符串。
        /// </summary>
        public static string HideOnRule {
            get {
                return ResourceManager.GetString("HideOnRule", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面行设置 的本地化字符串。
        /// </summary>
        public static string MainWindowLineSettings {
            get {
                return ResourceManager.GetString("MainWindowLineSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 继承 的本地化字符串。
        /// </summary>
        public static string Inherit {
            get {
                return ResourceManager.GetString("Inherit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不透明度 的本地化字符串。
        /// </summary>
        public static string Opacity {
            get {
                return ResourceManager.GetString("Opacity", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面行整体的不透明度。 的本地化字符串。
        /// </summary>
        public static string OpacityLineDescription {
            get {
                return ResourceManager.GetString("OpacityLineDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义背景效果 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundEffect {
            get {
                return ResourceManager.GetString("CustomBackgroundEffect", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义主界面的背景效果，仅在较新版本的 Windows 上可用，可能会产生额外性能开销。 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundEffectDescription {
            get {
                return ResourceManager.GetString("CustomBackgroundEffectDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 材质类型 的本地化字符串。
        /// </summary>
        public static string MaterialType {
            get {
                return ResourceManager.GetString("MaterialType", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 亚克力 的本地化字符串。
        /// </summary>
        public static string MaterialAcrylic {
            get {
                return ResourceManager.GetString("MaterialAcrylic", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 类液态玻璃 的本地化字符串。
        /// </summary>
        public static string MaterialLiquidGlass {
            get {
                return ResourceManager.GetString("MaterialLiquidGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 云母 的本地化字符串。
        /// </summary>
        public static string MaterialMica {
            get {
                return ResourceManager.GetString("MaterialMica", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义背景颜色 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundColor {
            get {
                return ResourceManager.GetString("CustomBackgroundColor", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前主界面行背景颜色，禁用时将使用上级默认值。 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundColorDescription {
            get {
                return ResourceManager.GetString("CustomBackgroundColorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义背景不透明度 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundOpacity {
            get {
                return ResourceManager.GetString("CustomBackgroundOpacity", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前主界面行的背景的不透明度，禁用将使用上级默认值。 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundOpacityDescription {
            get {
                return ResourceManager.GetString("CustomBackgroundOpacityDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义背景圆角半径 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundCornerRadius {
            get {
                return ResourceManager.GetString("CustomBackgroundCornerRadius", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前主界面行背景圆角半径，调至最大数值时左右边缘为半圆。 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundCornerRadiusDescription {
            get {
                return ResourceManager.GetString("CustomBackgroundCornerRadiusDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        public static string FontSection {
            get {
                return ResourceManager.GetString("FontSection", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字体大小 的本地化字符串。
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 调整组件上各类字体的大小，将覆盖【外观】设置和主界面行中设置的字体大小。 的本地化字符串。
        /// </summary>
        public static string FontSizeDescription {
            get {
                return ResourceManager.GetString("FontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 次级字体大小 的本地化字符串。
        /// </summary>
        public static string SecondaryFontSizeName {
            get {
                return ResourceManager.GetString("SecondaryFontSizeName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间点附加信息等 的本地化字符串。
        /// </summary>
        public static string SecondaryFontSizeDescription {
            get {
                return ResourceManager.GetString("SecondaryFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正文字体大小 的本地化字符串。
        /// </summary>
        public static string BodyFontSizeName {
            get {
                return ResourceManager.GetString("BodyFontSizeName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面默认字体大小 的本地化字符串。
        /// </summary>
        public static string BodyFontSizeDescription {
            get {
                return ResourceManager.GetString("BodyFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 强调字体大小 的本地化字符串。
        /// </summary>
        public static string EmphasizedFontSizeName {
            get {
                return ResourceManager.GetString("EmphasizedFontSizeName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课程表、时钟、提醒标题、天气预报等内容 的本地化字符串。
        /// </summary>
        public static string EmphasizedFontSizeDescription {
            get {
                return ResourceManager.GetString("EmphasizedFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 大号字体大小 的本地化字符串。
        /// </summary>
        public static string LargeFontSizeName {
            get {
                return ResourceManager.GetString("LargeFontSizeName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课程预报等内容 的本地化字符串。
        /// </summary>
        public static string LargeFontSizeDescription {
            get {
                return ResourceManager.GetString("LargeFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字体颜色 的本地化字符串。
        /// </summary>
        public static string FontColor {
            get {
                return ResourceManager.GetString("FontColor", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 调整字体颜色，将覆盖【外观】设置和主界面行中设置的值。 的本地化字符串。
        /// </summary>
        public static string FontColorDescription {
            get {
                return ResourceManager.GetString("FontColorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择要启用的组件配置 的本地化字符串。
        /// </summary>
        public static string SelectProfileToEnable {
            get {
                return ResourceManager.GetString("SelectProfileToEnable", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string RefreshTip {
            get {
                return ResourceManager.GetString("RefreshTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建… 的本地化字符串。
        /// </summary>
        public static string NewTip {
            get {
                return ResourceManager.GetString("NewTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开配置文件夹… 的本地化字符串。
        /// </summary>
        public static string OpenConfigFolderTip {
            get {
                return ResourceManager.GetString("OpenConfigFolderTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string DuplicateTip {
            get {
                return ResourceManager.GetString("DuplicateTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组件库 的本地化字符串。
        /// </summary>
        public static string ComponentsLibrary {
            get {
                return ResourceManager.GetString("ComponentsLibrary", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑规则集 的本地化字符串。
        /// </summary>
        public static string EditRuleset {
            get {
                return ResourceManager.GetString("EditRuleset", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建组件配置 的本地化字符串。
        /// </summary>
        public static string CreateProfileTitle {
            get {
                return ResourceManager.GetString("CreateProfileTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组件名 的本地化字符串。
        /// </summary>
        public static string ProfileNameLabel {
            get {
                return ResourceManager.GetString("ProfileNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法删除已加载或将要加载的组件配置。 的本地化字符串。
        /// </summary>
        public static string CannotDeleteLoadedProfileToast {
            get {
                return ResourceManager.GetString("CannotDeleteLoadedProfileToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除组件配置 的本地化字符串。
        /// </summary>
        public static string DeleteProfileTitle {
            get {
                return ResourceManager.GetString("DeleteProfileTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您确定要删除组件配置 {0} 吗？此操作无法撤销，组件配置内的组件信息都将被删除！ 的本地化字符串。
        /// </summary>
        public static string DeleteProfileConfirmFmt {
            get {
                return ResourceManager.GetString("DeleteProfileConfirmFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重命名组件配置方案 的本地化字符串。
        /// </summary>
        public static string RenameProfileTitle {
            get {
                return ResourceManager.GetString("RenameProfileTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组件配置方案名称 的本地化字符串。
        /// </summary>
        public static string ProfileSchemeNameLabel {
            get {
                return ResourceManager.GetString("ProfileSchemeNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法重命名组件配置，因为已存在一个相同名称的组件配置。 的本地化字符串。
        /// </summary>
        public static string RenameConflictToast {
            get {
                return ResourceManager.GetString("RenameConflictToast", resourceCulture);
            }
        }
    }
}
