//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Windows.TutorialEditor {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Windows.TutorialEditor.Localization.Windows.TutorialEditor", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 教程编辑器 的本地化字符串。
        /// </summary>
        public static string EditorTitle {
            get {
                return ResourceManager.GetString("EditorTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 教程组 的本地化字符串。
        /// </summary>
        public static string TutorialGroup {
            get {
                return ResourceManager.GetString("TutorialGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 标题 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 教程 的本地化字符串。
        /// </summary>
        public static string Tutorial {
            get {
                return ResourceManager.GetString("Tutorial", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 （默认） 的本地化字符串。
        /// </summary>
        public static string WatermarkDefault {
            get {
                return ResourceManager.GetString("WatermarkDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 基本 的本地化字符串。
        /// </summary>
        public static string BasicTab {
            get {
                return ResourceManager.GetString("BasicTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 段落 的本地化字符串。
        /// </summary>
        public static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 TopLevel 类名 的本地化字符串。
        /// </summary>
        public static string TopLevelClassName {
            get {
                return ResourceManager.GetString("TopLevelClassName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用屏障 的本地化字符串。
        /// </summary>
        public static string EnableBarrier {
            get {
                return ResourceManager.GetString("EnableBarrier", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 进入事件 的本地化字符串。
        /// </summary>
        public static string EnterEventTab {
            get {
                return ResourceManager.GetString("EnterEventTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 语句 的本地化字符串。
        /// </summary>
        public static string Sentence {
            get {
                return ResourceManager.GetString("Sentence", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 头图 的本地化字符串。
        /// </summary>
        public static string HeroImage {
            get {
                return ResourceManager.GetString("HeroImage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 （禁用） 的本地化字符串。
        /// </summary>
        public static string WatermarkDisabled {
            get {
                return ResourceManager.GetString("WatermarkDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 目标控件选择器 的本地化字符串。
        /// </summary>
        public static string TargetSelectorLabel {
            get {
                return ResourceManager.GetString("TargetSelectorLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 教学提示摆放模式 的本地化字符串。
        /// </summary>
        public static string TeachingTipPlacement {
            get {
                return ResourceManager.GetString("TeachingTipPlacement", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 指向目标 的本地化字符串。
        /// </summary>
        public static string PointToTarget {
            get {
                return ResourceManager.GetString("PointToTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 高亮目标 的本地化字符串。
        /// </summary>
        public static string HighlightTarget {
            get {
                return ResourceManager.GetString("HighlightTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 使目标具有模态 的本地化字符串。
        /// </summary>
        public static string ModalTarget {
            get {
                return ResourceManager.GetString("ModalTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 可等待被外部推动 的本地化字符串。
        /// </summary>
        public static string WaitForNextCommand {
            get {
                return ResourceManager.GetString("WaitForNextCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 使用 LightDismiss 代替右侧按钮 的本地化字符串。
        /// </summary>
        public static string UseLightDismiss {
            get {
                return ResourceManager.GetString("UseLightDismiss", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右侧按钮 的本地化字符串。
        /// </summary>
        public static string RightButton {
            get {
                return ResourceManager.GetString("RightButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左侧按钮 的本地化字符串。
        /// </summary>
        public static string LeftButton {
            get {
                return ResourceManager.GetString("LeftButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 左按钮事件 的本地化字符串。
        /// </summary>
        public static string LeftButtonEventTab {
            get {
                return ResourceManager.GetString("LeftButtonEventTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 右按钮事件 的本地化字符串。
        /// </summary>
        public static string RightButtonEventTab {
            get {
                return ResourceManager.GetString("RightButtonEventTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 脚本 的本地化字符串。
        /// </summary>
        public static string ScriptTab {
            get {
                return ResourceManager.GetString("ScriptTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 教程脚本 的本地化字符串。
        /// </summary>
        public static string TutorialScript {
            get {
                return ResourceManager.GetString("TutorialScript", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用脚本 的本地化字符串。
        /// </summary>
        public static string EnableScript {
            get {
                return ResourceManager.GetString("EnableScript", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 使用独立编辑器编辑此语句的 Lua 脚本。 的本地化字符串。
        /// </summary>
        public static string EditScriptHint {
            get {
                return ResourceManager.GetString("EditScriptHint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑脚本… 的本地化字符串。
        /// </summary>
        public static string EditScript {
            get {
                return ResourceManager.GetString("EditScript", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开… 的本地化字符串。
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 保存… 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 另存为… 的本地化字符串。
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 教程章节信息… 的本地化字符串。
        /// </summary>
        public static string ChapterInfo {
            get {
                return ResourceManager.GetString("ChapterInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        public static string RunMenu {
            get {
                return ResourceManager.GetString("RunMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 运行当前教程 的本地化字符串。
        /// </summary>
        public static string RunCurrent {
            get {
                return ResourceManager.GetString("RunCurrent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 从当前段落开始运行 的本地化字符串。
        /// </summary>
        public static string RunFromParagraph {
            get {
                return ResourceManager.GetString("RunFromParagraph", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 停止运行 的本地化字符串。
        /// </summary>
        public static string StopRunning {
            get {
                return ResourceManager.GetString("StopRunning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 目标选择器 的本地化字符串。
        /// </summary>
        public static string TargetSelector {
            get {
                return ResourceManager.GetString("TargetSelector", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新教程 的本地化字符串。
        /// </summary>
        public static string NewTutorial {
            get {
                return ResourceManager.GetString("NewTutorial", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新段落 的本地化字符串。
        /// </summary>
        public static string NewParagraph {
            get {
                return ResourceManager.GetString("NewParagraph", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法打开所选教程文件。 的本地化字符串。
        /// </summary>
        public static string ErrorCannotOpenTutorialFile {
            get {
                return ResourceManager.GetString("ErrorCannotOpenTutorialFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已打开 {0} 的本地化字符串。
        /// </summary>
        public static string OpenedToast {
            get {
                return ResourceManager.GetString("OpenedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已替换 ID 为 {0} 的教程组并启用热重载。 的本地化字符串。
        /// </summary>
        public static string ReplacedGroupToast {
            get {
                return ResourceManager.GetString("ReplacedGroupToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法打开教程文件 的本地化字符串。
        /// </summary>
        public static string ErrorOpenTutorialFile {
            get {
                return ResourceManager.GetString("ErrorOpenTutorialFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已保存 {0} 的本地化字符串。
        /// </summary>
        public static string SavedToast {
            get {
                return ResourceManager.GetString("SavedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法保存教程文件 的本地化字符串。
        /// </summary>
        public static string ErrorSaveTutorialFile {
            get {
                return ResourceManager.GetString("ErrorSaveTutorialFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更改尚未保存 的本地化字符串。
        /// </summary>
        public static string UnsavedChangesTitle {
            get {
                return ResourceManager.GetString("UnsavedChangesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更改尚未保存，您要在退出前保存更改吗？ 的本地化字符串。
        /// </summary>
        public static string UnsavedChangesContent {
            get {
                return ResourceManager.GetString("UnsavedChangesContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不保存 的本地化字符串。
        /// </summary>
        public static string DontSave {
            get {
                return ResourceManager.GetString("DontSave", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
    }
}
