//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.SettingsPage.Component {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.SettingsPage.Component.Localization.SettingsPage.Component", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 向上移动一行 的本地化字符串。
        /// </summary>
        public static string MoveUpMenu {
            get {
                return ResourceManager.GetString("MoveUpMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 向下移动一行 的本地化字符串。
        /// </summary>
        public static string MoveDownMenu {
            get {
                return ResourceManager.GetString("MoveDownMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 移动到选中的容器 的本地化字符串。
        /// </summary>
        public static string MoveToSelectedContainerMenu {
            get {
                return ResourceManager.GetString("MoveToSelectedContainerMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 从容器组件移出 的本地化字符串。
        /// </summary>
        public static string MoveOutOfContainerMenu {
            get {
                return ResourceManager.GetString("MoveOutOfContainerMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 包裹到新容器 的本地化字符串。
        /// </summary>
        public static string WrapIntoNewContainerMenu {
            get {
                return ResourceManager.GetString("WrapIntoNewContainerMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建副本 的本地化字符串。
        /// </summary>
        public static string DuplicateMenu {
            get {
                return ResourceManager.GetString("DuplicateMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更多选项… 的本地化字符串。
        /// </summary>
        public static string MoreOptionsToolTip {
            get {
                return ResourceManager.GetString("MoreOptionsToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查看子组件 的本地化字符串。
        /// </summary>
        public static string ViewChildrenToolTip {
            get {
                return ResourceManager.GetString("ViewChildrenToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string DeleteToolTip {
            get {
                return ResourceManager.GetString("DeleteToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 以下组件将显示在主界面上，从组件库拖动组件以添加组件。 的本地化字符串。
        /// </summary>
        public static string PageIntroText {
            get {
                return ResourceManager.GetString("PageIntroText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 配置方案 的本地化字符串。
        /// </summary>
        public static string ConfigProfileLabel {
            get {
                return ResourceManager.GetString("ConfigProfileLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string RefreshToolTip {
            get {
                return ResourceManager.GetString("RefreshToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建… 的本地化字符串。
        /// </summary>
        public static string NewConfigToolTip {
            get {
                return ResourceManager.GetString("NewConfigToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开配置文件夹… 的本地化字符串。
        /// </summary>
        public static string OpenConfigFolderToolTip {
            get {
                return ResourceManager.GetString("OpenConfigFolderToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此行是主要行 的本地化字符串。
        /// </summary>
        public static string IsMainLineToolTip {
            get {
                return ResourceManager.GetString("IsMainLineToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此行可以显示提醒 的本地化字符串。
        /// </summary>
        public static string LineNotificationToolTip {
            get {
                return ResourceManager.GetString("LineNotificationToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在下方插入一行 的本地化字符串。
        /// </summary>
        public static string InsertLineBelowToolTip {
            get {
                return ResourceManager.GetString("InsertLineBelowToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 返回上一层级 的本地化字符串。
        /// </summary>
        public static string NavigateBackToolTip {
            get {
                return ResourceManager.GetString("NavigateBackToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此组件的子组件 的本地化字符串。
        /// </summary>
        public static string ChildrenOfComponentText {
            get {
                return ResourceManager.GetString("ChildrenOfComponentText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string CloseToolTip {
            get {
                return ResourceManager.GetString("CloseToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组件库 的本地化字符串。
        /// </summary>
        public static string TabComponentLibrary {
            get {
                return ResourceManager.GetString("TabComponentLibrary", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组件设置 的本地化字符串。
        /// </summary>
        public static string TabComponentSettings {
            get {
                return ResourceManager.GetString("TabComponentSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 高级设置 的本地化字符串。
        /// </summary>
        public static string TabAdvancedSettings {
            get {
                return ResourceManager.GetString("TabAdvancedSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 行设置 的本地化字符串。
        /// </summary>
        public static string TabLineSettings {
            get {
                return ResourceManager.GetString("TabLineSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 按规则隐藏 的本地化字符串。
        /// </summary>
        public static string HideOnRuleHeader {
            get {
                return ResourceManager.GetString("HideOnRuleHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在指定规则满足时，自动隐藏此组件。注意此处的隐藏不会释放组件资源。 的本地化字符串。
        /// </summary>
        public static string HideOnRuleDescription {
            get {
                return ResourceManager.GetString("HideOnRuleDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑规则集… 的本地化字符串。
        /// </summary>
        public static string EditRuleset {
            get {
                return ResourceManager.GetString("EditRuleset", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 分体主界面 的本地化字符串。
        /// </summary>
        public static string SplitMainWindowHeader {
            get {
                return ResourceManager.GetString("SplitMainWindowHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后主界面会分开。 的本地化字符串。
        /// </summary>
        public static string SplitMainWindowDescription {
            get {
                return ResourceManager.GetString("SplitMainWindowDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 继承 的本地化字符串。
        /// </summary>
        public static string InheritOption {
            get {
                return ResourceManager.GetString("InheritOption", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string DisableOption {
            get {
                return ResourceManager.GetString("DisableOption", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string EnableOption {
            get {
                return ResourceManager.GetString("EnableOption", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        public static string SectionAppearance {
            get {
                return ResourceManager.GetString("SectionAppearance", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不透明度 的本地化字符串。
        /// </summary>
        public static string OpacityHeader {
            get {
                return ResourceManager.GetString("OpacityHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面行整体的不透明度。 的本地化字符串。
        /// </summary>
        public static string OpacityDescription {
            get {
                return ResourceManager.GetString("OpacityDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义背景效果 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundEffectHeader {
            get {
                return ResourceManager.GetString("CustomBackgroundEffectHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义主界面的背景效果，仅在较新版本的 Windows 上可用，可能会产生额外性能开销。 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundEffectDescription {
            get {
                return ResourceManager.GetString("CustomBackgroundEffectDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 材质类型 的本地化字符串。
        /// </summary>
        public static string MaterialTypeItem {
            get {
                return ResourceManager.GetString("MaterialTypeItem", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 亚克力 的本地化字符串。
        /// </summary>
        public static string MaterialAcrylic {
            get {
                return ResourceManager.GetString("MaterialAcrylic", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 类液态玻璃 的本地化字符串。
        /// </summary>
        public static string MaterialLiquidGlass {
            get {
                return ResourceManager.GetString("MaterialLiquidGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 云母 的本地化字符串。
        /// </summary>
        public static string MaterialMica {
            get {
                return ResourceManager.GetString("MaterialMica", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义背景颜色 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundColorHeader {
            get {
                return ResourceManager.GetString("CustomBackgroundColorHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前主界面行背景颜色，禁用时将使用上级默认值。 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundColorDescription {
            get {
                return ResourceManager.GetString("CustomBackgroundColorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义背景不透明度 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundOpacityHeader {
            get {
                return ResourceManager.GetString("CustomBackgroundOpacityHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前主界面行的背景的不透明度，禁用将使用上级默认值。 的本地化字符串。
        /// </summary>
        public static string CustomBackgroundOpacityDescription {
            get {
                return ResourceManager.GetString("CustomBackgroundOpacityDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义背景圆角半径 的本地化字符串。
        /// </summary>
        public static string CustomCornerRadiusHeader {
            get {
                return ResourceManager.GetString("CustomCornerRadiusHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前主界面行背景圆角半径，调至最大数值时左右边缘为半圆。 的本地化字符串。
        /// </summary>
        public static string CustomCornerRadiusDescription {
            get {
                return ResourceManager.GetString("CustomCornerRadiusDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        public static string SectionFont {
            get {
                return ResourceManager.GetString("SectionFont", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字体大小 的本地化字符串。
        /// </summary>
        public static string FontSizeHeader {
            get {
                return ResourceManager.GetString("FontSizeHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 调整组件上各类字体的大小，将覆盖【外观】设置和主界面行中设置的字体大小。 的本地化字符串。
        /// </summary>
        public static string FontSizeDescription {
            get {
                return ResourceManager.GetString("FontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 次级字体大小 的本地化字符串。
        /// </summary>
        public static string SecondaryFontSize {
            get {
                return ResourceManager.GetString("SecondaryFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间点附加信息等 的本地化字符串。
        /// </summary>
        public static string SecondaryFontSizeDescription {
            get {
                return ResourceManager.GetString("SecondaryFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正文字体大小 的本地化字符串。
        /// </summary>
        public static string BodyFontSize {
            get {
                return ResourceManager.GetString("BodyFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面默认字体大小 的本地化字符串。
        /// </summary>
        public static string BodyFontSizeDescription {
            get {
                return ResourceManager.GetString("BodyFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 强调字体大小 的本地化字符串。
        /// </summary>
        public static string EmphasizedFontSize {
            get {
                return ResourceManager.GetString("EmphasizedFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课程表、时钟、提醒标题、天气预报等内容 的本地化字符串。
        /// </summary>
        public static string EmphasizedFontSizeDescription {
            get {
                return ResourceManager.GetString("EmphasizedFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 大号字体大小 的本地化字符串。
        /// </summary>
        public static string LargeFontSize {
            get {
                return ResourceManager.GetString("LargeFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课程预报等内容 的本地化字符串。
        /// </summary>
        public static string LargeFontSizeDescription {
            get {
                return ResourceManager.GetString("LargeFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字体颜色 的本地化字符串。
        /// </summary>
        public static string FontColorHeader {
            get {
                return ResourceManager.GetString("FontColorHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 调整字体颜色，将覆盖【外观】设置和主界面行中设置的值。 的本地化字符串。
        /// </summary>
        public static string FontColorDescription {
            get {
                return ResourceManager.GetString("FontColorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑… 的本地化字符串。
        /// </summary>
        public static string EditEllipsisText {
            get {
                return ResourceManager.GetString("EditEllipsisText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新功能：现在可以使用⌈编辑模式⌋更加直观地编辑主界面上的组件！ 的本地化字符串。
        /// </summary>
        public static string EditModeInfoBarMessage {
            get {
                return ResourceManager.GetString("EditModeInfoBarMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 进入编辑模式 的本地化字符串。
        /// </summary>
        public static string EnterEditModeButton {
            get {
                return ResourceManager.GetString("EnterEditModeButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建组件配置 的本地化字符串。
        /// </summary>
        public static string CreateConfigDialogTitle {
            get {
                return ResourceManager.GetString("CreateConfigDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组件名 的本地化字符串。
        /// </summary>
        public static string ComponentNameLabel {
            get {
                return ResourceManager.GetString("ComponentNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 至少需要保留 1 个主界面行。 的本地化字符串。
        /// </summary>
        public static string AtLeastOneLineWarning {
            get {
                return ResourceManager.GetString("AtLeastOneLineWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您已经禁用了所有主界面行的提醒显示功能。如果没有插件注册其它提醒消费者，提醒将不会显示，也不会播放提醒音效、特效和语音。 的本地化字符串。
        /// </summary>
        public static string AllNotificationDisabledWarning {
            get {
                return ResourceManager.GetString("AllNotificationDisabledWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已将第一行设置为主要行。 的本地化字符串。
        /// </summary>
        public static string FirstLineSetAsMainToast {
            get {
                return ResourceManager.GetString("FirstLineSetAsMainToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已向上创建新主界面行。 的本地化字符串。
        /// </summary>
        public static string NewLineAboveToast {
            get {
                return ResourceManager.GetString("NewLineAboveToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已向下创建新主界面行。 的本地化字符串。
        /// </summary>
        public static string NewLineBelowToast {
            get {
                return ResourceManager.GetString("NewLineBelowToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不能将容器组件移动到自身（或其子级）的子组件中。 的本地化字符串。
        /// </summary>
        public static string MoveIntoSelfWarning {
            get {
                return ResourceManager.GetString("MoveIntoSelfWarning", resourceCulture);
            }
        }
    }
}
