//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.SettingsPage.Plugins {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.SettingsPage.Plugins.Localization.SettingsPage.Plugins", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 项目主页 的本地化字符串。
        /// </summary>
        public static string ProjectHomepage {
            get {
                return ResourceManager.GetString("ProjectHomepage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已加载 的本地化字符串。
        /// </summary>
        public static string StatusLoaded {
            get {
                return ResourceManager.GetString("StatusLoaded", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已禁用 的本地化字符串。
        /// </summary>
        public static string StatusDisabled {
            get {
                return ResourceManager.GetString("StatusDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string StatusError {
            get {
                return ResourceManager.GetString("StatusError", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未加载 的本地化字符串。
        /// </summary>
        public static string StatusNotLoaded {
            get {
                return ResourceManager.GetString("StatusNotLoaded", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已启用 的本地化字符串。
        /// </summary>
        public static string EnabledLabel {
            get {
                return ResourceManager.GetString("EnabledLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新 的本地化字符串。
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 移除 的本地化字符串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 撤销移除 的本地化字符串。
        /// </summary>
        public static string UndoRemove {
            get {
                return ResourceManager.GetString("UndoRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 安装 的本地化字符串。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重启以应用更改 的本地化字符串。
        /// </summary>
        public static string RestartToApply {
            get {
                return ResourceManager.GetString("RestartToApply", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此插件未声明支持当前所运行的操作系统。此插件可能不能正常按预期工作。 的本地化字符串。
        /// </summary>
        public static string UnsupportedOSWarning {
            get {
                return ResourceManager.GetString("UnsupportedOSWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法安装插件，请检查您的网络连接。更换插件镜像源可能可以解决此问题。 的本地化字符串。
        /// </summary>
        public static string InstallFailedNetworkMessage {
            get {
                return ResourceManager.GetString("InstallFailedNetworkMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更换插件镜像源 的本地化字符串。
        /// </summary>
        public static string ChangePluginMirror {
            get {
                return ResourceManager.GetString("ChangePluginMirror", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更多选项… 的本地化字符串。
        /// </summary>
        public static string MoreOptionsToolTip {
            get {
                return ResourceManager.GetString("MoreOptionsToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打包插件 的本地化字符串。
        /// </summary>
        public static string PackPlugin {
            get {
                return ResourceManager.GetString("PackPlugin", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开插件文件夹… 的本地化字符串。
        /// </summary>
        public static string OpenPluginFolder {
            get {
                return ResourceManager.GetString("OpenPluginFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开配置文件夹… 的本地化字符串。
        /// </summary>
        public static string OpenPluginConfigFolder {
            get {
                return ResourceManager.GetString("OpenPluginConfigFolder", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 概览 的本地化字符串。
        /// </summary>
        public static string OverviewTab {
            get {
                return ResourceManager.GetString("OverviewTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 错误信息 的本地化字符串。
        /// </summary>
        public static string ErrorInfoTab {
            get {
                return ResourceManager.GetString("ErrorInfoTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 依赖项 的本地化字符串。
        /// </summary>
        public static string DependenciesTab {
            get {
                return ResourceManager.GetString("DependenciesTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件 ID 的本地化字符串。
        /// </summary>
        public static string PluginIdColumnHeader {
            get {
                return ResourceManager.GetString("PluginIdColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 必选？ 的本地化字符串。
        /// </summary>
        public static string RequiredColumnHeader {
            get {
                return ResourceManager.GetString("RequiredColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件更新设置 的本地化字符串。
        /// </summary>
        public static string PluginUpdateSettingsTitle {
            get {
                return ResourceManager.GetString("PluginUpdateSettingsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件有更新时通知我 的本地化字符串。
        /// </summary>
        public static string NotifyOnPluginUpdates {
            get {
                return ResourceManager.GetString("NotifyOnPluginUpdates", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自动更新插件 的本地化字符串。
        /// </summary>
        public static string AutoUpdatePlugins {
            get {
                return ResourceManager.GetString("AutoUpdatePlugins", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 管理插件源 的本地化字符串。
        /// </summary>
        public static string ManagePluginSources {
            get {
                return ResourceManager.GetString("ManagePluginSources", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 内置插件源 的本地化字符串。
        /// </summary>
        public static string BuiltinPluginSources {
            get {
                return ResourceManager.GetString("BuiltinPluginSources", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 内置插件源镜像 的本地化字符串。
        /// </summary>
        public static string BuiltinMirrorLabel {
            get {
                return ResourceManager.GetString("BuiltinMirrorLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 忽略 SSL/TLS 证书错误 的本地化字符串。
        /// </summary>
        public static string IgnoreSslErrors {
            get {
                return ResourceManager.GetString("IgnoreSslErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 禁用插件镜像证书校验, 将降低安全性。 的本地化字符串。
        /// </summary>
        public static string IgnoreSslToolTip {
            get {
                return ResourceManager.GetString("IgnoreSslToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义插件源 的本地化字符串。
        /// </summary>
        public static string CustomPluginSources {
            get {
                return ResourceManager.GetString("CustomPluginSources", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 镜像 的本地化字符串。
        /// </summary>
        public static string MirrorColumnHeader {
            get {
                return ResourceManager.GetString("MirrorColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 安装未知来源的插件可能存在风险。 的本地化字符串。
        /// </summary>
        public static string UnknownSourceRiskWarning {
            get {
                return ResourceManager.GetString("UnknownSourceRiskWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 找不到符合条件的插件，请调整筛选条件后重试 的本地化字符串。
        /// </summary>
        public static string NoMatchingPlugins {
            get {
                return ResourceManager.GetString("NoMatchingPlugins", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 还没有安装任何插件，不妨去插件市场看看吧 的本地化字符串。
        /// </summary>
        public static string NoPluginsInstalled {
            get {
                return ResourceManager.GetString("NoPluginsInstalled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 前往插件市场 的本地化字符串。
        /// </summary>
        public static string GoToMarket {
            get {
                return ResourceManager.GetString("GoToMarket", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件详细 的本地化字符串。
        /// </summary>
        public static string PluginDetails {
            get {
                return ResourceManager.GetString("PluginDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 搜索插件… 的本地化字符串。
        /// </summary>
        public static string SearchPluginsWatermark {
            get {
                return ResourceManager.GetString("SearchPluginsWatermark", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 市场 的本地化字符串。
        /// </summary>
        public static string MarketTab {
            get {
                return ResourceManager.GetString("MarketTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已安装 的本地化字符串。
        /// </summary>
        public static string InstalledTab {
            get {
                return ResourceManager.GetString("InstalledTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 从缓存重载插件源 的本地化字符串。
        /// </summary>
        public static string ReloadFromCache {
            get {
                return ResourceManager.GetString("ReloadFromCache", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 管理插件源… 的本地化字符串。
        /// </summary>
        public static string ManagePluginSourcesMenu {
            get {
                return ResourceManager.GetString("ManagePluginSourcesMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件更新设置… 的本地化字符串。
        /// </summary>
        public static string PluginUpdateSettingsMenu {
            get {
                return ResourceManager.GetString("PluginUpdateSettingsMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 从本地安装… 的本地化字符串。
        /// </summary>
        public static string InstallFromLocal {
            get {
                return ResourceManager.GetString("InstallFromLocal", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 下载量 的本地化字符串。
        /// </summary>
        public static string DownloadsToolTip {
            get {
                return ResourceManager.GetString("DownloadsToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此插件将在重启后被移除。 的本地化字符串。
        /// </summary>
        public static string PendingRemoveToolTip {
            get {
                return ResourceManager.GetString("PendingRemoveToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件需要重启以应用更改。 的本地化字符串。
        /// </summary>
        public static string RestartRequiredToolTip {
            get {
                return ResourceManager.GetString("RestartRequiredToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 加载此插件时出现错误。 的本地化字符串。
        /// </summary>
        public static string LoadErrorToolTip {
            get {
                return ResourceManager.GetString("LoadErrorToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示诊断信息 的本地化字符串。
        /// </summary>
        public static string ShowDiagnosticToolTip {
            get {
                return ResourceManager.GetString("ShowDiagnosticToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新可用。 的本地化字符串。
        /// </summary>
        public static string UpdateAvailableToolTip {
            get {
                return ResourceManager.GetString("UpdateAvailableToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此插件已安装。 的本地化字符串。
        /// </summary>
        public static string AlreadyInstalledToolTip {
            get {
                return ResourceManager.GetString("AlreadyInstalledToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用插件 的本地化字符串。
        /// </summary>
        public static string EnablePluginToolTip {
            get {
                return ResourceManager.GetString("EnablePluginToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件 的本地化字符串。
        /// </summary>
        public static string PluginsHeader {
            get {
                return ResourceManager.GetString("PluginsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 欢迎使用插件！插件可以扩展 ClassFabric 的功能，比如添加一个组件，或者和其它软件联动，等等。 的本地化字符串。
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 需要注意，插件可以以 ClassFabric 的身份使用各项系统资源并请求任意权限，还可以自由访问设备上的所有文件。请不... 的本地化字符串。
        /// </summary>
        public static string MarketWarningText {
            get {
                return ResourceManager.GetString("MarketWarningText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 同意并开始使用插件 的本地化字符串。
        /// </summary>
        public static string AgreeAndStart {
            get {
                return ResourceManager.GetString("AgreeAndStart", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在解析... 的本地化字符串。
        /// </summary>
        public static string ParsingText {
            get {
                return ResourceManager.GetString("ParsingText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 共 的本地化字符串。
        /// </summary>
        public static string DragFilesPrefix {
            get {
                return ResourceManager.GetString("DragFilesPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 个文件，识别到 的本地化字符串。
        /// </summary>
        public static string DragFilesMiddle {
            get {
                return ResourceManager.GetString("DragFilesMiddle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 个插件包 的本地化字符串。
        /// </summary>
        public static string DragFilesSuffix {
            get {
                return ResourceManager.GetString("DragFilesSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 > 无法加载文档：{0} 的本地化字符串。
        /// </summary>
        public static string ReadmeLoadFailed {
            get {
                return ResourceManager.GetString("ReadmeLoadFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法打开所选插件包文件。 的本地化字符串。
        /// </summary>
        public static string CannotOpenPackageFile {
            get {
                return ResourceManager.GetString("CannotOpenPackageFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法打包插件 {0} 的本地化字符串。
        /// </summary>
        public static string PackPluginFailed {
            get {
                return ResourceManager.GetString("PackPluginFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未能从选择的文件中解析出任何可安装的插件包。 的本地化字符串。
        /// </summary>
        public static string NoValidPackagesToast {
            get {
                return ResourceManager.GetString("NoValidPackagesToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确认安装? 的本地化字符串。
        /// </summary>
        public static string InstallConfirmTitle {
            get {
                return ResourceManager.GetString("InstallConfirmTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法重新打开所选插件包。 的本地化字符串。
        /// </summary>
        public static string CannotReopenPackageFile {
            get {
                return ResourceManager.GetString("CannotReopenPackageFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法安装插件 {0} 的本地化字符串。
        /// </summary>
        public static string InstallPluginFailedToast {
            get {
                return ResourceManager.GetString("InstallPluginFailedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 成功安装了 {0} 个插件。 的本地化字符串。
        /// </summary>
        public static string InstallSuccessToast {
            get {
                return ResourceManager.GetString("InstallSuccessToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 安装失败：{0} 个插件。 的本地化字符串。
        /// </summary>
        public static string InstallFailedToast {
            get {
                return ResourceManager.GetString("InstallFailedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 从本地安装插件 的本地化字符串。
        /// </summary>
        public static string InstallFromLocalDialogTitle {
            get {
                return ResourceManager.GetString("InstallFromLocalDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 操作系统不受该插件支持 的本地化字符串。
        /// </summary>
        public static string UnsupportedOSDialogTitle {
            get {
                return ResourceManager.GetString("UnsupportedOSDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此插件所声明支持的操作系统并未包括当前所运行的操作系统。 如果继续安装此插件，此插件将可能无法正常工作。您要继续安装此插... 的本地化字符串。
        /// </summary>
        public static string UnsupportedOSContent {
            get {
                return ResourceManager.GetString("UnsupportedOSContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 缺少依赖项 的本地化字符串。
        /// </summary>
        public static string MissingDependenciesTitle {
            get {
                return ResourceManager.GetString("MissingDependenciesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此插件的部分必选依赖项未安装且无法从市场获取。如果继续安装此插件，此插件将可能无法工作。您要继续安装此插件吗？ 未找到的... 的本地化字符串。
        /// </summary>
        public static string MissingDependenciesContent {
            get {
                return ResourceManager.GetString("MissingDependenciesContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        public static string DialogContinue {
            get {
                return ResourceManager.GetString("DialogContinue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该插件加载失败。请确认插件与当前 ClassFabric 版本兼容，或联系插件作者。 的本地化字符串。
        /// </summary>
        public static string DiagnosticDefaultMessage {
            get {
                return ResourceManager.GetString("DiagnosticDefaultMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未记录技术详情。 的本地化字符串。
        /// </summary>
        public static string NoTechnicalDetails {
            get {
                return ResourceManager.GetString("NoTechnicalDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件加载诊断 的本地化字符串。
        /// </summary>
        public static string PluginDiagnosticTitle {
            get {
                return ResourceManager.GetString("PluginDiagnosticTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 复制诊断信息 的本地化字符串。
        /// </summary>
        public static string CopyDiagnosticInfo {
            get {
                return ResourceManager.GetString("CopyDiagnosticInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 复制失败，请全选诊断信息文本后手动复制。 的本地化字符串。
        /// </summary>
        public static string CopyFailedToast {
            get {
                return ResourceManager.GetString("CopyFailedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 诊断信息已复制到剪贴板 的本地化字符串。
        /// </summary>
        public static string DiagnosticCopiedToast {
            get {
                return ResourceManager.GetString("DiagnosticCopiedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法加载插件源 的本地化字符串。
        /// </summary>
        public static string LoadPluginSourceFailedToast {
            get {
                return ResourceManager.GetString("LoadPluginSourceFailedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 仅支持 {0} 插件包 的本地化字符串。
        /// </summary>
        public static string DragInvalidHint {
            get {
                return ResourceManager.GetString("DragInvalidHint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 请拖入插件包文件 的本地化字符串。
        /// </summary>
        public static string DragInvalidSubHint {
            get {
                return ResourceManager.GetString("DragInvalidSubHint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 松开以安装 1 个插件 的本地化字符串。
        /// </summary>
        public static string DragInstallHintOne {
            get {
                return ResourceManager.GetString("DragInstallHintOne", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 松开以安装 {0} 个插件 的本地化字符串。
        /// </summary>
        public static string DragInstallHintMany {
            get {
                return ResourceManager.GetString("DragInstallHintMany", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 将忽略 {0} 个不受支持的文件 的本地化字符串。
        /// </summary>
        public static string DragIgnoreFiles {
            get {
                return ResourceManager.GetString("DragIgnoreFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 支持多选（{0}） 的本地化字符串。
        /// </summary>
        public static string DragMultiSelectHint {
            get {
                return ResourceManager.GetString("DragMultiSelectHint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
    }
}
