//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.SettingsPage.Appearance {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.SettingsPage.Appearance.Localization.SettingsPage.Appearance", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 基本 的本地化字符串。
        /// </summary>
        public static string SectionBasic {
            get {
                return ResourceManager.GetString("SectionBasic", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string SectionTheme {
            get {
                return ResourceManager.GetString("SectionTheme", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        public static string SectionFont {
            get {
                return ResourceManager.GetString("SectionFont", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 界面缩放 的本地化字符串。
        /// </summary>
        public static string ScaleHeader {
            get {
                return ResourceManager.GetString("ScaleHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面的缩放大小。 的本地化字符串。
        /// </summary>
        public static string ScaleDescription {
            get {
                return ResourceManager.GetString("ScaleDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 背景颜色 的本地化字符串。
        /// </summary>
        public static string BackgroundColorHeader {
            get {
                return ResourceManager.GetString("BackgroundColorHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面背景颜色，禁用时将根据应用主题自动选择颜色。 的本地化字符串。
        /// </summary>
        public static string BackgroundColorDescription {
            get {
                return ResourceManager.GetString("BackgroundColorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 背景不透明度 的本地化字符串。
        /// </summary>
        public static string BackgroundOpacityHeader {
            get {
                return ResourceManager.GetString("BackgroundOpacityHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面背景的不透明度。 的本地化字符串。
        /// </summary>
        public static string BackgroundOpacityDescription {
            get {
                return ResourceManager.GetString("BackgroundOpacityDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 圆角半径 的本地化字符串。
        /// </summary>
        public static string CornerRadiusHeader {
            get {
                return ResourceManager.GetString("CornerRadiusHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面圆角半径，调至最大数值时左右边缘为半圆。 的本地化字符串。
        /// </summary>
        public static string CornerRadiusDescription {
            get {
                return ResourceManager.GetString("CornerRadiusDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 行间隔 的本地化字符串。
        /// </summary>
        public static string LineSpacingHeader {
            get {
                return ResourceManager.GetString("LineSpacingHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面行间间隔。 的本地化字符串。
        /// </summary>
        public static string LineSpacingDescription {
            get {
                return ResourceManager.GetString("LineSpacingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 分体主界面 的本地化字符串。
        /// </summary>
        public static string SeparateMainWindowHeader {
            get {
                return ResourceManager.GetString("SeparateMainWindowHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后组件会分开。 的本地化字符串。
        /// </summary>
        public static string SeparateMainWindowDescription {
            get {
                return ResourceManager.GetString("SeparateMainWindowDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 应用主题 的本地化字符串。
        /// </summary>
        public static string AppThemeHeader {
            get {
                return ResourceManager.GetString("AppThemeHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 控制应用的明暗主题。 的本地化字符串。
        /// </summary>
        public static string AppThemeDescription {
            get {
                return ResourceManager.GetString("AppThemeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 跟随系统 的本地化字符串。
        /// </summary>
        public static string ThemeFollowSystem {
            get {
                return ResourceManager.GetString("ThemeFollowSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 明亮 的本地化字符串。
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 黑暗 的本地化字符串。
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主题色来源 的本地化字符串。
        /// </summary>
        public static string ThemeColorSourceHeader {
            get {
                return ResourceManager.GetString("ThemeColorSourceHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 控制应用选取主题色的途径。 的本地化字符串。
        /// </summary>
        public static string ThemeColorSourceDescription {
            get {
                return ResourceManager.GetString("ThemeColorSourceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义 的本地化字符串。
        /// </summary>
        public static string ColorSourceCustom {
            get {
                return ResourceManager.GetString("ColorSourceCustom", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 系统壁纸 的本地化字符串。
        /// </summary>
        public static string ColorSourceWallpaper {
            get {
                return ResourceManager.GetString("ColorSourceWallpaper", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 系统 的本地化字符串。
        /// </summary>
        public static string ColorSourceSystem {
            get {
                return ResourceManager.GetString("ColorSourceSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 屏幕主题色 的本地化字符串。
        /// </summary>
        public static string ColorSourceScreen {
            get {
                return ResourceManager.GetString("ColorSourceScreen", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 强调色 的本地化字符串。
        /// </summary>
        public static string AccentColorHeader {
            get {
                return ResourceManager.GetString("AccentColorHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 应用显示强调元素时所使用的颜色。 的本地化字符串。
        /// </summary>
        public static string AccentColorDescription {
            get {
                return ResourceManager.GetString("AccentColorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义字体 的本地化字符串。
        /// </summary>
        public static string CustomFontHeader {
            get {
                return ResourceManager.GetString("CustomFontHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义主界面显示课表的字体。 的本地化字符串。
        /// </summary>
        public static string CustomFontDescription {
            get {
                return ResourceManager.GetString("CustomFontDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 HarmonyOS Sans SC（默认） 的本地化字符串。
        /// </summary>
        public static string DefaultFontOption {
            get {
                return ResourceManager.GetString("DefaultFontOption", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义字重 的本地化字符串。
        /// </summary>
        public static string CustomFontWeightHeader {
            get {
                return ResourceManager.GetString("CustomFontWeightHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义主界面显示的字体的字重，需要对应字体支持。 的本地化字符串。
        /// </summary>
        public static string CustomFontWeightDescription {
            get {
                return ResourceManager.GetString("CustomFontWeightDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字体大小 的本地化字符串。
        /// </summary>
        public static string FontSizeHeader {
            get {
                return ResourceManager.GetString("FontSizeHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 调整主界面上各类字体的大小。 的本地化字符串。
        /// </summary>
        public static string FontSizeDescription {
            get {
                return ResourceManager.GetString("FontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 次级字体大小 的本地化字符串。
        /// </summary>
        public static string SecondaryFontSize {
            get {
                return ResourceManager.GetString("SecondaryFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间点附加信息等 的本地化字符串。
        /// </summary>
        public static string SecondaryFontSizeDescription {
            get {
                return ResourceManager.GetString("SecondaryFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正文字体大小 的本地化字符串。
        /// </summary>
        public static string BodyFontSize {
            get {
                return ResourceManager.GetString("BodyFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主界面默认字体大小 的本地化字符串。
        /// </summary>
        public static string BodyFontSizeDescription {
            get {
                return ResourceManager.GetString("BodyFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 强调字体大小 的本地化字符串。
        /// </summary>
        public static string EmphasizedFontSize {
            get {
                return ResourceManager.GetString("EmphasizedFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课程表、时钟、提醒标题、天气预报等内容 的本地化字符串。
        /// </summary>
        public static string EmphasizedFontSizeDescription {
            get {
                return ResourceManager.GetString("EmphasizedFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 大号字体大小 的本地化字符串。
        /// </summary>
        public static string LargeFontSize {
            get {
                return ResourceManager.GetString("LargeFontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课程预报等内容 的本地化字符串。
        /// </summary>
        public static string LargeFontSizeDescription {
            get {
                return ResourceManager.GetString("LargeFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字体颜色 的本地化字符串。
        /// </summary>
        public static string FontColorHeader {
            get {
                return ResourceManager.GetString("FontColorHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 调整字体颜色，将覆盖主题默认值。 的本地化字符串。
        /// </summary>
        public static string FontColorDescription {
            get {
                return ResourceManager.GetString("FontColorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字体预览 的本地化字符串。
        /// </summary>
        public static string FontPreviewTab {
            get {
                return ResourceManager.GetString("FontPreviewTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当有一天你不再纠结于答案 当我们又重逢于天涯或沧海 语文 数学 英语 历史 物理 政治 化学 生物 地理 the qui... 的本地化字符串。
        /// </summary>
        public static string FontPreviewSample {
            get {
                return ResourceManager.GetString("FontPreviewSample", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字号预览 的本地化字符串。
        /// </summary>
        public static string FontSizePreviewTab {
            get {
                return ResourceManager.GetString("FontSizePreviewTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 测试文本 的本地化字符串。
        /// </summary>
        public static string FontSizeTestText {
            get {
                return ResourceManager.GetString("FontSizeTestText", resourceCulture);
            }
        }
    }
}
