//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Views.DataTransfer {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Views.DataTransfer.Localization.Views.DataTransfer", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 数据迁移 的本地化字符串。
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 向 ClassFabric 导入或从 ClassFabric 导出数据。 的本地化字符串。
        /// </summary>
        public static string PageDescription {
            get {
                return ResourceManager.GetString("PageDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string ImportTab {
            get {
                return ResourceManager.GetString("ImportTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string ExportTab {
            get {
                return ResourceManager.GetString("ExportTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此处的数据导出功能主要用于在不同 ClassFabric 实例间转移数据。若需导出诊断信息，请前往【应用设置】->【更多... 的本地化字符串。
        /// </summary>
        public static string ExportInfoBarMessage {
            get {
                return ResourceManager.GetString("ExportInfoBarMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择要导入的数据 的本地化字符串。
        /// </summary>
        public static string SelectDataToImport {
            get {
                return ResourceManager.GetString("SelectDataToImport", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择要导出的数据 的本地化字符串。
        /// </summary>
        public static string SelectDataToExport {
            get {
                return ResourceManager.GetString("SelectDataToExport", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择要导入的信息 的本地化字符串。
        /// </summary>
        public static string SelectInfoToImport {
            get {
                return ResourceManager.GetString("SelectInfoToImport", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择要导出的信息 的本地化字符串。
        /// </summary>
        public static string SelectInfoToExport {
            get {
                return ResourceManager.GetString("SelectInfoToExport", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课表配置 的本地化字符串。
        /// </summary>
        public static string ProfileDataHeader {
            get {
                return ResourceManager.GetString("ProfileDataHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 包括课表内容、时间安排、科目定义等信息。 的本地化字符串。
        /// </summary>
        public static string ProfileDataDescription {
            get {
                return ResourceManager.GetString("ProfileDataDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 应用设置 的本地化字符串。
        /// </summary>
        public static string SettingsDataHeader {
            get {
                return ResourceManager.GetString("SettingsDataHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 包括应用的各个首选项，如隐藏设置、颜色设置、提醒/铃声设置、天气信息等。 的本地化字符串。
        /// </summary>
        public static string SettingsDataDescription {
            get {
                return ResourceManager.GetString("SettingsDataDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 其它配置 的本地化字符串。
        /// </summary>
        public static string OtherConfigHeader {
            get {
                return ResourceManager.GetString("OtherConfigHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组件、自动化等配置文件。 的本地化字符串。
        /// </summary>
        public static string OtherConfigDescription {
            get {
                return ResourceManager.GetString("OtherConfigDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 上一步 的本地化字符串。
        /// </summary>
        public static string PreviousToolTip {
            get {
                return ResourceManager.GetString("PreviousToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string NextToolTip {
            get {
                return ResourceManager.GetString("NextToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导入来源 的本地化字符串。
        /// </summary>
        public static string ImportSourceTitle {
            get {
                return ResourceManager.GetString("ImportSourceTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导出目标 的本地化字符串。
        /// </summary>
        public static string ExportTargetTitle {
            get {
                return ResourceManager.GetString("ExportTargetTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择要导入的数据来源。 的本地化字符串。
        /// </summary>
        public static string SelectImportSourceDescription {
            get {
                return ResourceManager.GetString("SelectImportSourceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择要导出到的目标。 的本地化字符串。
        /// </summary>
        public static string SelectExportTargetDescription {
            get {
                return ResourceManager.GetString("SelectExportTargetDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 浏览… 的本地化字符串。
        /// </summary>
        public static string BrowseHeader {
            get {
                return ResourceManager.GetString("BrowseHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 手动浏览导入位置 的本地化字符串。
        /// </summary>
        public static string BrowseImportDescription {
            get {
                return ResourceManager.GetString("BrowseImportDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 手动浏览导出位置 的本地化字符串。
        /// </summary>
        public static string BrowseExportDescription {
            get {
                return ResourceManager.GetString("BrowseExportDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在导入 的本地化字符串。
        /// </summary>
        public static string ImportingTitle {
            get {
                return ResourceManager.GetString("ImportingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在导出 的本地化字符串。
        /// </summary>
        public static string ExportingTitle {
            get {
                return ResourceManager.GetString("ExportingTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 请坐和放宽，导入很快就能完成。 的本地化字符串。
        /// </summary>
        public static string ImportingDescription {
            get {
                return ResourceManager.GetString("ImportingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 请坐和放宽，导出很快就能完成。 的本地化字符串。
        /// </summary>
        public static string ExportingDescription {
            get {
                return ResourceManager.GetString("ExportingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导入完成 的本地化字符串。
        /// </summary>
        public static string ImportCompleteTitle {
            get {
                return ResourceManager.GetString("ImportCompleteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导出完成 的本地化字符串。
        /// </summary>
        public static string ExportCompleteTitle {
            get {
                return ResourceManager.GetString("ExportCompleteTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已成功完成导入。 的本地化字符串。
        /// </summary>
        public static string ImportCompleteDescription {
            get {
                return ResourceManager.GetString("ImportCompleteDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已成功完成导出。 的本地化字符串。
        /// </summary>
        public static string ExportCompleteDescription {
            get {
                return ResourceManager.GetString("ExportCompleteDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string FinishToolTip {
            get {
                return ResourceManager.GetString("FinishToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 支持从 1.x 版本的 ClassIsland 导入课表、组件配置、自动化配置、应用设置、部分插件和主题等数据。 的本地化字符串。
        /// </summary>
        public static string ImportDescriptionFromClassIsland {
            get {
                return ResourceManager.GetString("ImportDescriptionFromClassIsland", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择先前版本的 ClassIsland 实例 的本地化字符串。
        /// </summary>
        public static string PickerTitleFromClassIsland {
            get {
                return ResourceManager.GetString("PickerTitleFromClassIsland", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassIsland 可执行文件 的本地化字符串。
        /// </summary>
        public static string FileTypeClassIslandExecutable {
            get {
                return ResourceManager.GetString("FileTypeClassIslandExecutable", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重启以继续 的本地化字符串。
        /// </summary>
        public static string RestartToContinueTitle {
            get {
                return ResourceManager.GetString("RestartToContinueTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 应用需要重启以继续导入操作，要重启以继续导入吗？ 的本地化字符串。
        /// </summary>
        public static string RestartToContinueImportContent {
            get {
                return ResourceManager.GetString("RestartToContinueImportContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重启并继续 的本地化字符串。
        /// </summary>
        public static string RestartAndContinue {
            get {
                return ResourceManager.GetString("RestartAndContinue", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 源 ClassFabric 版本必须在 1.7.0.x，才能进行导入。 的本地化字符串。
        /// </summary>
        public static string ErrorSourceVersionNotSupported {
            get {
                return ResourceManager.GetString("ErrorSourceVersionNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导入时发生意外错误 的本地化字符串。
        /// </summary>
        public static string UnexpectedImportError {
            get {
                return ResourceManager.GetString("UnexpectedImportError", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 支持从 ClassFabric 2.x 数据文件导入课表、组件配置、自动化配置、应用设置、部分插件和主题等数据。 的本地化字符串。
        /// </summary>
        public static string ImportDescriptionFromClassFabric2 {
            get {
                return ResourceManager.GetString("ImportDescriptionFromClassFabric2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 浏览 ClassFabric 2 导出文件 的本地化字符串。
        /// </summary>
        public static string PickerTitleFromClassFabric2 {
            get {
                return ResourceManager.GetString("PickerTitleFromClassFabric2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 数据文件 的本地化字符串。
        /// </summary>
        public static string FileTypeClassFabricData {
            get {
                return ResourceManager.GetString("FileTypeClassFabricData", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法打开所选 ClassFabric 数据文件。 的本地化字符串。
        /// </summary>
        public static string ErrorCannotOpenDataFile {
            get {
                return ResourceManager.GetString("ErrorCannotOpenDataFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 压缩包包含无效路径：{0} 的本地化字符串。
        /// </summary>
        public static string ErrorInvalidEntryPath {
            get {
                return ResourceManager.GetString("ErrorInvalidEntryPath", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 支持导出为可以导入到其它 ClassFabric 2 实例的文件格式。 的本地化字符串。
        /// </summary>
        public static string ExportDescription {
            get {
                return ResourceManager.GetString("ExportDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 浏览保存的导出文件 的本地化字符串。
        /// </summary>
        public static string PickerTitleForExport {
            get {
                return ResourceManager.GetString("PickerTitleForExport", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导出数据时发生意外错误。 的本地化字符串。
        /// </summary>
        public static string UnexpectedExportError {
            get {
                return ResourceManager.GetString("UnexpectedExportError", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 支持从 Class Widgets 1 导入全部课表信息和大部分配置。 的本地化字符串。
        /// </summary>
        public static string ImportDescriptionFromClassWidgets {
            get {
                return ResourceManager.GetString("ImportDescriptionFromClassWidgets", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 浏览 Class Widgets 安装（即有 ClassWidgets[.exe]）的文件夹或其数据目录 的本地化字符串。
        /// </summary>
        public static string PickerTitleFromClassWidgets {
            get {
                return ResourceManager.GetString("PickerTitleFromClassWidgets", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 应用需要重启以完全应用导入操作，要继续吗？ 的本地化字符串。
        /// </summary>
        public static string RestartToContinueApplyContent {
            get {
                return ResourceManager.GetString("RestartToContinueApplyContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在升级插件 的本地化字符串。
        /// </summary>
        public static string UpgradingPluginsTitle {
            get {
                return ResourceManager.GetString("UpgradingPluginsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在升级从 ClassIsland 1 导入的插件到兼容 ClassFabric 2 的版本，这可能需要一定的时间，应用... 的本地化字符串。
        /// </summary>
        public static string UpgradingPluginsBody {
            get {
                return ResourceManager.GetString("UpgradingPluginsBody", resourceCulture);
            }
        }
    }
}
