//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.SettingsPage.Refreshing {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.SettingsPage.Refreshing.Localization.SettingsPage.Refreshing", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 定期翻新 的本地化字符串。
        /// </summary>
        public static string RefreshingHeader {
            get {
                return ResourceManager.GetString("RefreshingHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当在长时间未启动 ClassFabric 的寒假/暑假等学期结束后的长假后启动 ClassFabric 时，显示桌面通知... 的本地化字符串。
        /// </summary>
        public static string RefreshingDescription {
            get {
                return ResourceManager.GetString("RefreshingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 将创建并切换到一个全新的配置文件。 的本地化字符串。
        /// </summary>
        public static string NewConfigDescription {
            get {
                return ResourceManager.GetString("NewConfigDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 将禁用已经启用的插件。 的本地化字符串。
        /// </summary>
        public static string DisablePluginsDescription {
            get {
                return ResourceManager.GetString("DisablePluginsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认翻新范围 的本地化字符串。
        /// </summary>
        public static string DefaultRefreshingScopes {
            get {
                return ResourceManager.GetString("DefaultRefreshingScopes", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认情况下将勾选以下翻新范围，翻新时会重置对应的设置。 的本地化字符串。
        /// </summary>
        public static string DefaultRefreshingScopesDescription {
            get {
                return ResourceManager.GetString("DefaultRefreshingScopesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 档案 的本地化字符串。
        /// </summary>
        public static string ScopeProfile {
            get {
                return ResourceManager.GetString("ScopeProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课表 的本地化字符串。
        /// </summary>
        public static string ScopeProfileClassPlans {
            get {
                return ResourceManager.GetString("ScopeProfileClassPlans", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间表 的本地化字符串。
        /// </summary>
        public static string ScopeProfileTimeLayouts {
            get {
                return ResourceManager.GetString("ScopeProfileTimeLayouts", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择保留的内容… 的本地化字符串。
        /// </summary>
        public static string ChooseReservedContent {
            get {
                return ResourceManager.GetString("ChooseReservedContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组件配置 的本地化字符串。
        /// </summary>
        public static string ScopeComponents {
            get {
                return ResourceManager.GetString("ScopeComponents", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自动化 的本地化字符串。
        /// </summary>
        public static string ScopeAutomations {
            get {
                return ResourceManager.GetString("ScopeAutomations", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 插件 的本地化字符串。
        /// </summary>
        public static string ScopePlugins {
            get {
                return ResourceManager.GetString("ScopePlugins", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 立即翻新 的本地化字符串。
        /// </summary>
        public static string RefreshNow {
            get {
                return ResourceManager.GetString("RefreshNow", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 迎新模式 的本地化字符串。
        /// </summary>
        public static string OnboardingModeHeader {
            get {
                return ResourceManager.GetString("OnboardingModeHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，在下次显示翻新提示时将其替换为迎新指引，指引不熟悉 ClassFabric 的新同学上手本应用，并对应用进行翻新... 的本地化字符串。
        /// </summary>
        public static string OnboardingModeDescription {
            get {
                return ResourceManager.GetString("OnboardingModeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 通知标题 的本地化字符串。
        /// </summary>
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 通知内容 的本地化字符串。
        /// </summary>
        public static string NotificationBody {
            get {
                return ResourceManager.GetString("NotificationBody", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重置为默认值 的本地化字符串。
        /// </summary>
        public static string ResetToDefault {
            get {
                return ResourceManager.GetString("ResetToDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 测试通知 的本地化字符串。
        /// </summary>
        public static string TestNotification {
            get {
                return ResourceManager.GetString("TestNotification", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 通知选项 的本地化字符串。
        /// </summary>
        public static string NotificationOptions {
            get {
                return ResourceManager.GetString("NotificationOptions", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 通知显示间隔 的本地化字符串。
        /// </summary>
        public static string NotificationDisplayInterval {
            get {
                return ResourceManager.GetString("NotificationDisplayInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设置在不启动 ClassFabric 多少天后显示翻新或迎新指引。 的本地化字符串。
        /// </summary>
        public static string NotificationDisplayIntervalDescription {
            get {
                return ResourceManager.GetString("NotificationDisplayIntervalDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天 的本地化字符串。
        /// </summary>
        public static string DayUnit {
            get {
                return ResourceManager.GetString("DayUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在下次启动时显示通知 的本地化字符串。
        /// </summary>
        public static string ShowNotificationOnNextStart {
            get {
                return ResourceManager.GetString("ShowNotificationOnNextStart", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，将在下一次启动应用时立即显示翻新或迎新指引通知。此选项生效后将被关闭。 的本地化字符串。
        /// </summary>
        public static string ShowNotificationOnNextStartDescription {
            get {
                return ResourceManager.GetString("ShowNotificationOnNextStartDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 立即退出应用 的本地化字符串。
        /// </summary>
        public static string ExitAppNow {
            get {
                return ResourceManager.GetString("ExitAppNow", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 最高通知显示次数 的本地化字符串。
        /// </summary>
        public static string MaxNotificationCount {
            get {
                return ResourceManager.GetString("MaxNotificationCount", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 如果用户忽略了通知，应用会在下次启动时再次发送给通知询问用户。这里可以设置翻新或迎新指引通知在触发后最多可以显示次数。 的本地化字符串。
        /// </summary>
        public static string MaxNotificationCountDescription {
            get {
                return ResourceManager.GetString("MaxNotificationCountDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 次 的本地化字符串。
        /// </summary>
        public static string TimesUnit {
            get {
                return ResourceManager.GetString("TimesUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 剩余通知次数： 的本地化字符串。
        /// </summary>
        public static string LeftNotificationCount {
            get {
                return ResourceManager.GetString("LeftNotificationCount", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重置迎新消息设置 的本地化字符串。
        /// </summary>
        public static string ResetOnboardingMessagesDialogTitle {
            get {
                return ResourceManager.GetString("ResetOnboardingMessagesDialogTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确定要重置迎新消息设置吗？此操作不可撤销！ 的本地化字符串。
        /// </summary>
        public static string ResetOnboardingMessagesDialogContent {
            get {
                return ResourceManager.GetString("ResetOnboardingMessagesDialogContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已重置迎新消息。 的本地化字符串。
        /// </summary>
        public static string OnboardingMessagesReset {
            get {
                return ResourceManager.GetString("OnboardingMessagesReset", resourceCulture);
            }
        }
    }
}
