<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ClassIsland.Core</AssemblyName>
    <RootNamespace>ClassIsland.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ClassFabric.Core\ClassFabric.Core.csproj" />
  </ItemGroup>
</Project>
