//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Controls.Components {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Controls.Components.Localization.Controls.Components", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 使用实际时间 的本地化字符串。
        /// </summary>
        public static string UseRealTime {
            get {
                return ResourceManager.GetString("UseRealTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示不经过时间偏移的系统时间。 的本地化字符串。
        /// </summary>
        public static string UseRealTimeDescription {
            get {
                return ResourceManager.GetString("UseRealTimeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示秒数 的本地化字符串。
        /// </summary>
        public static string ShowSeconds {
            get {
                return ResourceManager.GetString("ShowSeconds", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，时钟将显示精准到秒的时间。 的本地化字符串。
        /// </summary>
        public static string ShowSecondsDescription {
            get {
                return ResourceManager.GetString("ShowSecondsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 闪动时间分隔符 的本地化字符串。
        /// </summary>
        public static string FlashTimeSeparator {
            get {
                return ResourceManager.GetString("FlashTimeSeparator", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 模拟电子时钟的分隔符闪动效果。 的本地化字符串。
        /// </summary>
        public static string FlashTimeSeparatorDescription {
            get {
                return ResourceManager.GetString("FlashTimeSeparatorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 文本内容 的本地化字符串。
        /// </summary>
        public static string TextContent {
            get {
                return ResourceManager.GetString("TextContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 要显示的文本。 的本地化字符串。
        /// </summary>
        public static string TextContentDescription {
            get {
                return ResourceManager.GetString("TextContentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义字体颜色 的本地化字符串。
        /// </summary>
        public static string CustomFontColor {
            get {
                return ResourceManager.GetString("CustomFontColor", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择要显示文本的颜色。 的本地化字符串。
        /// </summary>
        public static string CustomFontColorDescription {
            get {
                return ResourceManager.GetString("CustomFontColorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 字体大小 的本地化字符串。
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 修改要显示的文本的大小。 的本地化字符串。
        /// </summary>
        public static string TextFontSizeDescription {
            get {
                return ResourceManager.GetString("TextFontSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 本页面仅包含组件设置，要调整显示天气的城市，请转到【天气】选项卡 的本地化字符串。
        /// </summary>
        public static string WeatherSettingsInfoBarMessage {
            get {
                return ResourceManager.GetString("WeatherSettingsInfoBarMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示天气信息 的本地化字符串。
        /// </summary>
        public static string ShowWeatherInfo {
            get {
                return ResourceManager.GetString("ShowWeatherInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示当前天气信息摘要。 的本地化字符串。
        /// </summary>
        public static string ShowWeatherInfoDescription {
            get {
                return ResourceManager.GetString("ShowWeatherInfoDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天气类型/气温 的本地化字符串。
        /// </summary>
        public static string WeatherTypeTemperature {
            get {
                return ResourceManager.GetString("WeatherTypeTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 湿度 的本地化字符串。
        /// </summary>
        public static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 风力 的本地化字符串。
        /// </summary>
        public static string WindPower {
            get {
                return ResourceManager.GetString("WindPower", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 气压 的本地化字符串。
        /// </summary>
        public static string AirPressure {
            get {
                return ResourceManager.GetString("AirPressure", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 体感温度 的本地化字符串。
        /// </summary>
        public static string FeelsLikeTemperature {
            get {
                return ResourceManager.GetString("FeelsLikeTemperature", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示预警信号 的本地化字符串。
        /// </summary>
        public static string ShowAlerts {
            get {
                return ResourceManager.GetString("ShowAlerts", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，预警将以图标形式显示在天气组件上。 的本地化字符串。
        /// </summary>
        public static string ShowAlertsDescription {
            get {
                return ResourceManager.GetString("ShowAlertsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示预警类型 的本地化字符串。
        /// </summary>
        public static string ShowAlertType {
            get {
                return ResourceManager.GetString("ShowAlertType", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设置何种情况下显示预警类型。 的本地化字符串。
        /// </summary>
        public static string ShowAlertTypeDescription {
            get {
                return ResourceManager.GetString("ShowAlertTypeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不显示 的本地化字符串。
        /// </summary>
        public static string DoNotShow {
            get {
                return ResourceManager.GetString("DoNotShow", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 仅当没有对应图标时 的本地化字符串。
        /// </summary>
        public static string OnlyWhenIconMissing {
            get {
                return ResourceManager.GetString("OnlyWhenIconMissing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 总是显示 的本地化字符串。
        /// </summary>
        public static string AlwaysShow {
            get {
                return ResourceManager.GetString("AlwaysShow", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示降水提示 的本地化字符串。
        /// </summary>
        public static string ShowRainTip {
            get {
                return ResourceManager.GetString("ShowRainTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，将显示降水即将到来的时间和降水剩余时间。正数代表降水即将到来的时间，负数代表剩余时间。 的本地化字符串。
        /// </summary>
        public static string ShowRainTipDescription {
            get {
                return ResourceManager.GetString("ShowRainTipDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 模糊长时间降雨倒计时时间显示精度 的本地化字符串。
        /// </summary>
        public static string FuzzyLongRainCountdownPrecision {
            get {
                return ResourceManager.GetString("FuzzyLongRainCountdownPrecision", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 开启后，大于 60min 的降雨时间将会以 0.5h 为单位模糊显示，关闭则总是以精确分钟显示。 的本地化字符串。
        /// </summary>
        public static string FuzzyLongRainCountdownPrecisionDescription {
            get {
                return ResourceManager.GetString("FuzzyLongRainCountdownPrecisionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 滚动组件仅在组件内容超出滚动组件宽度时才会开始滚动。您可能需要在【高级设置】中为本组件设置【最大宽度】或【固定宽度】以限... 的本地化字符串。
        /// </summary>
        public static string RollingWidthWarningMessage {
            get {
                return ResourceManager.GetString("RollingWidthWarningMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 滚动速度 的本地化字符串。
        /// </summary>
        public static string ScrollSpeed {
            get {
                return ResourceManager.GetString("ScrollSpeed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组件内容的滚动速度 的本地化字符串。
        /// </summary>
        public static string ScrollSpeedDescription {
            get {
                return ResourceManager.GetString("ScrollSpeedDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 px/秒 的本地化字符串。
        /// </summary>
        public static string SpeedUnitPixelsPerSecond {
            get {
                return ResourceManager.GetString("SpeedUnitPixelsPerSecond", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 定时暂停 的本地化字符串。
        /// </summary>
        public static string TimedPause {
            get {
                return ResourceManager.GetString("TimedPause", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，将在滚动到指定位置后暂停滚动一段时间 的本地化字符串。
        /// </summary>
        public static string TimedPauseDescription {
            get {
                return ResourceManager.GetString("TimedPauseDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 暂停时长 的本地化字符串。
        /// </summary>
        public static string PauseDuration {
            get {
                return ResourceManager.GetString("PauseDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 每次暂停时停留的时长 的本地化字符串。
        /// </summary>
        public static string PauseDurationDescription {
            get {
                return ResourceManager.GetString("PauseDurationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string SecondsUnit {
            get {
                return ResourceManager.GetString("SecondsUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 暂停位置 的本地化字符串。
        /// </summary>
        public static string PausePosition {
            get {
                return ResourceManager.GetString("PausePosition", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 暂停时的滚动偏移值 的本地化字符串。
        /// </summary>
        public static string PausePositionDescription {
            get {
                return ResourceManager.GetString("PausePositionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 满足规则时停止 的本地化字符串。
        /// </summary>
        public static string StopWhenRuleMet {
            get {
                return ResourceManager.GetString("StopWhenRuleMet", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在指定规则满足时停止滚动。停止时会停止滚动，并回到初始位置。 的本地化字符串。
        /// </summary>
        public static string RollingStopWhenRuleMetDescription {
            get {
                return ResourceManager.GetString("RollingStopWhenRuleMetDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑规则集… 的本地化字符串。
        /// </summary>
        public static string EditRuleset {
            get {
                return ResourceManager.GetString("EditRuleset", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 轮换间隔 的本地化字符串。
        /// </summary>
        public static string RotationInterval {
            get {
                return ResourceManager.GetString("RotationInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 组件自动轮换的间隔时间 的本地化字符串。
        /// </summary>
        public static string RotationIntervalDescription {
            get {
                return ResourceManager.GetString("RotationIntervalDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 轮换模式 的本地化字符串。
        /// </summary>
        public static string RotationMode {
            get {
                return ResourceManager.GetString("RotationMode", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设定轮换组件的行为 的本地化字符串。
        /// </summary>
        public static string RotationModeDescription {
            get {
                return ResourceManager.GetString("RotationModeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 循环 的本地化字符串。
        /// </summary>
        public static string LoopMode {
            get {
                return ResourceManager.GetString("LoopMode", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 随机 的本地化字符串。
        /// </summary>
        public static string RandomMode {
            get {
                return ResourceManager.GetString("RandomMode", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 往复 的本地化字符串。
        /// </summary>
        public static string PingPongMode {
            get {
                return ResourceManager.GetString("PingPongMode", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 满足规则时暂停 的本地化字符串。
        /// </summary>
        public static string PauseWhenRuleMet {
            get {
                return ResourceManager.GetString("PauseWhenRuleMet", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在指定规则满足时暂停轮播。 的本地化字符串。
        /// </summary>
        public static string PauseWhenRuleMetDescription {
            get {
                return ResourceManager.GetString("PauseWhenRuleMetDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在指定规则满足时停止轮播。停止时会停止轮播，并回到第一个组件。如果此处的规则和暂停规则同时满足，会停止轮播而不是暂停。 的本地化字符串。
        /// </summary>
        public static string SlideStopWhenRuleMetDescription {
            get {
                return ResourceManager.GetString("SlideStopWhenRuleMetDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用动画 的本地化字符串。
        /// </summary>
        public static string EnableAnimation {
            get {
                return ResourceManager.GetString("EnableAnimation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，将在切换组件时播放过渡动画。 的本地化字符串。
        /// </summary>
        public static string EnableAnimationDescription {
            get {
                return ResourceManager.GetString("EnableAnimationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此处的设置可以在档案设置中被附加设置覆盖。 的本地化字符串。
        /// </summary>
        public static string AttachedSettingsOverrideMessage {
            get {
                return ResourceManager.GetString("AttachedSettingsOverrideMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查看… 的本地化字符串。
        /// </summary>
        public static string ViewAttachedSettings {
            get {
                return ResourceManager.GetString("ViewAttachedSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示时间点附加信息 的本地化字符串。
        /// </summary>
        public static string ShowExtraInfoOnTimePoint {
            get {
                return ResourceManager.GetString("ShowExtraInfoOnTimePoint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在当前的时间点上显示当前时间点的附加信息。 的本地化字符串。
        /// </summary>
        public static string ShowExtraInfoOnTimePointDescription {
            get {
                return ResourceManager.GetString("ShowExtraInfoOnTimePointDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 要显示的附加信息 的本地化字符串。
        /// </summary>
        public static string ExtraInfoToDisplay {
            get {
                return ResourceManager.GetString("ExtraInfoToDisplay", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间点持续时间 的本地化字符串。
        /// </summary>
        public static string ExtraInfoTimePointDuration {
            get {
                return ResourceManager.GetString("ExtraInfoTimePointDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已过时间/持续时间 的本地化字符串。
        /// </summary>
        public static string ExtraInfoElapsedTimeOverDuration {
            get {
                return ResourceManager.GetString("ExtraInfoElapsedTimeOverDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 剩余时间/持续时间 的本地化字符串。
        /// </summary>
        public static string ExtraInfoRemainingOverDuration {
            get {
                return ResourceManager.GetString("ExtraInfoRemainingOverDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已过时间百分比 的本地化字符串。
        /// </summary>
        public static string ExtraInfoElapsedTimePercentage {
            get {
                return ResourceManager.GetString("ExtraInfoElapsedTimePercentage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 剩余时间 的本地化字符串。
        /// </summary>
        public static string ExtraInfoRemainingTime {
            get {
                return ResourceManager.GetString("ExtraInfoRemainingTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 倒计时 的本地化字符串。
        /// </summary>
        public static string ExtraInfoCountdown {
            get {
                return ResourceManager.GetString("ExtraInfoCountdown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示精确倒计时 的本地化字符串。
        /// </summary>
        public static string ShowExactCountdown {
            get {
                return ResourceManager.GetString("ShowExactCountdown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当剩余时间不足 的本地化字符串。
        /// </summary>
        public static string WhenRemainingLessThan {
            get {
                return ResourceManager.GetString("WhenRemainingLessThan", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间点结束倒计时 的本地化字符串。
        /// </summary>
        public static string TimePointEndCountdown {
            get {
                return ResourceManager.GetString("TimePointEndCountdown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在当前时间点将要结束时显示倒计时。 的本地化字符串。
        /// </summary>
        public static string TimePointEndCountdownDescription {
            get {
                return ResourceManager.GetString("TimePointEndCountdownDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间点结束倒计时时长 的本地化字符串。
        /// </summary>
        public static string TimePointEndCountdownDuration {
            get {
                return ResourceManager.GetString("TimePointEndCountdownDuration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 使用模糊倒计时 的本地化字符串。
        /// </summary>
        public static string UseFuzzyCountdown {
            get {
                return ResourceManager.GetString("UseFuzzyCountdown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 上课时仅显示当前课程 的本地化字符串。
        /// </summary>
        public static string ShowCurrentLessonOnly {
            get {
                return ResourceManager.GetString("ShowCurrentLessonOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在处于上课类型的时间点时，只显示当前时间点。 的本地化字符串。
        /// </summary>
        public static string ShowCurrentLessonOnlyDescription {
            get {
                return ResourceManager.GetString("ShowCurrentLessonOnlyDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不显示已结束的课程 的本地化字符串。
        /// </summary>
        public static string HideFinishedLessons {
            get {
                return ResourceManager.GetString("HideFinishedLessons", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 隐藏已结束的课程，只显示当前课程与暂未开始的课程。 的本地化字符串。
        /// </summary>
        public static string HideFinishedLessonsDescription {
            get {
                return ResourceManager.GetString("HideFinishedLessonsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 淡化上过的课程 的本地化字符串。
        /// </summary>
        public static string FadeCompletedLessons {
            get {
                return ResourceManager.GetString("FadeCompletedLessons", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已经上过的课程将被淡化显示。 的本地化字符串。
        /// </summary>
        public static string FadeCompletedLessonsDescription {
            get {
                return ResourceManager.GetString("FadeCompletedLessonsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 标记换课课程 的本地化字符串。
        /// </summary>
        public static string HighlightClassChanges {
            get {
                return ResourceManager.GetString("HighlightClassChanges", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 将临时层中的换课课程以高亮色标记，仅支持使用“换课”修改的课程。 的本地化字符串。
        /// </summary>
        public static string HighlightClassChangesDescription {
            get {
                return ResourceManager.GetString("HighlightClassChangesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课程表文本间距 的本地化字符串。
        /// </summary>
        public static string ScheduleTextSpacing {
            get {
                return ResourceManager.GetString("ScheduleTextSpacing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 使课程表显示更紧凑或宽松。 的本地化字符串。
        /// </summary>
        public static string ScheduleTextSpacingDescription {
            get {
                return ResourceManager.GetString("ScheduleTextSpacingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无课程时显示占位符 的本地化字符串。
        /// </summary>
        public static string ShowPlaceholderOnEmptyPlan {
            get {
                return ResourceManager.GetString("ShowPlaceholderOnEmptyPlan", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当当前没有加载课表或当日所有课程都已结束且不显示第二日课程时，显示指定的占位符。 的本地化字符串。
        /// </summary>
        public static string ShowPlaceholderOnEmptyPlanDescription {
            get {
                return ResourceManager.GetString("ShowPlaceholderOnEmptyPlanDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当日没有课程的占位符内容 的本地化字符串。
        /// </summary>
        public static string NoClassPlaceholderContent {
            get {
                return ResourceManager.GetString("NoClassPlaceholderContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当日课程结束的占位符内容 的本地化字符串。
        /// </summary>
        public static string AllEndedPlaceholderContent {
            get {
                return ResourceManager.GetString("AllEndedPlaceholderContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示明天课表 的本地化字符串。
        /// </summary>
        public static string ShowTomorrowSchedule {
            get {
                return ResourceManager.GetString("ShowTomorrowSchedule", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设置什么时候显示明天课表。 的本地化字符串。
        /// </summary>
        public static string ShowTomorrowScheduleDescription {
            get {
                return ResourceManager.GetString("ShowTomorrowScheduleDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 放学后显示 的本地化字符串。
        /// </summary>
        public static string ShowAfterSchool {
            get {
                return ResourceManager.GetString("ShowAfterSchool", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无展示课程时显示 的本地化字符串。
        /// </summary>
        public static string ShowWhenNoDisplayedLesson {
            get {
                return ResourceManager.GetString("ShowWhenNoDisplayedLesson", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 倒计时名称 的本地化字符串。
        /// </summary>
        public static string CountdownName {
            get {
                return ResourceManager.GetString("CountdownName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 会作为设定日期事件名称显示。 的本地化字符串。
        /// </summary>
        public static string CountdownNameDescription {
            get {
                return ResourceManager.GetString("CountdownNameDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 倒计时的开始和结束时间。 的本地化字符串。
        /// </summary>
        public static string TimeDescription {
            get {
                return ResourceManager.GetString("TimeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 固定时间 的本地化字符串。
        /// </summary>
        public static string FixedTime {
            get {
                return ResourceManager.GetString("FixedTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周期 的本地化字符串。
        /// </summary>
        public static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 本周 的本地化字符串。
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 倒计时开始的日期。 的本地化字符串。
        /// </summary>
        public static string StartDateDescription {
            get {
                return ResourceManager.GetString("StartDateDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 结束日期 的本地化字符串。
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 倒计时为 0 天时的日期。 的本地化字符串。
        /// </summary>
        public static string EndDateDescription {
            get {
                return ResourceManager.GetString("EndDateDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 高级计时 的本地化字符串。
        /// </summary>
        public static string AdvancedTiming {
            get {
                return ResourceManager.GetString("AdvancedTiming", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周期前时长 的本地化字符串。
        /// </summary>
        public static string CycleBeforeDurationLabel {
            get {
                return ResourceManager.GetString("CycleBeforeDurationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在本周期开始计时前的间隔时长 的本地化字符串。
        /// </summary>
        public static string CycleBeforeDurationHint {
            get {
                return ResourceManager.GetString("CycleBeforeDurationHint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周期计时时长 的本地化字符串。
        /// </summary>
        public static string CycleTimingDurationLabel {
            get {
                return ResourceManager.GetString("CycleTimingDurationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周期要显示倒计时的时长 的本地化字符串。
        /// </summary>
        public static string CycleTimingDurationHint {
            get {
                return ResourceManager.GetString("CycleTimingDurationHint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周期后时长 的本地化字符串。
        /// </summary>
        public static string CycleAfterDurationLabel {
            get {
                return ResourceManager.GetString("CycleAfterDurationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 从本周期计时结束，到下个周期开始的间隔时长 的本地化字符串。
        /// </summary>
        public static string CycleAfterDurationHint {
            get {
                return ResourceManager.GetString("CycleAfterDurationHint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周期持续时间 的本地化字符串。
        /// </summary>
        public static string CycleDurationLabel {
            get {
                return ResourceManager.GetString("CycleDurationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周期开始时间 的本地化字符串。
        /// </summary>
        public static string CycleStartTimeLabel {
            get {
                return ResourceManager.GetString("CycleStartTimeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 整个周期的开始时间，从周期前阶段开始计时。 的本地化字符串。
        /// </summary>
        public static string CycleStartTimeLabelDescription {
            get {
                return ResourceManager.GetString("CycleStartTimeLabelDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 限制周期循环次数 的本地化字符串。
        /// </summary>
        public static string LimitCycleLoops {
            get {
                return ResourceManager.GetString("LimitCycleLoops", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，将限制倒计时周期的最大循环次数。 的本地化字符串。
        /// </summary>
        public static string LimitCycleLoopsDescription {
            get {
                return ResourceManager.GetString("LimitCycleLoopsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间模式 的本地化字符串。
        /// </summary>
        public static string TimeMode {
            get {
                return ResourceManager.GetString("TimeMode", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认情况下将从当日课程安排获取倒计时时间，以当天的第一个上课或课间休息时间点的开始时间为开始时间，最后一个上课或课间休息... 的本地化字符串。
        /// </summary>
        public static string TimeModeDailyDescription {
            get {
                return ResourceManager.GetString("TimeModeDailyDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认情况下将从本周课程安排获取倒计时时间，以本周的第一个上课或课间休息时间点的开始时间为开始时间，最后一个上课或课间休息... 的本地化字符串。
        /// </summary>
        public static string TimeModeWeeklyDescription {
            get {
                return ResourceManager.GetString("TimeModeWeeklyDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string TimeModeDefault {
            get {
                return ResourceManager.GetString("TimeModeDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 强制自然时间 的本地化字符串。
        /// </summary>
        public static string ForceNaturalTime {
            get {
                return ResourceManager.GetString("ForceNaturalTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 强制课程时间 的本地化字符串。
        /// </summary>
        public static string ForceClassTime {
            get {
                return ResourceManager.GetString("ForceClassTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义每周的第一天 的本地化字符串。
        /// </summary>
        public static string CustomWeekStartDay {
            get {
                return ResourceManager.GetString("CustomWeekStartDay", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认情况下将使用在【基本】中设置的学期开始时间的星期作为每周的第一天，启用后将使用此处指定的星期。 的本地化字符串。
        /// </summary>
        public static string CustomWeekStartDayDescription {
            get {
                return ResourceManager.GetString("CustomWeekStartDayDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 星期日 的本地化字符串。
        /// </summary>
        public static string WeekdaySunday {
            get {
                return ResourceManager.GetString("WeekdaySunday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 星期一 的本地化字符串。
        /// </summary>
        public static string WeekdayMonday {
            get {
                return ResourceManager.GetString("WeekdayMonday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 星期二 的本地化字符串。
        /// </summary>
        public static string WeekdayTuesday {
            get {
                return ResourceManager.GetString("WeekdayTuesday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 星期三 的本地化字符串。
        /// </summary>
        public static string WeekdayWednesday {
            get {
                return ResourceManager.GetString("WeekdayWednesday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 星期四 的本地化字符串。
        /// </summary>
        public static string WeekdayThursday {
            get {
                return ResourceManager.GetString("WeekdayThursday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 星期五 的本地化字符串。
        /// </summary>
        public static string WeekdayFriday {
            get {
                return ResourceManager.GetString("WeekdayFriday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 星期六 的本地化字符串。
        /// </summary>
        public static string WeekdaySaturday {
            get {
                return ResourceManager.GetString("WeekdaySaturday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示内容 的本地化字符串。
        /// </summary>
        public static string DisplayContent {
            get {
                return ResourceManager.GetString("DisplayContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 要在组件上显示的信息 的本地化字符串。
        /// </summary>
        public static string DisplayContentDescription {
            get {
                return ResourceManager.GetString("DisplayContentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 进度条 的本地化字符串。
        /// </summary>
        public static string ProgressBar {
            get {
                return ResourceManager.GetString("ProgressBar", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 进度环 的本地化字符串。
        /// </summary>
        public static string ProgressRing {
            get {
                return ResourceManager.GetString("ProgressRing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 倒计时连接词 的本地化字符串。
        /// </summary>
        public static string CountdownConnector {
            get {
                return ResourceManager.GetString("CountdownConnector", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 倒计时 的本地化字符串。
        /// </summary>
        public static string Countdown {
            get {
                return ResourceManager.GetString("Countdown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 格式化变量说明 的本地化字符串。
        /// </summary>
        public static string FormatVariablesHelp {
            get {
                return ResourceManager.GetString("FormatVariablesHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %D - 总天数 的本地化字符串。
        /// </summary>
        public static string FormatTotalDays {
            get {
                return ResourceManager.GetString("FormatTotalDays", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %H - 总小时数 的本地化字符串。
        /// </summary>
        public static string FormatTotalHours {
            get {
                return ResourceManager.GetString("FormatTotalHours", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %M - 总分钟数 的本地化字符串。
        /// </summary>
        public static string FormatTotalMinutes {
            get {
                return ResourceManager.GetString("FormatTotalMinutes", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %S - 总秒数 的本地化字符串。
        /// </summary>
        public static string FormatTotalSeconds {
            get {
                return ResourceManager.GetString("FormatTotalSeconds", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %X - 总毫秒数 的本地化字符串。
        /// </summary>
        public static string FormatTotalMilliseconds {
            get {
                return ResourceManager.GetString("FormatTotalMilliseconds", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 以上数值向上取整。 的本地化字符串。
        /// </summary>
        public static string FormatRoundUpNote {
            get {
                return ResourceManager.GetString("FormatRoundUpNote", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %L - 剩余百分比 的本地化字符串。
        /// </summary>
        public static string FormatRemainingPercent {
            get {
                return ResourceManager.GetString("FormatRemainingPercent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %P - 已过百分比 的本地化字符串。
        /// </summary>
        public static string FormatElapsedPercent {
            get {
                return ResourceManager.GetString("FormatElapsedPercent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %p - 已过百分比(两位小数) 的本地化字符串。
        /// </summary>
        public static string FormatElapsedPercent2Decimals {
            get {
                return ResourceManager.GetString("FormatElapsedPercent2Decimals", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 以上数值四舍五入取整。 的本地化字符串。
        /// </summary>
        public static string FormatRoundingNote {
            get {
                return ResourceManager.GetString("FormatRoundingNote", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %d - 天 的本地化字符串。
        /// </summary>
        public static string FormatDays {
            get {
                return ResourceManager.GetString("FormatDays", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %h - 小时 的本地化字符串。
        /// </summary>
        public static string FormatHours {
            get {
                return ResourceManager.GetString("FormatHours", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %m - 分钟 的本地化字符串。
        /// </summary>
        public static string FormatMinutes {
            get {
                return ResourceManager.GetString("FormatMinutes", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %s - 秒 的本地化字符串。
        /// </summary>
        public static string FormatSeconds {
            get {
                return ResourceManager.GetString("FormatSeconds", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 %x - 毫秒 的本地化字符串。
        /// </summary>
        public static string FormatMilliseconds {
            get {
                return ResourceManager.GetString("FormatMilliseconds", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 以上数值取对应元素的值。 的本地化字符串。
        /// </summary>
        public static string FormatElementValueNote {
            get {
                return ResourceManager.GetString("FormatElementValueNote", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 强调色 的本地化字符串。
        /// </summary>
        public static string AccentColor {
            get {
                return ResourceManager.GetString("AccentColor", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 事件名称和倒计时的字体颜色。 的本地化字符串。
        /// </summary>
        public static string AccentColorDescription {
            get {
                return ResourceManager.GetString("AccentColorDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 进度条使用强调色 的本地化字符串。
        /// </summary>
        public static string ProgressBarUseAccent {
            get {
                return ResourceManager.GetString("ProgressBarUseAccent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，进度条将使用选定的主题色作为主题色，而不是使用应用的主题色。 的本地化字符串。
        /// </summary>
        public static string ProgressBarUseAccentDescription {
            get {
                return ResourceManager.GetString("ProgressBarUseAccentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 倒计时连接词使用强调颜色 的本地化字符串。
        /// </summary>
        public static string ConnectorUseAccent {
            get {
                return ResourceManager.GetString("ConnectorUseAccent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，倒计时连接词颜色与字体颜色一致，否则为默认颜色。 的本地化字符串。
        /// </summary>
        public static string ConnectorUseAccentDescription {
            get {
                return ResourceManager.GetString("ConnectorUseAccentDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 事件名称和倒计时的字体大小。 的本地化字符串。
        /// </summary>
        public static string CountdownFontSizeDescription {
            get {
                return ResourceManager.GetString("CountdownFontSizeDescription", resourceCulture);
            }
        }
    }
}
