//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Windows.ClassChanging {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Windows.ClassChanging.Localization.Windows.ClassChanging", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 换课 的本地化字符串。
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 替换 的本地化字符串。
        /// </summary>
        public static string Replace {
            get {
                return ResourceManager.GetString("Replace", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 交换 的本地化字符串。
        /// </summary>
        public static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 换课成… 的本地化字符串。
        /// </summary>
        public static string ChangeToLabel {
            get {
                return ResourceManager.GetString("ChangeToLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消换课操作。 的本地化字符串。
        /// </summary>
        public static string CancelToolTip {
            get {
                return ResourceManager.GetString("CancelToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 上一步 的本地化字符串。
        /// </summary>
        public static string PreviousStep {
            get {
                return ResourceManager.GetString("PreviousStep", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 返回上一步。 的本地化字符串。
        /// </summary>
        public static string PreviousStepToolTip {
            get {
                return ResourceManager.GetString("PreviousStepToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 高级换课... 的本地化字符串。
        /// </summary>
        public static string AdvancedClassChanging {
            get {
                return ResourceManager.GetString("AdvancedClassChanging", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开调课界面，支持跨天的换课选项和更复杂的调课方案。 的本地化字符串。
        /// </summary>
        public static string AdvancedClassChangingToolTip {
            get {
                return ResourceManager.GetString("AdvancedClassChangingToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 下一步 的本地化字符串。
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 进入下一步。 的本地化字符串。
        /// </summary>
        public static string NextStepToolTip {
            get {
                return ResourceManager.GetString("NextStepToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 永久换课 的本地化字符串。
        /// </summary>
        public static string PermanentChange {
            get {
                return ResourceManager.GetString("PermanentChange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 如果选择，将不会在换课时创建临时层课表，而会直接应用到原课表上。 的本地化字符串。
        /// </summary>
        public static string PermanentChangeToolTip {
            get {
                return ResourceManager.GetString("PermanentChangeToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确认换课 的本地化字符串。
        /// </summary>
        public static string ConfirmChange {
            get {
                return ResourceManager.GetString("ConfirmChange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确认并应用换课。 的本地化字符串。
        /// </summary>
        public static string ConfirmChangeToolTip {
            get {
                return ResourceManager.GetString("ConfirmChangeToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 要换课的课表 的本地化字符串。
        /// </summary>
        public static string TemporaryClassPlanToolTip {
            get {
                return ResourceManager.GetString("TemporaryClassPlanToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择要调换的课程。 的本地化字符串。
        /// </summary>
        public static string StepSelectSource {
            get {
                return ResourceManager.GetString("StepSelectSource", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择要与刚刚选择的课程调换的课程。点击复选框可以切换调换模式。 的本地化字符串。
        /// </summary>
        public static string StepSelectTarget {
            get {
                return ResourceManager.GetString("StepSelectTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择的课程无效。 的本地化字符串。
        /// </summary>
        public static string InvalidSelectedClass {
            get {
                return ResourceManager.GetString("InvalidSelectedClass", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 覆盖当前的临时层 的本地化字符串。
        /// </summary>
        public static string OverwriteTempLayerTitle {
            get {
                return ResourceManager.GetString("OverwriteTempLayerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前已经存在一个临时层课表，如果继续换课，那么该临时层将被覆盖。是否继续？ 的本地化字符串。
        /// </summary>
        public static string OverwriteTempLayerContent {
            get {
                return ResourceManager.GetString("OverwriteTempLayerContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
    }
}
