//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Controls.NotificationProviders {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Controls.NotificationProviders.Localization.Controls.NotificationProviders", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 此处的设置可以在档案设置中被附加设置覆盖。 的本地化字符串。
        /// </summary>
        public static string AttachedSettingsOverrideMessage {
            get {
                return ResourceManager.GetString("AttachedSettingsOverrideMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查看… 的本地化字符串。
        /// </summary>
        public static string ViewAttachedSettings {
            get {
                return ResourceManager.GetString("ViewAttachedSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在放学时发出提醒 的本地化字符串。
        /// </summary>
        public static string NotifyOnAfterSchool {
            get {
                return ResourceManager.GetString("NotifyOnAfterSchool", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在当日所有时间点结束后显示醒目提醒，提示已经放学。 的本地化字符串。
        /// </summary>
        public static string NotifyOnAfterSchoolDescription {
            get {
                return ResourceManager.GetString("NotifyOnAfterSchoolDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 提醒显示内容 的本地化字符串。
        /// </summary>
        public static string NotificationDisplayContent {
            get {
                return ResourceManager.GetString("NotificationDisplayContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在课前准备时发出提醒 的本地化字符串。
        /// </summary>
        public static string NotifyOnClassPreparing {
            get {
                return ResourceManager.GetString("NotifyOnClassPreparing", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在上课前一段时间发出醒目提醒，提示做好上课准备。 的本地化字符串。
        /// </summary>
        public static string NotifyOnClassPreparingDescription {
            get {
                return ResourceManager.GetString("NotifyOnClassPreparingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用语音 的本地化字符串。
        /// </summary>
        public static string EnableSpeech {
            get {
                return ResourceManager.GetString("EnableSpeech", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 室内课程课前提醒时间 的本地化字符串。
        /// </summary>
        public static string IndoorPreparationNotifyTime {
            get {
                return ResourceManager.GetString("IndoorPreparationNotifyTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在室内课程的上课前指定时间进行上课提醒。 的本地化字符串。
        /// </summary>
        public static string IndoorPreparationNotifyTimeDescription {
            get {
                return ResourceManager.GetString("IndoorPreparationNotifyTimeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 秒 的本地化字符串。
        /// </summary>
        public static string SecondsUnit {
            get {
                return ResourceManager.GetString("SecondsUnit", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 室外课程课前提醒时间 的本地化字符串。
        /// </summary>
        public static string OutdoorPreparationNotifyTime {
            get {
                return ResourceManager.GetString("OutdoorPreparationNotifyTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在室外课程的上课前指定时间进行上课提醒。 的本地化字符串。
        /// </summary>
        public static string OutdoorPreparationNotifyTimeDescription {
            get {
                return ResourceManager.GetString("OutdoorPreparationNotifyTimeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 室内课程准备上课提醒文字 的本地化字符串。
        /// </summary>
        public static string IndoorClassPreparingNotificationText {
            get {
                return ResourceManager.GetString("IndoorClassPreparingNotificationText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 （禁用） 的本地化字符串。
        /// </summary>
        public static string DisabledWatermark {
            get {
                return ResourceManager.GetString("DisabledWatermark", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 室内课程准备上课遮罩文字 的本地化字符串。
        /// </summary>
        public static string IndoorClassPreparingMaskText {
            get {
                return ResourceManager.GetString("IndoorClassPreparingMaskText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 户外课程准备上课提醒文字 的本地化字符串。
        /// </summary>
        public static string OutdoorClassPreparingNotificationText {
            get {
                return ResourceManager.GetString("OutdoorClassPreparingNotificationText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 户外课程准备上课遮罩文字 的本地化字符串。
        /// </summary>
        public static string OutdoorClassPreparingMaskText {
            get {
                return ResourceManager.GetString("OutdoorClassPreparingMaskText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在上课时发出提醒 的本地化字符串。
        /// </summary>
        public static string NotifyOnClassOn {
            get {
                return ResourceManager.GetString("NotifyOnClassOn", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在上课时发出醒目提醒，提示已经上课。 的本地化字符串。
        /// </summary>
        public static string NotifyOnClassOnDescription {
            get {
                return ResourceManager.GetString("NotifyOnClassOnDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 上课遮罩文字 的本地化字符串。
        /// </summary>
        public static string ClassOnMaskText {
            get {
                return ResourceManager.GetString("ClassOnMaskText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在下课时发出提醒 的本地化字符串。
        /// </summary>
        public static string NotifyOnClassOff {
            get {
                return ResourceManager.GetString("NotifyOnClassOff", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在下课时发出醒目提醒，提示已经下课。 的本地化字符串。
        /// </summary>
        public static string NotifyOnClassOffDescription {
            get {
                return ResourceManager.GetString("NotifyOnClassOffDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 下课提醒文字 的本地化字符串。
        /// </summary>
        public static string ClassOffNotificationText {
            get {
                return ResourceManager.GetString("ClassOffNotificationText", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示科任老师名字 的本地化字符串。
        /// </summary>
        public static string ShowTeacherName {
            get {
                return ResourceManager.GetString("ShowTeacherName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在显示课程相关的提醒时同时展示并播报对应科任老师的名字 的本地化字符串。
        /// </summary>
        public static string ShowTeacherNameDescription {
            get {
                return ResourceManager.GetString("ShowTeacherNameDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 距上课还剩 的本地化字符串。
        /// </summary>
        public static string UntilClassStarts {
            get {
                return ResourceManager.GetString("UntilClassStarts", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 下节课是： 的本地化字符串。
        /// </summary>
        public static string NextLessonIs {
            get {
                return ResourceManager.GetString("NextLessonIs", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 本节 的本地化字符串。
        /// </summary>
        public static string CurrentLessonPrefix {
            get {
                return ResourceManager.GetString("CurrentLessonPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 长 的本地化字符串。
        /// </summary>
        public static string DurationSuffix {
            get {
                return ResourceManager.GetString("DurationSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} 分钟 的本地化字符串。
        /// </summary>
        public static string DurationMinutesFmt {
            get {
                return ResourceManager.GetString("DurationMinutesFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} 小时 的本地化字符串。
        /// </summary>
        public static string DurationHoursFmt {
            get {
                return ResourceManager.GetString("DurationHoursFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} 分 的本地化字符串。
        /// </summary>
        public static string DurationShortMinutesFmt {
            get {
                return ResourceManager.GetString("DurationShortMinutesFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0} 秒 的本地化字符串。
        /// </summary>
        public static string DurationSecondsFmt {
            get {
                return ResourceManager.GetString("DurationSecondsFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用天气预报 的本地化字符串。
        /// </summary>
        public static string EnableWeatherForecast {
            get {
                return ResourceManager.GetString("EnableWeatherForecast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 若启用天气预报，会在指定时间段显示今天和明后两天的天气概况。 的本地化字符串。
        /// </summary>
        public static string EnableWeatherForecastDescription {
            get {
                return ResourceManager.GetString("EnableWeatherForecastDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用极端天气预警 的本地化字符串。
        /// </summary>
        public static string EnableWeatherAlert {
            get {
                return ResourceManager.GetString("EnableWeatherAlert", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当发布气象预警时，会在指定的时间段进行通知。 的本地化字符串。
        /// </summary>
        public static string EnableWeatherAlertDescription {
            get {
                return ResourceManager.GetString("EnableWeatherAlertDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认天气预报显示模式 的本地化字符串。
        /// </summary>
        public static string DefaultForecastShowMode {
            get {
                return ResourceManager.GetString("DefaultForecastShowMode", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天气预报的默认显示模式，可以在各个时间点覆盖该设置。 的本地化字符串。
        /// </summary>
        public static string DefaultForecastShowModeDescription {
            get {
                return ResourceManager.GetString("DefaultForecastShowModeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认禁用 的本地化字符串。
        /// </summary>
        public static string DefaultDisabled {
            get {
                return ResourceManager.GetString("DefaultDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认启用 的本地化字符串。
        /// </summary>
        public static string DefaultEnabled {
            get {
                return ResourceManager.GetString("DefaultEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认极端天气提醒显示模式 的本地化字符串。
        /// </summary>
        public static string DefaultAlertShowMode {
            get {
                return ResourceManager.GetString("DefaultAlertShowMode", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 极端天气提醒的默认显示模式，可以在各个时间点覆盖该设置。 的本地化字符串。
        /// </summary>
        public static string DefaultAlertShowModeDescription {
            get {
                return ResourceManager.GetString("DefaultAlertShowModeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 极端天气预警滚动速度（字/秒） 的本地化字符串。
        /// </summary>
        public static string WeatherAlertScrollSpeed {
            get {
                return ResourceManager.GetString("WeatherAlertScrollSpeed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示天气预警详细信息时文本滚动一轮的速度。无论此选项设置为何值，滚动一轮的时间始终限制在10~90秒内。 的本地化字符串。
        /// </summary>
        public static string WeatherAlertScrollSpeedDescription {
            get {
                return ResourceManager.GetString("WeatherAlertScrollSpeedDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天气预报 的本地化字符串。
        /// </summary>
        public static string WeatherForecastTitle {
            get {
                return ResourceManager.GetString("WeatherForecastTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 今天 的本地化字符串。
        /// </summary>
        public static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 明天 的本地化字符串。
        /// </summary>
        public static string TomorrowLabel {
            get {
                return ResourceManager.GetString("TomorrowLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 后天 的本地化字符串。
        /// </summary>
        public static string DayAfterTomorrowLabel {
            get {
                return ResourceManager.GetString("DayAfterTomorrowLabel", resourceCulture);
            }
        }
    }
}
