//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.SettingsPage.Window {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.SettingsPage.Window.Localization.SettingsPage.Window", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 窗口停靠位置 的本地化字符串。
        /// </summary>
        public static string WindowDockingLocation {
            get {
                return ResourceManager.GetString("WindowDockingLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 总之这是开始按钮，或类似开始的按钮 的本地化字符串。
        /// </summary>
        public static string StartButtonToolTip {
            get {
                return ResourceManager.GetString("StartButtonToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 向右偏移 的本地化字符串。
        /// </summary>
        public static string OffsetRightLabel {
            get {
                return ResourceManager.GetString("OffsetRightLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 向下偏移 的本地化字符串。
        /// </summary>
        public static string OffsetDownLabel {
            get {
                return ResourceManager.GetString("OffsetDownLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示器 的本地化字符串。
        /// </summary>
        public static string MonitorLabel {
            get {
                return ResourceManager.GetString("MonitorLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 刷新显示器列表 的本地化字符串。
        /// </summary>
        public static string RefreshMonitors {
            get {
                return ResourceManager.GetString("RefreshMonitors", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 应用会以左图的位置显示在指定的显示器上。如果指定的显示器不存在，那么应用会显示在主显示器上。 的本地化字符串。
        /// </summary>
        public static string MonitorHint {
            get {
                return ResourceManager.GetString("MonitorHint", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 初始化 RawInput 失败，将使用兼容模式判断光标位置。详细请查看日志。 的本地化字符串。
        /// </summary>
        public static string RawInputInitFailedWarning {
            get {
                return ResourceManager.GetString("RawInputInitFailedWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 使用原始输入判断鼠标位置时，如果前台窗口的进程以管理员身份运行，可能会出现无法判定鼠标位置的情况。以管理员身份运行 Cl... 的本地化字符串。
        /// </summary>
        public static string RawInputAdminWarning {
            get {
                return ResourceManager.GetString("RawInputAdminWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 窗口层级 的本地化字符串。
        /// </summary>
        public static string WindowLayerHeader {
            get {
                return ResourceManager.GetString("WindowLayerHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 窗口在屏幕上的层级。置底则会显示在所有窗口的后方，置顶则将显示在所有窗口的前方。 的本地化字符串。
        /// </summary>
        public static string WindowLayerDescription {
            get {
                return ResourceManager.GetString("WindowLayerDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 置底 的本地化字符串。
        /// </summary>
        public static string LayerBottom {
            get {
                return ResourceManager.GetString("LayerBottom", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 置顶 的本地化字符串。
        /// </summary>
        public static string LayerTop {
            get {
                return ResourceManager.GetString("LayerTop", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 窗口层级设置频率 的本地化字符串。
        /// </summary>
        public static string LayerSetFrequencyContent {
            get {
                return ResourceManager.GetString("LayerSetFrequencyContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 在什么时候重新设置窗口置顶/置底状态。请注意，较高的设置频率可能会产生较高的性能占用并导致主界面... 的本地化字符串。
        /// </summary>
        public static string LayerSetFrequencyDescription {
            get {
                return ResourceManager.GetString("LayerSetFrequencyDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 窗口层级变化时（默认） 的本地化字符串。
        /// </summary>
        public static string LayerModeWindowChange {
            get {
                return ResourceManager.GetString("LayerModeWindowChange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 前台窗口变化时 的本地化字符串。
        /// </summary>
        public static string LayerModeForegroundChange {
            get {
                return ResourceManager.GetString("LayerModeForegroundChange", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 每 50ms 的本地化字符串。
        /// </summary>
        public static string LayerMode50ms {
            get {
                return ResourceManager.GetString("LayerMode50ms", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 每 1ms 的本地化字符串。
        /// </summary>
        public static string LayerMode1ms {
            get {
                return ResourceManager.GetString("LayerMode1ms", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义背景效果 的本地化字符串。
        /// </summary>
        public static string BackgroundEffectHeader {
            get {
                return ResourceManager.GetString("BackgroundEffectHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自定义主界面的背景效果，仅在较新版本的 Windows 上可用，可能会产生额外性能开销。 的本地化字符串。
        /// </summary>
        public static string BackgroundEffectDescription {
            get {
                return ResourceManager.GetString("BackgroundEffectDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 画刷类型 的本地化字符串。
        /// </summary>
        public static string BrushTypeContent {
            get {
                return ResourceManager.GetString("BrushTypeContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择主界面背景使用的材质。 的本地化字符串。
        /// </summary>
        public static string BrushTypeDescription {
            get {
                return ResourceManager.GetString("BrushTypeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 亚克力 的本地化字符串。
        /// </summary>
        public static string MaterialAcrylic {
            get {
                return ResourceManager.GetString("MaterialAcrylic", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 类液态玻璃 的本地化字符串。
        /// </summary>
        public static string MaterialLiquidGlass {
            get {
                return ResourceManager.GetString("MaterialLiquidGlass", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 云母 的本地化字符串。
        /// </summary>
        public static string MaterialMica {
            get {
                return ResourceManager.GetString("MaterialMica", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 指针移入淡化 的本地化字符串。
        /// </summary>
        public static string MouseFadingHeader {
            get {
                return ResourceManager.GetString("MouseFadingHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，在鼠标移入或触屏点击主界面区域时，将淡化主界面。 的本地化字符串。
        /// </summary>
        public static string MouseFadingDescription {
            get {
                return ResourceManager.GetString("MouseFadingDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 使用原始输入 的本地化字符串。
        /// </summary>
        public static string UseRawInputContent {
            get {
                return ResourceManager.GetString("UseRawInputContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，ClassFabric 将使用 RawInput 接收鼠标/触屏事件，而不是轮询获取光标位置。这允许应用辨别鼠标... 的本地化字符串。
        /// </summary>
        public static string UseRawInputDescription {
            get {
                return ResourceManager.GetString("UseRawInputDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 触屏点击后自动恢复时间 的本地化字符串。
        /// </summary>
        public static string TouchRecoveryContent {
            get {
                return ResourceManager.GetString("TouchRecoveryContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，触屏点击主界面区域后将在一定时间后自动恢复主界面显示。设置为0为禁用。 的本地化字符串。
        /// </summary>
        public static string TouchRecoveryDescription {
            get {
                return ResourceManager.GetString("TouchRecoveryDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 反转指针移入淡化 的本地化字符串。
        /// </summary>
        public static string MouseFadingReversedContent {
            get {
                return ResourceManager.GetString("MouseFadingReversedContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，将默认淡化主界面，使主界面仅在鼠标移入时显示。此开关不影响隐藏主界面。 的本地化字符串。
        /// </summary>
        public static string MouseFadingReversedDescription {
            get {
                return ResourceManager.GetString("MouseFadingReversedDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 使用原始屏幕尺寸 的本地化字符串。
        /// </summary>
        public static string RawScreenSizeHeader {
            get {
                return ResourceManager.GetString("RawScreenSizeHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 若启用，主界面调整位置时将忽略系统工作区设置（通常包括任务栏和部分顶栏应用）。 的本地化字符串。
        /// </summary>
        public static string RawScreenSizeDescription {
            get {
                return ResourceManager.GetString("RawScreenSizeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 录制模式 的本地化字符串。
        /// </summary>
        public static string RecordingModeHeader {
            get {
                return ResourceManager.GetString("RecordingModeHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，ClassFabric 将调整窗口属性以便被录屏软件录制。这会导致主界面窗口显示在任务栏中且主界面窗口只会在一个... 的本地化字符串。
        /// </summary>
        public static string RecordingModeDescription {
            get {
                return ResourceManager.GetString("RecordingModeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 阻止截图 的本地化字符串。
        /// </summary>
        public static string BlockCaptureHeader {
            get {
                return ResourceManager.GetString("BlockCaptureHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 开启后，其他应用无法截取 ClassFabric 主界面窗口内容，录制时也不会录制到主页面。 的本地化字符串。
        /// </summary>
        public static string BlockCaptureDescription {
            get {
                return ResourceManager.GetString("BlockCaptureDescription", resourceCulture);
            }
        }
    }
}
