using System.Runtime.CompilerServices;
using Avalonia.Metadata;

[assembly: InternalsVisibleTo("ClassFabric")]
[assembly: InternalsVisibleTo("ClassFabric.Desktop")]
[assembly: InternalsVisibleTo("ClassFabric.Android")]
[assembly: InternalsVisibleTo("ClassFabric.iOS")]
[assembly: InternalsVisibleTo("ClassFabric.Hmos")]
[assembly: InternalsVisibleTo("ClassFabric.Platforms.Windows")]

[assembly: XmlnsPrefix("http://classfabric.tech/schemas/xaml/core", "ci")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Converters")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Controls")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Controls.CommonDialog")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Controls.LessonsControls")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Controls.IconControl")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Controls.NavHyperlink")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Controls.Ruleset")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Controls.Tutorial")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Commands")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Abstractions.Controls")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Abstractions.Behaviors")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Controls.StickerControl")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Abstractions.Views")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Behaviors")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.Assists")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.IconSources")]
[assembly: XmlnsDefinition("http://classfabric.tech/schemas/xaml/core", "ClassIsland.Core.MarkupExtensions")]
