//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Main {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Main.Localization.Main", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 教学... 的本地化字符串。
        /// </summary>
        public static string TutorialsMenu {
            get {
                return ResourceManager.GetString("TutorialsMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 帮助文档... 的本地化字符串。
        /// </summary>
        public static string HelpDocumentsMenu {
            get {
                return ResourceManager.GetString("HelpDocumentsMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示主界面 的本地化字符串。
        /// </summary>
        public static string ShowMainWindowMenu {
            get {
                return ResourceManager.GetString("ShowMainWindowMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清除全部提醒 的本地化字符串。
        /// </summary>
        public static string ClearAllNotificationsMenu {
            get {
                return ResourceManager.GetString("ClearAllNotificationsMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更多选项... 的本地化字符串。
        /// </summary>
        public static string MoreOptionsMenu {
            get {
                return ResourceManager.GetString("MoreOptionsMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑档案... 的本地化字符串。
        /// </summary>
        public static string EditProfileMenu {
            get {
                return ResourceManager.GetString("EditProfileMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 加载临时课表... 的本地化字符串。
        /// </summary>
        public static string LoadTempScheduleMenu {
            get {
                return ResourceManager.GetString("LoadTempScheduleMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 换课... 的本地化字符串。
        /// </summary>
        public static string ClassSwapMenu {
            get {
                return ResourceManager.GetString("ClassSwapMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑主界面... 的本地化字符串。
        /// </summary>
        public static string EnterEditModeMenu {
            get {
                return ResourceManager.GetString("EnterEditModeMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 应用设置... 的本地化字符串。
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑主界面 | ClassFabric 的本地化字符串。
        /// </summary>
        public static string EditModeWindowTitle {
            get {
                return ResourceManager.GetString("EditModeWindowTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开 MainView 的本地化字符串。
        /// </summary>
        public static string DebugOpenMainViewMenu {
            get {
                return ResourceManager.GetString("DebugOpenMainViewMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 截图工具 的本地化字符串。
        /// </summary>
        public static string DebugScreenshotToolMenu {
            get {
                return ResourceManager.GetString("DebugScreenshotToolMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 教程编辑器 的本地化字符串。
        /// </summary>
        public static string DebugTutorialEditorMenu {
            get {
                return ResourceManager.GetString("DebugTutorialEditorMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用课表 的本地化字符串。
        /// </summary>
        public static string DebugEnableClassPlanMenu {
            get {
                return ResourceManager.GetString("DebugEnableClassPlanMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示崩溃窗口 的本地化字符串。
        /// </summary>
        public static string DebugShowCrashWindowMenu {
            get {
                return ResourceManager.GetString("DebugShowCrashWindowMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设置... 的本地化字符串。
        /// </summary>
        public static string LineSettingsToolTip {
            get {
                return ResourceManager.GetString("LineSettingsToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此行是主要行 的本地化字符串。
        /// </summary>
        public static string IsMainLineToolTip {
            get {
                return ResourceManager.GetString("IsMainLineToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此行可以显示提醒 的本地化字符串。
        /// </summary>
        public static string LineNotificationToolTip {
            get {
                return ResourceManager.GetString("LineNotificationToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string DeleteToolTip {
            get {
                return ResourceManager.GetString("DeleteToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新主界面行 的本地化字符串。
        /// </summary>
        public static string NewMainWindowLine {
            get {
                return ResourceManager.GetString("NewMainWindowLine", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        public static string CloseToolTip {
            get {
                return ResourceManager.GetString("CloseToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重置视图 的本地化字符串。
        /// </summary>
        public static string ResetViewButton {
            get {
                return ResourceManager.GetString("ResetViewButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 外观 的本地化字符串。
        /// </summary>
        public static string AppearanceButton {
            get {
                return ResourceManager.GetString("AppearanceButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 添加组件 的本地化字符串。
        /// </summary>
        public static string AddComponentButton {
            get {
                return ResourceManager.GetString("AddComponentButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string DoneButton {
            get {
                return ResourceManager.GetString("DoneButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在加载界面主题（1） 的本地化字符串。
        /// </summary>
        public static string LoadingTheme1 {
            get {
                return ResourceManager.GetString("LoadingTheme1", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在加载界面主题（2） 的本地化字符串。
        /// </summary>
        public static string LoadingTheme2 {
            get {
                return ResourceManager.GetString("LoadingTheme2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在初始化主界面（步骤 1/2） 的本地化字符串。
        /// </summary>
        public static string InitializingMainWindowStep1 {
            get {
                return ResourceManager.GetString("InitializingMainWindowStep1", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在初始化托盘菜单 的本地化字符串。
        /// </summary>
        public static string InitializingTrayMenu {
            get {
                return ResourceManager.GetString("InitializingTrayMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在初始化输入 的本地化字符串。
        /// </summary>
        public static string InitializingInput {
            get {
                return ResourceManager.GetString("InitializingInput", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在初始化主界面（步骤 2/2） 的本地化字符串。
        /// </summary>
        public static string InitializingMainWindowStep2 {
            get {
                return ResourceManager.GetString("InitializingMainWindowStep2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已禁用不支持的设置 的本地化字符串。
        /// </summary>
        public static string UnsupportedSettingDisabledToastTitle {
            get {
                return ResourceManager.GetString("UnsupportedSettingDisabledToastTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 【启用鼠标点击】设置项目不再受到支持并已自动禁用，感谢您的支持与理解。 的本地化字符串。
        /// </summary>
        public static string UnsupportedSettingDisabledToastBody {
            get {
                return ResourceManager.GetString("UnsupportedSettingDisabledToastBody", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用临时课表 的本地化字符串。
        /// </summary>
        public static string DebugEnableTempClassPlanHeader {
            get {
                return ResourceManager.GetString("DebugEnableTempClassPlanHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 输入课表 GUID，当前档案为 {0} 的本地化字符串。
        /// </summary>
        public static string DebugEnableTempClassPlanPrompt {
            get {
                return ResourceManager.GetString("DebugEnableTempClassPlanPrompt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已将第一行设置为主要行。 的本地化字符串。
        /// </summary>
        public static string FirstLineSetAsMainToast {
            get {
                return ResourceManager.GetString("FirstLineSetAsMainToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您已经禁用了所有主界面行的提醒显示功能。... 的本地化字符串。
        /// </summary>
        public static string AllNotificationDisabledWarning {
            get {
                return ResourceManager.GetString("AllNotificationDisabledWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 至少需要保留 1 个主界面行。 的本地化字符串。
        /// </summary>
        public static string AtLeastOneLineWarning {
            get {
                return ResourceManager.GetString("AtLeastOneLineWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此问题可能由以下插件引起... 的本地化字符串。
        /// </summary>
        public static string CrashPluginsWarning {
            get {
                return ResourceManager.GetString("CrashPluginsWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 以上异常插件已自动禁用... 的本地化字符串。
        /// </summary>
        public static string CrashPluginsDisabled {
            get {
                return ResourceManager.GetString("CrashPluginsDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在向开发者提交问题时请保留以下信息： 的本地化字符串。
        /// </summary>
        public static string CrashTraceInfoHeader {
            get {
                return ResourceManager.GetString("CrashTraceInfoHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 崩溃报告 的本地化字符串。
        /// </summary>
        public static string CrashReportToastTitle {
            get {
                return ResourceManager.GetString("CrashReportToastTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 发生了一个无法处理的错误：{0} 的本地化字符串。
        /// </summary>
        public static string CrashReportToastBody {
            get {
                return ResourceManager.GetString("CrashReportToastBody", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 欢迎使用 2.2-Mikhail Developer Preview 的本地化字符串。
        /// </summary>
        public static string DevPreviewHeader {
            get {
                return ResourceManager.GetString("DevPreviewHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此版本仅供开发人员进行早期预览... 的本地化字符串。
        /// </summary>
        public static string DevPreviewContent {
            get {
                return ResourceManager.GetString("DevPreviewContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 我就要运行 的本地化字符串。
        /// </summary>
        public static string ForceRunButton {
            get {
                return ResourceManager.GetString("ForceRunButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 检测到应用正在临时目录下运行 的本地化字符串。
        /// </summary>
        public static string TempDirHeader {
            get {
                return ResourceManager.GetString("TempDirHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 正在临时目录下运行... 的本地化字符串。
        /// </summary>
        public static string TempDirContent {
            get {
                return ResourceManager.GetString("TempDirContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 检测到正在桌面上运行 的本地化字符串。
        /// </summary>
        public static string DesktopRunHeader {
            get {
                return ResourceManager.GetString("DesktopRunHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 正在桌面上运行... 的本地化字符串。
        /// </summary>
        public static string DesktopRunContent {
            get {
                return ResourceManager.GetString("DesktopRunContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 目录权限错误 的本地化字符串。
        /// </summary>
        public static string DirectoryPermissionErrorHeader {
            get {
                return ResourceManager.GetString("DirectoryPermissionErrorHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 无法写入当前目录：{0} 的本地化字符串。
        /// </summary>
        public static string DirectoryPermissionErrorBody {
            get {
                return ResourceManager.GetString("DirectoryPermissionErrorBody", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 请将本软件解压到一个合适的位置后再运行。 的本地化字符串。
        /// </summary>
        public static string DirectoryPermissionErrorFooter {
            get {
                return ResourceManager.GetString("DirectoryPermissionErrorFooter", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 进入恢复模式 的本地化字符串。
        /// </summary>
        public static string RecoveryModeTitle {
            get {
                return ResourceManager.GetString("RecoveryModeTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 多次启动失败... 的本地化字符串。
        /// </summary>
        public static string RecoveryModeContent {
            get {
                return ResourceManager.GetString("RecoveryModeContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 进入恢复模式 的本地化字符串。
        /// </summary>
        public static string EnterRecoveryModeButton {
            get {
                return ResourceManager.GetString("EnterRecoveryModeButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前界面缩放是否正常？ 的本地化字符串。
        /// </summary>
        public static string ScaleQuestionHeader {
            get {
                return ResourceManager.GetString("ScaleQuestionHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 如果您发现当前界面缩放相对系统缩放过小... 的本地化字符串。
        /// </summary>
        public static string ScaleQuestionContent {
            get {
                return ResourceManager.GetString("ScaleQuestionContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        public static string ScaleNormalButton {
            get {
                return ResourceManager.GetString("ScaleNormalButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不正常 的本地化字符串。
        /// </summary>
        public static string ScaleAbnormalButton {
            get {
                return ResourceManager.GetString("ScaleAbnormalButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在启动挂起检查服务 的本地化字符串。
        /// </summary>
        public static string StartingHangCheckService {
            get {
                return ResourceManager.GetString("StartingHangCheckService", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在创建任务栏图标 的本地化字符串。
        /// </summary>
        public static string CreatingTaskbarIcon {
            get {
                return ResourceManager.GetString("CreatingTaskbarIcon", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在进行更新服务启动操作 的本地化字符串。
        /// </summary>
        public static string StartingUpdateService {
            get {
                return ResourceManager.GetString("StartingUpdateService", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在加载档案 的本地化字符串。
        /// </summary>
        public static string LoadingProfile {
            get {
                return ResourceManager.GetString("LoadingProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在启动主界面所需的服务 的本地化字符串。
        /// </summary>
        public static string StartingMainWindowServices {
            get {
                return ResourceManager.GetString("StartingMainWindowServices", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在进行启动后操作 的本地化字符串。
        /// </summary>
        public static string PostStartupOperations {
            get {
                return ResourceManager.GetString("PostStartupOperations", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 测试导航 的本地化字符串。
        /// </summary>
        public static string DebugNavigationTitle {
            get {
                return ResourceManager.GetString("DebugNavigationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新完成。 的本地化字符串。
        /// </summary>
        public static string UpdateCompletedToastTitle {
            get {
                return ResourceManager.GetString("UpdateCompletedToastTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 应用已更新到版本{0}。 的本地化字符串。
        /// </summary>
        public static string UpdateCompletedToastBody {
            get {
                return ResourceManager.GetString("UpdateCompletedToastBody", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查看更新日志 的本地化字符串。
        /// </summary>
        public static string ViewChangelogButton {
            get {
                return ResourceManager.GetString("ViewChangelogButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 配置文件损坏 的本地化字符串。
        /// </summary>
        public static string ConfigCorruptedToastTitle {
            get {
                return ResourceManager.GetString("ConfigCorruptedToastTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 部分配置文件已损坏且无法加载... 的本地化字符串。
        /// </summary>
        public static string ConfigCorruptedToastBody {
            get {
                return ResourceManager.GetString("ConfigCorruptedToastBody", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已自动禁用异常插件 的本地化字符串。
        /// </summary>
        public static string CorruptPluginsDisabledToastTitle {
            get {
                return ResourceManager.GetString("CorruptPluginsDisabledToastTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 已自动禁用导致上次崩溃的插件... 的本地化字符串。
        /// </summary>
        public static string CorruptPluginsDisabledToastBody {
            get {
                return ResourceManager.GetString("CorruptPluginsDisabledToastBody", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开插件设置 的本地化字符串。
        /// </summary>
        public static string OpenPluginSettingsButton {
            get {
                return ResourceManager.GetString("OpenPluginSettingsButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 管理异常插件行为 的本地化字符串。
        /// </summary>
        public static string ManagePluginBehaviorButton {
            get {
                return ResourceManager.GetString("ManagePluginBehaviorButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 已在运行 的本地化字符串。
        /// </summary>
        public static string AppAlreadyRunningTitle {
            get {
                return ResourceManager.GetString("AppAlreadyRunningTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassFabric 已经启动，请通过任务栏托盘图标进行设置等操作。 的本地化字符串。
        /// </summary>
        public static string AppAlreadyRunningContent1 {
            get {
                return ResourceManager.GetString("AppAlreadyRunningContent1", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 如果您无法看到主界面... 的本地化字符串。
        /// </summary>
        public static string AppAlreadyRunningContent2 {
            get {
                return ResourceManager.GetString("AppAlreadyRunningContent2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重启当前实例 的本地化字符串。
        /// </summary>
        public static string RestartCurrentInstanceCommand {
            get {
                return ResourceManager.GetString("RestartCurrentInstanceCommand", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 结束正在运行的 ClassFabric 实例，然后再次启动本实例。 的本地化字符串。
        /// </summary>
        public static string RestartCurrentInstanceDescription {
            get {
                return ResourceManager.GetString("RestartCurrentInstanceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重启失败 的本地化字符串。
        /// </summary>
        public static string RestartFailedTitle {
            get {
                return ResourceManager.GetString("RestartFailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法重新启动应用... 的本地化字符串。
        /// </summary>
        public static string RestartFailedBody {
            get {
                return ResourceManager.GetString("RestartFailedBody", resourceCulture);
            }
        }
    }
}
