//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.SettingsPage.Weather {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.SettingsPage.Weather.Localization.SettingsPage.Weather", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 搜索城市 的本地化字符串。
        /// </summary>
        public static string SearchCityTitle {
            get {
                return ResourceManager.GetString("SearchCityTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 搜索城市或省份… 的本地化字符串。
        /// </summary>
        public static string SearchCityWatermark {
            get {
                return ResourceManager.GetString("SearchCityWatermark", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 找不到符合条件的城市。请更换搜索关键字，然后再试一次。 的本地化字符串。
        /// </summary>
        public static string CitySearchNoResults {
            get {
                return ResourceManager.GetString("CitySearchNoResults", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天气预览 的本地化字符串。
        /// </summary>
        public static string WeatherPreview {
            get {
                return ResourceManager.GetString("WeatherPreview", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 湿度 的本地化字符串。
        /// </summary>
        public static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 空气质量 的本地化字符串。
        /// </summary>
        public static string AirQuality {
            get {
                return ResourceManager.GetString("AirQuality", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 风力 的本地化字符串。
        /// </summary>
        public static string Wind {
            get {
                return ResourceManager.GetString("Wind", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新于 的本地化字符串。
        /// </summary>
        public static string UpdatedAtPrefix {
            get {
                return ResourceManager.GetString("UpdatedAtPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 位置设置 的本地化字符串。
        /// </summary>
        public static string LocationSettings {
            get {
                return ResourceManager.GetString("LocationSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天气位置 的本地化字符串。
        /// </summary>
        public static string WeatherLocation {
            get {
                return ResourceManager.GetString("WeatherLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设置 ClassFabric 用于查询天气的位置信息及获取方式。 的本地化字符串。
        /// </summary>
        public static string WeatherLocationDescription {
            get {
                return ResourceManager.GetString("WeatherLocationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择城市 的本地化字符串。
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 坐标定位 的本地化字符串。
        /// </summary>
        public static string CoordinateLocating {
            get {
                return ResourceManager.GetString("CoordinateLocating", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 城市选择 的本地化字符串。
        /// </summary>
        public static string CitySelection {
            get {
                return ResourceManager.GetString("CitySelection", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择当前所在的城市，以用于天气查询。 的本地化字符串。
        /// </summary>
        public static string CitySelectionDescription {
            get {
                return ResourceManager.GetString("CitySelectionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑城市 的本地化字符串。
        /// </summary>
        public static string EditCity {
            get {
                return ResourceManager.GetString("EditCity", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 位置坐标 的本地化字符串。
        /// </summary>
        public static string LocationCoordinates {
            get {
                return ResourceManager.GetString("LocationCoordinates", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 输入用于获取天气信息的经纬坐标。 的本地化字符串。
        /// </summary>
        public static string LocationCoordinatesDescription {
            get {
                return ResourceManager.GetString("LocationCoordinatesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 经度 的本地化字符串。
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 纬度 的本地化字符串。
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 显示坐标 的本地化字符串。
        /// </summary>
        public static string ShowCoordinates {
            get {
                return ResourceManager.GetString("ShowCoordinates", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自动定位 的本地化字符串。
        /// </summary>
        public static string AutoLocate {
            get {
                return ResourceManager.GetString("AutoLocate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自动获取位置 的本地化字符串。
        /// </summary>
        public static string AutoGetLocation {
            get {
                return ResourceManager.GetString("AutoGetLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，将在应用每次启动时自动更新位置信息。 的本地化字符串。
        /// </summary>
        public static string AutoGetLocationDescription {
            get {
                return ResourceManager.GetString("AutoGetLocationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天气数据源 的本地化字符串。
        /// </summary>
        public static string WeatherDataSource {
            get {
                return ResourceManager.GetString("WeatherDataSource", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择天气数据提供方。默认使用小米天气；其他来源失败时可自动回退。 的本地化字符串。
        /// </summary>
        public static string WeatherDataSourceDescription {
            get {
                return ResourceManager.GetString("WeatherDataSourceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 小米天气（默认） 的本地化字符串。
        /// </summary>
        public static string XiaomiWeatherDefault {
            get {
                return ResourceManager.GetString("XiaomiWeatherDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 使用 OpenWeather 时必填，由用户自行申请并保存在本机设置中。 的本地化字符串。
        /// </summary>
        public static string OpenWeatherApiKeyDescription {
            get {
                return ResourceManager.GetString("OpenWeatherApiKeyDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 请输入 API Key 的本地化字符串。
        /// </summary>
        public static string OpenWeatherApiKeyPlaceholder {
            get {
                return ResourceManager.GetString("OpenWeatherApiKeyPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 失败时回退到小米天气 的本地化字符串。
        /// </summary>
        public static string FallbackToXiaomiWeather {
            get {
                return ResourceManager.GetString("FallbackToXiaomiWeather", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用后，所选天气源不可用时继续使用默认源。 的本地化字符串。
        /// </summary>
        public static string FallbackToXiaomiWeatherDescription {
            get {
                return ResourceManager.GetString("FallbackToXiaomiWeatherDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 外观与高级设置 的本地化字符串。
        /// </summary>
        public static string AppearanceAndAdvancedSettings {
            get {
                return ResourceManager.GetString("AppearanceAndAdvancedSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天气图标包 的本地化字符串。
        /// </summary>
        public static string WeatherIconPack {
            get {
                return ResourceManager.GetString("WeatherIconPack", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 调整在显示天气类型时使用的图标外观。 的本地化字符串。
        /// </summary>
        public static string WeatherIconPackDescription {
            get {
                return ResourceManager.GetString("WeatherIconPackDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 排除的气象预警 的本地化字符串。
        /// </summary>
        public static string ExcludedWeatherAlerts {
            get {
                return ResourceManager.GetString("ExcludedWeatherAlerts", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 包含以下字符串的预警将不会显示，一行一条排除项。 的本地化字符串。
        /// </summary>
        public static string ExcludedWeatherAlertsDescription {
            get {
                return ResourceManager.GetString("ExcludedWeatherAlertsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 排除列表 的本地化字符串。
        /// </summary>
        public static string ExclusionList {
            get {
                return ResourceManager.GetString("ExclusionList", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不使用 TLS 协议获取天气 的本地化字符串。
        /// </summary>
        public static string NoTLSWeather {
            get {
                return ResourceManager.GetString("NoTLSWeather", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不建议启用。启用后，应用将通过不安全的 HTTP 协议获取天气信息。 的本地化字符串。
        /// </summary>
        public static string NoTLSWeatherDescription {
            get {
                return ResourceManager.GetString("NoTLSWeatherDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 要调整天气提醒设置，请转到 的本地化字符串。
        /// </summary>
        public static string WeatherHintNotificationPrefix {
            get {
                return ResourceManager.GetString("WeatherHintNotificationPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 【提醒】页面 的本地化字符串。
        /// </summary>
        public static string WeatherHintNotificationLink {
            get {
                return ResourceManager.GetString("WeatherHintNotificationLink", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 。 的本地化字符串。
        /// </summary>
        public static string WeatherHintNotificationSuffix {
            get {
                return ResourceManager.GetString("WeatherHintNotificationSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 要调整主界面上的天气快速信息，请在 的本地化字符串。
        /// </summary>
        public static string WeatherHintComponentsPrefix {
            get {
                return ResourceManager.GetString("WeatherHintComponentsPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 【组件】页面 的本地化字符串。
        /// </summary>
        public static string WeatherHintComponentsLink {
            get {
                return ResourceManager.GetString("WeatherHintComponentsLink", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 中配置天气简报组件。 的本地化字符串。
        /// </summary>
        public static string WeatherHintComponentsSuffix {
            get {
                return ResourceManager.GetString("WeatherHintComponentsSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在定位... 的本地化字符串。
        /// </summary>
        public static string LocatingToast {
            get {
                return ResourceManager.GetString("LocatingToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 定位成功 的本地化字符串。
        /// </summary>
        public static string LocateSuccessToast {
            get {
                return ResourceManager.GetString("LocateSuccessToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法获取当前位置：{0} 的本地化字符串。
        /// </summary>
        public static string GetCurrentPositionFailedFormat {
            get {
                return ResourceManager.GetString("GetCurrentPositionFailedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此天气信息降级了坐标精度: {0}位小数 的本地化字符串。
        /// </summary>
        public static string WeatherPrecisionDegradedFormat {
            get {
                return ResourceManager.GetString("WeatherPrecisionDegradedFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天气刷新成功 的本地化字符串。
        /// </summary>
        public static string WeatherRefreshSuccessToast {
            get {
                return ResourceManager.GetString("WeatherRefreshSuccessToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天气刷新失败: {0} 的本地化字符串。
        /// </summary>
        public static string WeatherRefreshFailedFormat {
            get {
                return ResourceManager.GetString("WeatherRefreshFailedFormat", resourceCulture);
            }
        }
    }
}
