//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Services.ProfileTransfer {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Services.ProfileTransfer.Localization.Services.ProfileTransfer", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 Class Widgets 2 课表文件内容为空。 的本地化字符串。
        /// </summary>
        public static string EmptyScheduleFile {
            get {
                return ResourceManager.GetString("EmptyScheduleFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课表文件缺少 meta 信息。 的本地化字符串。
        /// </summary>
        public static string MissingMetaInfo {
            get {
                return ResourceManager.GetString("MissingMetaInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不支持 Class Widgets 2 课表版本 {0}，当前仅支持版本 {1}。 的本地化字符串。
        /// </summary>
        public static string UnsupportedVersionFmt {
            get {
                return ResourceManager.GetString("UnsupportedVersionFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 meta.maxWeekCycle 必须大于 0。 的本地化字符串。
        /// </summary>
        public static string MaxWeekCycleInvalid {
            get {
                return ResourceManager.GetString("MaxWeekCycleInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 meta.startDate 不是有效的 yyyy-MM-dd 日期。 的本地化字符串。
        /// </summary>
        public static string InvalidStartDate {
            get {
                return ResourceManager.GetString("InvalidStartDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课表使用 {0} 周轮换，超过 ClassFabric 支持的 {1} 周；将仅保留每周课表、非周期覆盖项和指定日期课表 的本地化字符串。
        /// </summary>
        public static string WeekCycleTruncationWarningFmt {
            get {
                return ResourceManager.GetString("WeekCycleTruncationWarningFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 缺少 ID 或名称的科目将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningInvalidSubject {
            get {
                return ResourceManager.GetString("WarningInvalidSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ID 重复的科目将保留第一个，其余将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningDuplicateSubject {
            get {
                return ResourceManager.GetString("WarningDuplicateSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 科目的图标、颜色或地点字段不受支持，将被忽略 的本地化字符串。
        /// </summary>
        public static string WarningUnsupportedSubjectFields {
            get {
                return ResourceManager.GetString("WarningUnsupportedSubjectFields", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 缺少 ID 的时间线将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningInvalidTimeline {
            get {
                return ResourceManager.GetString("WarningInvalidTimeline", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ID 重复的时间线将保留第一个，其余将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningDuplicateTimeline {
            get {
                return ResourceManager.GetString("WarningDuplicateTimeline", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间线 的本地化字符串。
        /// </summary>
        public static string EntityTimeline {
            get {
                return ResourceManager.GetString("EntityTimeline", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无效的指定日期将被忽略；若时间线没有有效星期信息，整条时间线也会被跳过 的本地化字符串。
        /// </summary>
        public static string WarningInvalidDate {
            get {
                return ResourceManager.GetString("WarningInvalidDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 没有有效星期或指定日期的时间线将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningTimelineWithoutDay {
            get {
                return ResourceManager.GetString("WarningTimelineWithoutDay", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 超长轮换中的周期限定时间线将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningOversizedCycleTimeline {
            get {
                return ResourceManager.GetString("WarningOversizedCycleTimeline", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 缺少 ID 的课表条目将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningInvalidEntry {
            get {
                return ResourceManager.GetString("WarningInvalidEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ID 重复的课表条目将保留第一个，其余将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningDuplicateEntry {
            get {
                return ResourceManager.GetString("WarningDuplicateEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 类型未知的课表条目将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningUnknownEntryType {
            get {
                return ResourceManager.GetString("WarningUnknownEntryType", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 起止时间无效的课表条目将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningInvalidEntryTime {
            get {
                return ResourceManager.GetString("WarningInvalidEntryTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课表条目引用了不存在的科目，该科目引用将被忽略 的本地化字符串。
        /// </summary>
        public static string WarningUnknownEntrySubject {
            get {
                return ResourceManager.GetString("WarningUnknownEntrySubject", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 缺少 ID 或 ID 重复的覆盖项将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningInvalidOverrideId {
            get {
                return ResourceManager.GetString("WarningInvalidOverrideId", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 引用不存在课表条目的覆盖项将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningUnknownOverrideEntry {
            get {
                return ResourceManager.GetString("WarningUnknownOverrideEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 覆盖项 的本地化字符串。
        /// </summary>
        public static string EntityOverride {
            get {
                return ResourceManager.GetString("EntityOverride", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 超长轮换中的周期限定覆盖项将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningOversizedCycleOverride {
            get {
                return ResourceManager.GetString("WarningOversizedCycleOverride", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 覆盖项引用了不存在的科目，该科目修改将被忽略 的本地化字符串。
        /// </summary>
        public static string WarningUnknownOverrideSubject {
            get {
                return ResourceManager.GetString("WarningUnknownOverrideSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 覆盖项中的无效起止时间将被忽略 的本地化字符串。
        /// </summary>
        public static string WarningInvalidOverrideTime {
            get {
                return ResourceManager.GetString("WarningInvalidOverrideTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 同一指定日期的多条时间线将只保留第一条 的本地化字符串。
        /// </summary>
        public static string WarningDuplicateDateTimeline {
            get {
                return ResourceManager.GetString("WarningDuplicateDateTimeline", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 （指定日期） 的本地化字符串。
        /// </summary>
        public static string NamedDateSuffix {
            get {
                return ResourceManager.GetString("NamedDateSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}中的无效星期值将被忽略 的本地化字符串。
        /// </summary>
        public static string WarningInvalidDayFmt {
            get {
                return ResourceManager.GetString("WarningInvalidDayFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}中的未知周轮换值将导致该元素被跳过 的本地化字符串。
        /// </summary>
        public static string WarningUnknownWeeksFmt {
            get {
                return ResourceManager.GetString("WarningUnknownWeeksFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 {0}中的越界周轮换值将被忽略 的本地化字符串。
        /// </summary>
        public static string WarningOutOfRangeWeeksFmt {
            get {
                return ResourceManager.GetString("WarningOutOfRangeWeeksFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周一 的本地化字符串。
        /// </summary>
        public static string DayMonday {
            get {
                return ResourceManager.GetString("DayMonday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周二 的本地化字符串。
        /// </summary>
        public static string DayTuesday {
            get {
                return ResourceManager.GetString("DayTuesday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周三 的本地化字符串。
        /// </summary>
        public static string DayWednesday {
            get {
                return ResourceManager.GetString("DayWednesday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周四 的本地化字符串。
        /// </summary>
        public static string DayThursday {
            get {
                return ResourceManager.GetString("DayThursday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周五 的本地化字符串。
        /// </summary>
        public static string DayFriday {
            get {
                return ResourceManager.GetString("DayFriday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周六 的本地化字符串。
        /// </summary>
        public static string DaySaturday {
            get {
                return ResourceManager.GetString("DaySaturday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周日 的本地化字符串。
        /// </summary>
        public static string DaySunday {
            get {
                return ResourceManager.GetString("DaySunday", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未知星期 的本地化字符串。
        /// </summary>
        public static string DayUnknown {
            get {
                return ResourceManager.GetString("DayUnknown", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 单周 的本地化字符串。
        /// </summary>
        public static string OddWeekLabel {
            get {
                return ResourceManager.GetString("OddWeekLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 双周 的本地化字符串。
        /// </summary>
        public static string EvenWeekLabel {
            get {
                return ResourceManager.GetString("EvenWeekLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 （{0}） 的本地化字符串。
        /// </summary>
        public static string OddEvenWeekSuffixFmt {
            get {
                return ResourceManager.GetString("OddEvenWeekSuffixFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 （第 {0}/{1} 周） 的本地化字符串。
        /// </summary>
        public static string WeekCycleSuffixFmt {
            get {
                return ResourceManager.GetString("WeekCycleSuffixFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 （{0} 项） 的本地化字符串。
        /// </summary>
        public static string WarningCountSuffixFmt {
            get {
                return ResourceManager.GetString("WarningCountSuffixFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 应用覆盖项后起止时间无效的课表条目将被跳过 的本地化字符串。
        /// </summary>
        public static string WarningInvalidResolvedTime {
            get {
                return ResourceManager.GetString("WarningInvalidResolvedTime", resourceCulture);
            }
        }
    }
}
