<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ClassIsland.Shared</AssemblyName>
    <RootNamespace>ClassIsland.Shared</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ClassFabric.Shared\ClassFabric.Shared.csproj" />
  </ItemGroup>
</Project>
