//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Windows.ProfileSettings {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Windows.ProfileSettings.Localization.Windows.ProfileSettings", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 档案编辑 的本地化字符串。
        /// </summary>
        public static string ProfileEditorHeader {
            get {
                return ResourceManager.GetString("ProfileEditorHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课表 的本地化字符串。
        /// </summary>
        public static string ClassPlansTabHeader {
            get {
                return ResourceManager.GetString("ClassPlansTabHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课程 的本地化字符串。
        /// </summary>
        public static string SchedulesTabHeader {
            get {
                return ResourceManager.GetString("SchedulesTabHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已禁止 的本地化字符串。
        /// </summary>
        public static string ForbiddenTabHeader {
            get {
                return ResourceManager.GetString("ForbiddenTabHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 调课 的本地化字符串。
        /// </summary>
        public static string AdjustmentTabHeader {
            get {
                return ResourceManager.GetString("AdjustmentTabHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课程表信息 的本地化字符串。
        /// </summary>
        public static string ClassPlanInfoHeader {
            get {
                return ResourceManager.GetString("ClassPlanInfoHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间表信息 的本地化字符串。
        /// </summary>
        public static string TimeLayoutInfoHeader {
            get {
                return ResourceManager.GetString("TimeLayoutInfoHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 管理档案 的本地化字符串。
        /// </summary>
        public static string ManageProfilesHeader {
            get {
                return ResourceManager.GetString("ManageProfilesHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 管理与切换保存的档案。切换档案需要重新启动应用。 的本地化字符串。
        /// </summary>
        public static string ManageProfilesDescription {
            get {
                return ResourceManager.GetString("ManageProfilesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前启用的课表 的本地化字符串。
        /// </summary>
        public static string CurrentClassPlanHeader {
            get {
                return ResourceManager.GetString("CurrentClassPlanHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 多周轮换偏移 的本地化字符串。
        /// </summary>
        public static string WeekOffsetHeader {
            get {
                return ResourceManager.GetString("WeekOffsetHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑时间点 的本地化字符串。
        /// </summary>
        public static string EditTimePointHeader {
            get {
                return ResourceManager.GetString("EditTimePointHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑课程信息 的本地化字符串。
        /// </summary>
        public static string EditClassInfoHeader {
            get {
                return ResourceManager.GetString("EditClassInfoHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑科目信息 的本地化字符串。
        /// </summary>
        public static string EditSubjectInfoHeader {
            get {
                return ResourceManager.GetString("EditSubjectInfoHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课表群 的本地化字符串。
        /// </summary>
        public static string ClassPlanGroupLabel {
            get {
                return ResourceManager.GetString("ClassPlanGroupLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 临时课表群 的本地化字符串。
        /// </summary>
        public static string TempClassPlanGroupLabel {
            get {
                return ResourceManager.GetString("TempClassPlanGroupLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 临时课表 的本地化字符串。
        /// </summary>
        public static string TempClassPlanLabel {
            get {
                return ResourceManager.GetString("TempClassPlanLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 临时层 的本地化字符串。
        /// </summary>
        public static string OverlayLabel {
            get {
                return ResourceManager.GetString("OverlayLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 迁移信息（调试） 的本地化字符串。
        /// </summary>
        public static string ProfileMigrationsDebugHeader {
            get {
                return ResourceManager.GetString("ProfileMigrationsDebugHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 直接编辑当前档案的迁移记录，保存方式与其他档案修改相同。 的本地化字符串。
        /// </summary>
        public static string ProfileMigrationsDebugDescription {
            get {
                return ResourceManager.GetString("ProfileMigrationsDebugDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间表 的本地化字符串。
        /// </summary>
        public static string TimeLayoutLabel {
            get {
                return ResourceManager.GetString("TimeLayoutLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 科目 的本地化字符串。
        /// </summary>
        public static string SubjectLabel {
            get {
                return ResourceManager.GetString("SubjectLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string TypeLabel {
            get {
                return ResourceManager.GetString("TypeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更多选项 的本地化字符串。
        /// </summary>
        public static string MoreOptionsLabel {
            get {
                return ResourceManager.GetString("MoreOptionsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string RefreshLabel {
            get {
                return ResourceManager.GetString("RefreshLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string AddLabel {
            get {
                return ResourceManager.GetString("AddLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string AddNewLabel {
            get {
                return ResourceManager.GetString("AddNewLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string DuplicateLabel {
            get {
                return ResourceManager.GetString("DuplicateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string CreateLabel {
            get {
                return ResourceManager.GetString("CreateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建副本 的本地化字符串。
        /// </summary>
        public static string CreateDuplicateLabel {
            get {
                return ResourceManager.GetString("CreateDuplicateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        public static string NewLabel {
            get {
                return ResourceManager.GetString("NewLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string DeleteLabel {
            get {
                return ResourceManager.GetString("DeleteLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除选中项 的本地化字符串。
        /// </summary>
        public static string DeleteSelectedItemLabel {
            get {
                return ResourceManager.GetString("DeleteSelectedItemLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        public static string RenameLabel {
            get {
                return ResourceManager.GetString("RenameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OKLabel {
            get {
                return ResourceManager.GetString("OKLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string SaveLabel {
            get {
                return ResourceManager.GetString("SaveLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string HelpLabel {
            get {
                return ResourceManager.GetString("HelpLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不信任 的本地化字符串。
        /// </summary>
        public static string UntrustedLabel {
            get {
                return ResourceManager.GetString("UntrustedLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导入/导出 的本地化字符串。
        /// </summary>
        public static string ImportExportLabel {
            get {
                return ResourceManager.GetString("ImportExportLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string ClearLabel {
            get {
                return ResourceManager.GetString("ClearLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清除临时层 的本地化字符串。
        /// </summary>
        public static string ClearOverlayLabel {
            get {
                return ResourceManager.GetString("ClearOverlayLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清除临时课表 的本地化字符串。
        /// </summary>
        public static string ClearTempClassPlanLabel {
            get {
                return ResourceManager.GetString("ClearTempClassPlanLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建档案 的本地化字符串。
        /// </summary>
        public static string CreateProfileLabel {
            get {
                return ResourceManager.GetString("CreateProfileLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        public static string OpenFolderLabel {
            get {
                return ResourceManager.GetString("OpenFolderLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 详细信息 的本地化字符串。
        /// </summary>
        public static string DetailsLabel {
            get {
                return ResourceManager.GetString("DetailsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 详细看板 的本地化字符串。
        /// </summary>
        public static string DetailsDashboardLabel {
            get {
                return ResourceManager.GetString("DetailsDashboardLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建临时层 的本地化字符串。
        /// </summary>
        public static string CreateOverlayHeader {
            get {
                return ResourceManager.GetString("CreateOverlayHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 修改课程 的本地化字符串。
        /// </summary>
        public static string ChangeClassHeader {
            get {
                return ResourceManager.GetString("ChangeClassHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 交换课程 的本地化字符串。
        /// </summary>
        public static string SwapClassesLabel {
            get {
                return ResourceManager.GetString("SwapClassesLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 完成交换 的本地化字符串。
        /// </summary>
        public static string CompleteSwapLabel {
            get {
                return ResourceManager.GetString("CompleteSwapLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 永久换课 的本地化字符串。
        /// </summary>
        public static string TempSwapModeLabel {
            get {
                return ResourceManager.GetString("TempSwapModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 本周 的本地化字符串。
        /// </summary>
        public static string ThisWeekLabel {
            get {
                return ResourceManager.GetString("ThisWeekLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 撤销 的本地化字符串。
        /// </summary>
        public static string UndoButton {
            get {
                return ResourceManager.GetString("UndoButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 撤销上一步 (Ctrl+Z) 的本地化字符串。
        /// </summary>
        public static string UndoLastStepButton {
            get {
                return ResourceManager.GetString("UndoLastStepButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重做上一步 (Ctrl+Y) 的本地化字符串。
        /// </summary>
        public static string RedoLastStepButton {
            get {
                return ResourceManager.GetString("RedoLastStepButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 撤销历史 的本地化字符串。
        /// </summary>
        public static string UndoHistoryLabel {
            get {
                return ResourceManager.GetString("UndoHistoryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重做历史 的本地化字符串。
        /// </summary>
        public static string RedoHistoryLabel {
            get {
                return ResourceManager.GetString("RedoHistoryLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 前往编排时间表 的本地化字符串。
        /// </summary>
        public static string GoToTimeLayoutsButton {
            get {
                return ResourceManager.GetString("GoToTimeLayoutsButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 前往设置时间表 的本地化字符串。
        /// </summary>
        public static string GoToSetTimeLayoutButton {
            get {
                return ResourceManager.GetString("GoToSetTimeLayoutButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 立即重启 的本地化字符串。
        /// </summary>
        public static string RestartNowButton {
            get {
                return ResourceManager.GetString("RestartNowButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建课表 的本地化字符串。
        /// </summary>
        public static string NewClassPlanButton {
            get {
                return ResourceManager.GetString("NewClassPlanButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 信任此档案 的本地化字符串。
        /// </summary>
        public static string TrustProfileButton {
            get {
                return ResourceManager.GetString("TrustProfileButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        public static string ContinueLabel {
            get {
                return ResourceManager.GetString("ContinueLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除时间表 的本地化字符串。
        /// </summary>
        public static string DeleteTimeLayoutLabel {
            get {
                return ResourceManager.GetString("DeleteTimeLayoutLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前： 的本地化字符串。
        /// </summary>
        public static string CurrentPrefixLabel {
            get {
                return ResourceManager.GetString("CurrentPrefixLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 分钟 的本地化字符串。
        /// </summary>
        public static string MinutesSuffix {
            get {
                return ResourceManager.GetString("MinutesSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周 的本地化字符串。
        /// </summary>
        public static string WeekUnitSuffix {
            get {
                return ResourceManager.GetString("WeekUnitSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 天 的本地化字符串。
        /// </summary>
        public static string DayUnitSuffix {
            get {
                return ResourceManager.GetString("DayUnitSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 （无） 的本地化字符串。
        /// </summary>
        public static string CurrentProfileNoneLabel {
            get {
                return ResourceManager.GetString("CurrentProfileNoneLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 了解更多… 的本地化字符串。
        /// </summary>
        public static string LearnMoreLabel {
            get {
                return ResourceManager.GetString("LearnMoreLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 调整多周轮换偏移… 的本地化字符串。
        /// </summary>
        public static string AdjustWeekOffsetLabel {
            get {
                return ResourceManager.GetString("AdjustWeekOffsetLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 覆盖 的本地化字符串。
        /// </summary>
        public static string OverrideLabel {
            get {
                return ResourceManager.GetString("OverrideLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 继承 的本地化字符串。
        /// </summary>
        public static string InheritLabel {
            get {
                return ResourceManager.GetString("InheritLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 经典 的本地化字符串。
        /// </summary>
        public static string ScheduleTypeClassic {
            get {
                return ResourceManager.GetString("ScheduleTypeClassic", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 exp_日程 的本地化字符串。
        /// </summary>
        public static string ScheduleTypeExperimental {
            get {
                return ResourceManager.GetString("ScheduleTypeExperimental", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未选择课表 的本地化字符串。
        /// </summary>
        public static string NoClassPlanSelected {
            get {
                return ResourceManager.GetString("NoClassPlanSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 列表视图 的本地化字符串。
        /// </summary>
        public static string ListViewToolTip {
            get {
                return ResourceManager.GetString("ListViewToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 周视图 的本地化字符串。
        /// </summary>
        public static string WeekViewToolTip {
            get {
                return ResourceManager.GetString("WeekViewToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 月视图 的本地化字符串。
        /// </summary>
        public static string MonthViewToolTip {
            get {
                return ResourceManager.GetString("MonthViewToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 日程视图 的本地化字符串。
        /// </summary>
        public static string ScheduleViewToolTip {
            get {
                return ResourceManager.GetString("ScheduleViewToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 触发规则 的本地化字符串。
        /// </summary>
        public static string TriggerRuleToolTip {
            get {
                return ResourceManager.GetString("TriggerRuleToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建档案。 的本地化字符串。
        /// </summary>
        public static string CreateProfileTip {
            get {
                return ResourceManager.GetString("CreateProfileTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 打开档案文件夹。 的本地化字符串。
        /// </summary>
        public static string OpenProfileFolderTip {
            get {
                return ResourceManager.GetString("OpenProfileFolderTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重新加载档案列表。 的本地化字符串。
        /// </summary>
        public static string RefreshProfilesTip {
            get {
                return ResourceManager.GetString("RefreshProfilesTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建一个新的课表群。 的本地化字符串。
        /// </summary>
        public static string CreateClassPlanGroupTip {
            get {
                return ResourceManager.GetString("CreateClassPlanGroupTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建一个课表。 的本地化字符串。
        /// </summary>
        public static string CreateClassPlanTip {
            get {
                return ResourceManager.GetString("CreateClassPlanTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 复制一个当前选中的课表的副本。 的本地化字符串。
        /// </summary>
        public static string DuplicateClassPlanTip {
            get {
                return ResourceManager.GetString("DuplicateClassPlanTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除该课表。 的本地化字符串。
        /// </summary>
        public static string DeleteClassPlanTip {
            get {
                return ResourceManager.GetString("DeleteClassPlanTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查看并编辑课表的基本信息。 的本地化字符串。
        /// </summary>
        public static string ViewClassPlanDetailsTip {
            get {
                return ResourceManager.GetString("ViewClassPlanDetailsTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查看课表的所有时间点的附加设置继承情况。 的本地化字符串。
        /// </summary>
        public static string DetailsDashboardTip {
            get {
                return ResourceManager.GetString("DetailsDashboardTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建临时课表层。 的本地化字符串。
        /// </summary>
        public static string CreateOverlayTip {
            get {
                return ResourceManager.GetString("CreateOverlayTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清除临时层课表。 的本地化字符串。
        /// </summary>
        public static string ClearOverlayTip {
            get {
                return ResourceManager.GetString("ClearOverlayTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 清除选择的临时课表，并恢复至正常课表安排。 的本地化字符串。
        /// </summary>
        public static string ClearTempClassPlanTip {
            get {
                return ResourceManager.GetString("ClearTempClassPlanTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建一个时间表。 的本地化字符串。
        /// </summary>
        public static string CreateTimeLayoutTip {
            get {
                return ResourceManager.GetString("CreateTimeLayoutTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 复制选中的时间表。 的本地化字符串。
        /// </summary>
        public static string DuplicateTimeLayoutTip {
            get {
                return ResourceManager.GetString("DuplicateTimeLayoutTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此时间表正在活动。 的本地化字符串。
        /// </summary>
        public static string TimeLayoutActiveTip {
            get {
                return ResourceManager.GetString("TimeLayoutActiveTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 添加上课时间点。 的本地化字符串。
        /// </summary>
        public static string AddOnClassTimePointTip {
            get {
                return ResourceManager.GetString("AddOnClassTimePointTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 添加课间休息时间点。 的本地化字符串。
        /// </summary>
        public static string AddBreakTimePointTip {
            get {
                return ResourceManager.GetString("AddBreakTimePointTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 添加分割线。 的本地化字符串。
        /// </summary>
        public static string AddSeparatorTip {
            get {
                return ResourceManager.GetString("AddSeparatorTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 添加行动时间点。 的本地化字符串。
        /// </summary>
        public static string AddActionTimePointTip {
            get {
                return ResourceManager.GetString("AddActionTimePointTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建选中时间点的副本。 的本地化字符串。
        /// </summary>
        public static string DuplicateTimePointTip {
            get {
                return ResourceManager.GetString("DuplicateTimePointTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 撤销 (Ctrl+Z 单步) 的本地化字符串。
        /// </summary>
        public static string UndoStepToolTip {
            get {
                return ResourceManager.GetString("UndoStepToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重做 (Ctrl+Y 单步) 的本地化字符串。
        /// </summary>
        public static string RedoStepToolTip {
            get {
                return ResourceManager.GetString("RedoStepToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除选中的时间点。 的本地化字符串。
        /// </summary>
        public static string DeleteTimePointTip {
            get {
                return ResourceManager.GetString("DeleteTimePointTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重新排序该时间表中的时间点。 的本地化字符串。
        /// </summary>
        public static string ResortTimePointsTip {
            get {
                return ResourceManager.GetString("ResortTimePointsTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查看并编辑时间表的基本信息。 的本地化字符串。
        /// </summary>
        public static string ViewTimeLayoutDetailsTip {
            get {
                return ResourceManager.GetString("ViewTimeLayoutDetailsTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除该时间表。 的本地化字符串。
        /// </summary>
        public static string DeleteTimeLayoutTip {
            get {
                return ResourceManager.GetString("DeleteTimeLayoutTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间点吸附 的本地化字符串。
        /// </summary>
        public static string TimePointSnapTip {
            get {
                return ResourceManager.GetString("TimePointSnapTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        public static string ZoomOutTip {
            get {
                return ResourceManager.GetString("ZoomOutTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        public static string ZoomInTip {
            get {
                return ResourceManager.GetString("ZoomInTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 定位到选择的时间点 的本地化字符串。
        /// </summary>
        public static string LocateSelectedTimePointTip {
            get {
                return ResourceManager.GetString("LocateSelectedTimePointTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建一个课程。 的本地化字符串。
        /// </summary>
        public static string CreateScheduleTip {
            get {
                return ResourceManager.GetString("CreateScheduleTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 复制选中的课程。 的本地化字符串。
        /// </summary>
        public static string DuplicateScheduleTip {
            get {
                return ResourceManager.GetString("DuplicateScheduleTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除选中的课程。 的本地化字符串。
        /// </summary>
        public static string DeleteScheduleTip {
            get {
                return ResourceManager.GetString("DeleteScheduleTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 拖拽调整课程顺序 的本地化字符串。
        /// </summary>
        public static string DragToReorderTip {
            get {
                return ResourceManager.GetString("DragToReorderTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择日期以跳转到所在周 的本地化字符串。
        /// </summary>
        public static string PickDateToJumpWeekTip {
            get {
                return ResourceManager.GetString("PickDateToJumpWeekTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 上一周 的本地化字符串。
        /// </summary>
        public static string PreviousWeekTip {
            get {
                return ResourceManager.GetString("PreviousWeekTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 下一周 的本地化字符串。
        /// </summary>
        public static string NextWeekTip {
            get {
                return ResourceManager.GetString("NextWeekTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建一个科目。 的本地化字符串。
        /// </summary>
        public static string CreateSubjectTip {
            get {
                return ResourceManager.GetString("CreateSubjectTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 复制选中的科目。 的本地化字符串。
        /// </summary>
        public static string DuplicateSubjectTip {
            get {
                return ResourceManager.GetString("DuplicateSubjectTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除选中的科目。 的本地化字符串。
        /// </summary>
        public static string DeleteSubjectTip {
            get {
                return ResourceManager.GetString("DeleteSubjectTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前启用的档案 的本地化字符串。
        /// </summary>
        public static string CurrentProfileTip {
            get {
                return ResourceManager.GetString("CurrentProfileTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用临时课表 的本地化字符串。
        /// </summary>
        public static string EnableTempClassPlanTip {
            get {
                return ResourceManager.GetString("EnableTempClassPlanTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 保存当前档案文件。 的本地化字符串。
        /// </summary>
        public static string SaveProfileTip {
            get {
                return ResourceManager.GetString("SaveProfileTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导入外部的课程信息，或导出当前的档案信息。 的本地化字符串。
        /// </summary>
        public static string ImportExportTip {
            get {
                return ResourceManager.GetString("ImportExportTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查看档案编辑器帮助 的本地化字符串。
        /// </summary>
        public static string ViewHelpTip {
            get {
                return ResourceManager.GetString("ViewHelpTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前档案不受信任，部分功能受限。 的本地化字符串。
        /// </summary>
        public static string UntrustedProfileTip {
            get {
                return ResourceManager.GetString("UntrustedProfileTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 换课成… 的本地化字符串。
        /// </summary>
        public static string ChangeClassToSelectorLabel {
            get {
                return ResourceManager.GetString("ChangeClassToSelectorLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 失效日期 的本地化字符串。
        /// </summary>
        public static string ExpireDateLabel {
            get {
                return ResourceManager.GetString("ExpireDateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 覆盖模式 的本地化字符串。
        /// </summary>
        public static string OverrideModeLabel {
            get {
                return ResourceManager.GetString("OverrideModeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用日期 的本地化字符串。
        /// </summary>
        public static string EnableDateLabel {
            get {
                return ResourceManager.GetString("EnableDateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 管理课表群 的本地化字符串。
        /// </summary>
        public static string ManageClassPlanGroupsLabel {
            get {
                return ResourceManager.GetString("ManageClassPlanGroupsLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 新建课表群 的本地化字符串。
        /// </summary>
        public static string CreateClassPlanGroupLabel {
            get {
                return ResourceManager.GetString("CreateClassPlanGroupLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间点时长 的本地化字符串。
        /// </summary>
        public static string TimePointDurationHeader {
            get {
                return ResourceManager.GetString("TimePointDurationHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认上课时间点时长 的本地化字符串。
        /// </summary>
        public static string DefaultOnClassDurationLabel {
            get {
                return ResourceManager.GetString("DefaultOnClassDurationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认课间时间点时长 的本地化字符串。
        /// </summary>
        public static string DefaultBreakDurationLabel {
            get {
                return ResourceManager.GetString("DefaultBreakDurationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        public static string StartTimeLabel {
            get {
                return ResourceManager.GetString("StartTimeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        public static string EndTimeLabel {
            get {
                return ResourceManager.GetString("EndTimeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认隐藏 的本地化字符串。
        /// </summary>
        public static string HideByDefault {
            get {
                return ResourceManager.GetString("HideByDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 覆盖现有课程 的本地化字符串。
        /// </summary>
        public static string OverwriteExistingClasses {
            get {
                return ResourceManager.GetString("OverwriteExistingClasses", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该科目是户外课程 的本地化字符串。
        /// </summary>
        public static string IsOutdoorSubject {
            get {
                return ResourceManager.GetString("IsOutdoorSubject", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 同时创建临时时间表 的本地化字符串。
        /// </summary>
        public static string AlsoCreateTempTimeLayout {
            get {
                return ResourceManager.GetString("AlsoCreateTempTimeLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自动启用 的本地化字符串。
        /// </summary>
        public static string AutoEnable {
            get {
                return ResourceManager.GetString("AutoEnable", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选完科目自动移动到下一个课程 的本地化字符串。
        /// </summary>
        public static string AutoMoveNextAfterSubjectSelected {
            get {
                return ResourceManager.GetString("AutoMoveNextAfterSubjectSelected", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课间名称 的本地化字符串。
        /// </summary>
        public static string BreakNameLabel {
            get {
                return ResourceManager.GetString("BreakNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 上课 的本地化字符串。
        /// </summary>
        public static string OnClassLabel {
            get {
                return ResourceManager.GetString("OnClassLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课间 的本地化字符串。
        /// </summary>
        public static string BreakLabel {
            get {
                return ResourceManager.GetString("BreakLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 课间休息 的本地化字符串。
        /// </summary>
        public static string BreakRestLabel {
            get {
                return ResourceManager.GetString("BreakRestLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 分割线 的本地化字符串。
        /// </summary>
        public static string SeparatorLabel {
            get {
                return ResourceManager.GetString("SeparatorLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 行动 的本地化字符串。
        /// </summary>
        public static string ActionLabel {
            get {
                return ResourceManager.GetString("ActionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 默认课程 的本地化字符串。
        /// </summary>
        public static string DefaultClassLabel {
            get {
                return ResourceManager.GetString("DefaultClassLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 图标 的本地化字符串。
        /// </summary>
        public static string IconLabel {
            get {
                return ResourceManager.GetString("IconLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 科目名 的本地化字符串。
        /// </summary>
        public static string SubjectNameLabel {
            get {
                return ResourceManager.GetString("SubjectNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 简称 的本地化字符串。
        /// </summary>
        public static string ShortNameLabel {
            get {
                return ResourceManager.GetString("ShortNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 主题色 的本地化字符串。
        /// </summary>
        public static string ThemeColorLabel {
            get {
                return ResourceManager.GetString("ThemeColorLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 科任老师 的本地化字符串。
        /// </summary>
        public static string TeacherLabel {
            get {
                return ResourceManager.GetString("TeacherLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 地点 的本地化字符串。
        /// </summary>
        public static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string EnabledColumnHeader {
            get {
                return ResourceManager.GetString("EnabledColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        public static string TimeColumnHeader {
            get {
                return ResourceManager.GetString("TimeColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 户外课程？ 的本地化字符串。
        /// </summary>
        public static string IsOutdoorColumnHeader {
            get {
                return ResourceManager.GetString("IsOutdoorColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 迁移 ID 的本地化字符串。
        /// </summary>
        public static string MigrationIdColumnHeader {
            get {
                return ResourceManager.GetString("MigrationIdColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 允许降级 的本地化字符串。
        /// </summary>
        public static string AllowDowngradeColumnHeader {
            get {
                return ResourceManager.GetString("AllowDowngradeColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 降级时移除 的本地化字符串。
        /// </summary>
        public static string RemoveOnDowngradeColumnHeader {
            get {
                return ResourceManager.GetString("RemoveOnDowngradeColumnHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 这是一个临时层课表，将在使用过后自动删除。 的本地化字符串。
        /// </summary>
        public static string ClassPlanOverlayInfoBarMessage {
            get {
                return ResourceManager.GetString("ClassPlanOverlayInfoBarMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 临时层课表将忽略触发规则强制启用。 的本地化字符串。
        /// </summary>
        public static string OverlayIgnoresTriggerRulesDescription {
            get {
                return ResourceManager.GetString("OverlayIgnoresTriggerRulesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 将会根据触发规则自动启用该课表。 的本地化字符串。
        /// </summary>
        public static string AutoEnableByTriggerRulesDescription {
            get {
                return ResourceManager.GetString("AutoEnableByTriggerRulesDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 该课表不会自动启用，只能通过临时课表或临时层手动启用该课表。 的本地化字符串。
        /// </summary>
        public static string ManualEnableOnlyDescription {
            get {
                return ResourceManager.GetString("ManualEnableOnlyDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 临时层课表将优先于临时课表应用。临时层课表将在该课表过期后自动清除。 的本地化字符串。
        /// </summary>
        public static string OverlayPriorityDescription {
            get {
                return ResourceManager.GetString("OverlayPriorityDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 若当天授课计划有变，可临时选择某一课表作为当天的课表。该设置仅在当天有效。 的本地化字符串。
        /// </summary>
        public static string TempClassPlanDescription {
            get {
                return ResourceManager.GetString("TempClassPlanDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 临时课表被临时层课表覆盖。要使用临时课表，请暂时禁用或清除临时层课表。 的本地化字符串。
        /// </summary>
        public static string TempClassPlanCoveredByOverlayDescription {
            get {
                return ResourceManager.GetString("TempClassPlanCoveredByOverlayDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您可以通过课表群对课表进行分组，并灵活地启用一批课表。 的本地化字符串。
        /// </summary>
        public static string ClassPlanGroupsIntroPrefix {
            get {
                return ResourceManager.GetString("ClassPlanGroupsIntroPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在设置课表之前，您需要在【时间表】页面中根据学校的作息安排编排时间表。 的本地化字符串。
        /// </summary>
        public static string NoTimeLayoutWarningMessage {
            get {
                return ResourceManager.GetString("NoTimeLayoutWarningMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您还没有为此课表设置时间表。在编排课程之前，您需要在【详细信息】中为本课表设置一个时间表。 的本地化字符串。
        /// </summary>
        public static string EmptyTimeLayoutWarningMessage {
            get {
                return ResourceManager.GetString("EmptyTimeLayoutWarningMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 此操作无法撤销。 的本地化字符串。
        /// </summary>
        public static string CannotBeUndoneDescription {
            get {
                return ResourceManager.GetString("CannotBeUndoneDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 要删除课表 的本地化字符串。
        /// </summary>
        public static string DeleteClassPlanConfirmPrefix {
            get {
                return ResourceManager.GetString("DeleteClassPlanConfirmPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 吗？ 的本地化字符串。
        /// </summary>
        public static string DeleteClassPlanConfirmSuffix {
            get {
                return ResourceManager.GetString("DeleteClassPlanConfirmSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在交换课程。选择要与 的本地化字符串。
        /// </summary>
        public static string SwapClassesIntroPrefix {
            get {
                return ResourceManager.GetString("SwapClassesIntroPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 交换的课程，然后点击【完成交换】。 的本地化字符串。
        /// </summary>
        public static string SwapClassesIntroSuffix {
            get {
                return ResourceManager.GetString("SwapClassesIntroSuffix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 若默认隐藏一个时间点，那么只有在处于此时间点时，此时间点才会显示。 的本地化字符串。
        /// </summary>
        public static string HideByDefaultDescription {
            get {
                return ResourceManager.GetString("HideByDefaultDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 不信任的档案 的本地化字符串。
        /// </summary>
        public static string UntrustedProfileTitle {
            get {
                return ResourceManager.GetString("UntrustedProfileTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前档案不受信任，行动时间点不会自动运行。 的本地化字符串。
        /// </summary>
        public static string UntrustedProfileInfoBarMessage {
            get {
                return ResourceManager.GetString("UntrustedProfileInfoBarMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您的组织已禁用档案编辑功能。 的本地化字符串。
        /// </summary>
        public static string ProfileEditingDisabledByPolicy {
            get {
                return ResourceManager.GetString("ProfileEditingDisabledByPolicy", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 实验性功能，正在开发中，不保证数据完全向后兼容，请以最终版本为准。 的本地化字符串。
        /// </summary>
        public static string ExperimentalFeatureWarning {
            get {
                return ResourceManager.GetString("ExperimentalFeatureWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        public static string TransferImportLabel {
            get {
                return ResourceManager.GetString("TransferImportLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string TransferExportLabel {
            get {
                return ResourceManager.GetString("TransferExportLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 执行 的本地化字符串。
        /// </summary>
        public static string TransferExecuteLabel {
            get {
                return ResourceManager.GetString("TransferExecuteLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 迁移 的本地化字符串。
        /// </summary>
        public static string TransferMigrateLabel {
            get {
                return ResourceManager.GetString("TransferMigrateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前档案不受信任，部分功能（如行动时间点等）将禁用。如果您信任此档案并希望启用这些受限的功能，请将此档案设置为信任。 的本地化字符串。
        /// </summary>
        public static string UntrustedProfileDialogContent {
            get {
                return ResourceManager.GetString("UntrustedProfileDialogContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已保存到 {0}。 的本地化字符串。
        /// </summary>
        public static string ProfileSavedToPathFmt {
            get {
                return ResourceManager.GetString("ProfileSavedToPathFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法保存档案 的本地化字符串。
        /// </summary>
        public static string SaveProfileFailedToast {
            get {
                return ResourceManager.GetString("SaveProfileFailedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 档案名称 的本地化字符串。
        /// </summary>
        public static string ProfileNameLabel {
            get {
                return ResourceManager.GetString("ProfileNameLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法重命名档案，因为已存在一个相同名称的档案。 的本地化字符串。
        /// </summary>
        public static string RenameProfileConflictToast {
            get {
                return ResourceManager.GetString("RenameProfileConflictToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重命名档案 的本地化字符串。
        /// </summary>
        public static string RenameProfileTitle {
            get {
                return ResourceManager.GetString("RenameProfileTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法删除已加载或将要加载的档案。 的本地化字符串。
        /// </summary>
        public static string CannotDeleteLoadedProfileToast {
            get {
                return ResourceManager.GetString("CannotDeleteLoadedProfileToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除档案 的本地化字符串。
        /// </summary>
        public static string DeleteProfileTitle {
            get {
                return ResourceManager.GetString("DeleteProfileTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您确定要删除档案 {0} 吗？此操作无法撤销，档案内的课表、时间表、科目等信息都将被删除！ 的本地化字符串。
        /// </summary>
        public static string DeleteProfileConfirmFmt {
            get {
                return ResourceManager.GetString("DeleteProfileConfirmFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 需要重启 的本地化字符串。
        /// </summary>
        public static string RestartRequiredTitle {
            get {
                return ResourceManager.GetString("RestartRequiredTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 切换档案需要重启应用以生效。 的本地化字符串。
        /// </summary>
        public static string SwitchProfileRestartMessage {
            get {
                return ResourceManager.GetString("SwitchProfileRestartMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 在这一天已存在一个临时层课表，无法创建新的临时层课表。 的本地化字符串。
        /// </summary>
        public static string OverlayAlreadyExistsToast {
            get {
                return ResourceManager.GetString("OverlayAlreadyExistsToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已完成本周课表的录入。 的本地化字符串。
        /// </summary>
        public static string WeeklyEntryCompletedToast {
            get {
                return ResourceManager.GetString("WeeklyEntryCompletedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已跳转到次日课表。 的本地化字符串。
        /// </summary>
        public static string JumpedToNextDayToast {
            get {
                return ResourceManager.GetString("JumpedToNextDayToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已完成此课表的课程录入。 的本地化字符串。
        /// </summary>
        public static string ClassPlanEntryCompletedToast {
            get {
                return ResourceManager.GetString("ClassPlanEntryCompletedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 仍有课表在使用该时间表。删除时间表前需要删除所有使用该时间表的课表。 的本地化字符串。
        /// </summary>
        public static string TimeLayoutInUseToast {
            get {
                return ResourceManager.GetString("TimeLayoutInUseToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 要删除时间表“{0}”吗？此操作无法撤销。 的本地化字符串。
        /// </summary>
        public static string DeleteTimeLayoutConfirmFmt {
            get {
                return ResourceManager.GetString("DeleteTimeLayoutConfirmFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 添加{0} 的本地化字符串。
        /// </summary>
        public static string AddUndoDescriptionFmt {
            get {
                return ResourceManager.GetString("AddUndoDescriptionFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 删除{0} 的本地化字符串。
        /// </summary>
        public static string DeleteUndoDescriptionFmt {
            get {
                return ResourceManager.GetString("DeleteUndoDescriptionFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 没有合适的位置来插入新的时间点。 的本地化字符串。
        /// </summary>
        public static string NoRoomToInsertTimePointToast {
            get {
                return ResourceManager.GetString("NoRoomToInsertTimePointToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已向前插入了新的时间点。 的本地化字符串。
        /// </summary>
        public static string InsertedBeforeToast {
            get {
                return ResourceManager.GetString("InsertedBeforeToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 没有足够的空间完全插入该时间点，已缩短时间点长度。 的本地化字符串。
        /// </summary>
        public static string InsertShrunkToast {
            get {
                return ResourceManager.GetString("InsertShrunkToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 这里已经存在一条分割线。 的本地化字符串。
        /// </summary>
        public static string SeparatorExistsToast {
            get {
                return ResourceManager.GetString("SeparatorExistsToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 这里已经存在一个行动。 的本地化字符串。
        /// </summary>
        public static string ActionExistsToast {
            get {
                return ResourceManager.GetString("ActionExistsToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 没有足够的空间来复制时间点。 的本地化字符串。
        /// </summary>
        public static string NoRoomToDuplicateTimePointToast {
            get {
                return ResourceManager.GetString("NoRoomToDuplicateTimePointToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 没有合适的位置来复制时间点。 的本地化字符串。
        /// </summary>
        public static string NoRoomBeforeToDuplicateTimePointToast {
            get {
                return ResourceManager.GetString("NoRoomBeforeToDuplicateTimePointToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 没有足够的空间完全复制该时间点，已缩短时间点长度。 的本地化字符串。
        /// </summary>
        public static string DuplicateShrunkToast {
            get {
                return ResourceManager.GetString("DuplicateShrunkToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已创建时间点副本。 的本地化字符串。
        /// </summary>
        public static string TimePointDuplicatedToast {
            get {
                return ResourceManager.GetString("TimePointDuplicatedToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法移动到该日期或时间，请在右侧检查课程的时间和启用范围。 的本地化字符串。
        /// </summary>
        public static string CannotMoveScheduleItemToast {
            get {
                return ResourceManager.GetString("CannotMoveScheduleItemToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已删除 {0} 个课程。 的本地化字符串。
        /// </summary>
        public static string DeletedClassItemsFmt {
            get {
                return ResourceManager.GetString("DeletedClassItemsFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已删除 {0} 个科目。 的本地化字符串。
        /// </summary>
        public static string DeletedSubjectsFmt {
            get {
                return ResourceManager.GetString("DeletedSubjectsFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 选择课程区域无效。 的本地化字符串。
        /// </summary>
        public static string InvalidClassSelectionToast {
            get {
                return ResourceManager.GetString("InvalidClassSelectionToast", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 要继续{0}吗 的本地化字符串。
        /// </summary>
        public static string ContinueTransferConfirmTitleFmt {
            get {
                return ResourceManager.GetString("ContinueTransferConfirmTitleFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您先前已经成功地{0}了档案，您还要继续{0}吗？ 的本地化字符串。
        /// </summary>
        public static string ContinueTransferConfirmMessageFmt {
            get {
                return ResourceManager.GetString("ContinueTransferConfirmMessageFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 加载课表 的本地化字符串。
        /// </summary>
        public static string LoadClassPlanToggle {
            get {
                return ResourceManager.GetString("LoadClassPlanToggle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用临时层 的本地化字符串。
        /// </summary>
        public static string EnableOverlayToggle {
            get {
                return ResourceManager.GetString("EnableOverlayToggle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 刷新当前视图。 的本地化字符串。
        /// </summary>
        public static string RefreshCurrentViewTip {
            get {
                return ResourceManager.GetString("RefreshCurrentViewTip", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 编辑科目 的本地化字符串。
        /// </summary>
        public static string EditSubjectTabHeader {
            get {
                return ResourceManager.GetString("EditSubjectTabHeader", resourceCulture);
            }
        }
    }
}
