//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Services.Update {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Services.Update.Localization.Services.Update", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 更新成功 的本地化字符串。
        /// </summary>
        public static string UpdateSuccessTitle {
            get {
                return ResourceManager.GetString("UpdateSuccessTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 应用已更新到 {0}，点击以查看详细信息。 的本地化字符串。
        /// </summary>
        public static string UpdateSuccessBodyFmt {
            get {
                return ResourceManager.GetString("UpdateSuccessBodyFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 当前安装方式不支持应用内自动更新。请前往项目主页手动下载并安装最新版本。 的本地化字符串。
        /// </summary>
        public static string InstallMethodNotSupportedMessage {
            get {
                return ResourceManager.GetString("InstallMethodNotSupportedMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 发现新版本 的本地化字符串。
        /// </summary>
        public static string NewVersionFoundTitle {
            get {
                return ResourceManager.GetString("NewVersionFoundTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 点击以查看详细信息。 的本地化字符串。
        /// </summary>
        public static string NewVersionFoundFooter {
            get {
                return ResourceManager.GetString("NewVersionFoundFooter", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 没有可用的应用更新源，请检查更新源设置。 的本地化字符串。
        /// </summary>
        public static string NoAvailableUpdateSourceMessage {
            get {
                return ResourceManager.GetString("NoAvailableUpdateSourceMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新源 {0} 上的最新版本 {1} 没有提供与当前安装方式匹配的更新包，请稍后重试或前往项目主页手动下载。 的本地化字符串。
        /// </summary>
        public static string UpdatePackageMissingOnSourceFmt {
            get {
                return ResourceManager.GetString("UpdatePackageMissingOnSourceFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新源返回了无法识别的版本号：{0} 的本地化字符串。
        /// </summary>
        public static string UnrecognizedVersionFromSourceFmt {
            get {
                return ResourceManager.GetString("UnrecognizedVersionFromSourceFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 文件图签名校验不通过 的本地化字符串。
        /// </summary>
        public static string ManifestSignatureVerificationFailed {
            get {
                return ResourceManager.GetString("ManifestSignatureVerificationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 文件图解析失败 的本地化字符串。
        /// </summary>
        public static string ManifestParseFailed {
            get {
                return ResourceManager.GetString("ManifestParseFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 文件图组件根目录无效 的本地化字符串。
        /// </summary>
        public static string ManifestRootInvalid {
            get {
                return ResourceManager.GetString("ManifestRootInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 文件图哈希与下载时不符合，可能已经损坏 的本地化字符串。
        /// </summary>
        public static string FileHashMismatch {
            get {
                return ResourceManager.GetString("FileHashMismatch", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 下载的更新不适用于当前子频道的 ClassFabric 的本地化字符串。
        /// </summary>
        public static string UpdateNotForChannel {
            get {
                return ResourceManager.GetString("UpdateNotForChannel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 文件 {0}/{1} 的 SHA512 校验失败 的本地化字符串。
        /// </summary>
        public static string FileSha512MismatchFmt {
            get {
                return ResourceManager.GetString("FileSha512MismatchFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 文件图发现非法文件路径 的本地化字符串。
        /// </summary>
        public static string InvalidFilePathInManifest {
            get {
                return ResourceManager.GetString("InvalidFilePathInManifest", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 文件 {0}/{1} 未找到部署源 的本地化字符串。
        /// </summary>
        public static string DeploymentSourceNotFoundFmt {
            get {
                return ResourceManager.GetString("DeploymentSourceNotFoundFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 待处理更新缺少更新包下载信息，请重新检查更新。 的本地化字符串。
        /// </summary>
        public static string PendingUpdateMissingPackageInfo {
            get {
                return ResourceManager.GetString("PendingUpdateMissingPackageInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未找到已下载的更新包，请重新下载更新。 的本地化字符串。
        /// </summary>
        public static string DownloadedUpdatePackageNotFound {
            get {
                return ResourceManager.GetString("DownloadedUpdatePackageNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未检测到独立的程序包目录，当前安装形态无法就地部署更新，请手动下载安装包进行更新。 的本地化字符串。
        /// </summary>
        public static string NoDeploymentDirectoryMessage {
            get {
                return ResourceManager.GetString("NoDeploymentDirectoryMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新包结构无效：未找到应用部署目录。 的本地化字符串。
        /// </summary>
        public static string UpdatePackageStructureInvalid {
            get {
                return ResourceManager.GetString("UpdatePackageStructureInvalid", resourceCulture);
            }
        }
    }
}
