//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.SettingsPage.Update {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.SettingsPage.Update.Localization.SettingsPage.Update", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 下载进度 的本地化字符串。
        /// </summary>
        public static string DownloadProgressTitle {
            get {
                return ResourceManager.GetString("DownloadProgressTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 等待下载 的本地化字符串。
        /// </summary>
        public static string DownloadStatePending {
            get {
                return ResourceManager.GetString("DownloadStatePending", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在下载 的本地化字符串。
        /// </summary>
        public static string DownloadStateDownloading {
            get {
                return ResourceManager.GetString("DownloadStateDownloading", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string DownloadStateCompleted {
            get {
                return ResourceManager.GetString("DownloadStateCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string DownloadStateError {
            get {
                return ResourceManager.GetString("DownloadStateError", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 检查更新失败 的本地化字符串。
        /// </summary>
        public static string CheckUpdateFailed {
            get {
                return ResourceManager.GetString("CheckUpdateFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 上次检查更新时间： 的本地化字符串。
        /// </summary>
        public static string LastCheckUpdateTimePrefix {
            get {
                return ResourceManager.GetString("LastCheckUpdateTimePrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 发现新版本： 的本地化字符串。
        /// </summary>
        public static string NewVersionFoundPrefix {
            get {
                return ResourceManager.GetString("NewVersionFoundPrefix", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新时发生错误。 的本地化字符串。
        /// </summary>
        public static string UpdateErrorInfoBarTitle {
            get {
                return ResourceManager.GetString("UpdateErrorInfoBarTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 部署时发生错误，请稍后重试。 的本地化字符串。
        /// </summary>
        public static string DeployErrorInfoBarTitle {
            get {
                return ResourceManager.GetString("DeployErrorInfoBarTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新将在重启后应用 的本地化字符串。
        /// </summary>
        public static string RestartToApplyInfoBarTitle {
            get {
                return ResourceManager.GetString("RestartToApplyInfoBarTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已成功部署更新，下次启动应用时将启动新版本。您也可以现在重启以立即使用新版本的 ClassFabric。 的本地化字符串。
        /// </summary>
        public static string RestartToApplyInfoBarMessage {
            get {
                return ResourceManager.GetString("RestartToApplyInfoBarMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 检查更新 的本地化字符串。
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 下载并安装 的本地化字符串。
        /// </summary>
        public static string DownloadAndInstall {
            get {
                return ResourceManager.GetString("DownloadAndInstall", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 仅下载 的本地化字符串。
        /// </summary>
        public static string DownloadOnly {
            get {
                return ResourceManager.GetString("DownloadOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 安装更新 的本地化字符串。
        /// </summary>
        public static string InstallUpdate {
            get {
                return ResourceManager.GetString("InstallUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重启并应用更新 的本地化字符串。
        /// </summary>
        public static string RestartToApplyUpdate {
            get {
                return ResourceManager.GetString("RestartToApplyUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查看下载状态 的本地化字符串。
        /// </summary>
        public static string ShowDownloadStatus {
            get {
                return ResourceManager.GetString("ShowDownloadStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新日志 的本地化字符串。
        /// </summary>
        public static string ChangeLogTab {
            get {
                return ResourceManager.GetString("ChangeLogTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新设置 的本地化字符串。
        /// </summary>
        public static string UpdateSettingsTab {
            get {
                return ResourceManager.GetString("UpdateSettingsTab", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已经是最新版啦，真棒，夸夸你哦♪ 的本地化字符串。
        /// </summary>
        public static string AlreadyLatestEasterEgg {
            get {
                return ResourceManager.GetString("AlreadyLatestEasterEgg", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 真棒，您已更新到最新版本！ 的本地化字符串。
        /// </summary>
        public static string AlreadyLatest {
            get {
                return ResourceManager.GetString("AlreadyLatest", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 查看更新日志 的本地化字符串。
        /// </summary>
        public static string ViewChangeLog {
            get {
                return ResourceManager.GetString("ViewChangeLog", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新模式 的本地化字符串。
        /// </summary>
        public static string UpdateMode {
            get {
                return ResourceManager.GetString("UpdateMode", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 设置应用的更新模式。 的本地化字符串。
        /// </summary>
        public static string UpdateModeDescription {
            get {
                return ResourceManager.GetString("UpdateModeDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 从不自动更新 的本地化字符串。
        /// </summary>
        public static string UpdateModeNever {
            get {
                return ResourceManager.GetString("UpdateModeNever", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自动检查更新并通知 的本地化字符串。
        /// </summary>
        public static string UpdateModeCheckAndNotify {
            get {
                return ResourceManager.GetString("UpdateModeCheckAndNotify", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自动检查更新并下载 的本地化字符串。
        /// </summary>
        public static string UpdateModeCheckAndDownload {
            get {
                return ResourceManager.GetString("UpdateModeCheckAndDownload", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 自动检查更新并安装 的本地化字符串。
        /// </summary>
        public static string UpdateModeCheckAndInstall {
            get {
                return ResourceManager.GetString("UpdateModeCheckAndInstall", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新源 的本地化字符串。
        /// </summary>
        public static string UpdateSource {
            get {
                return ResourceManager.GetString("UpdateSource", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 控制获取应用更新信息的来源。GitHub Releases 为默认更新源，匿名访问受 GitHub 接口速率限制。 的本地化字符串。
        /// </summary>
        public static string UpdateSourceDescription {
            get {
                return ResourceManager.GetString("UpdateSourceDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 GitHub Releases（失败时回退到 ClassIsland 分发中心） 的本地化字符串。
        /// </summary>
        public static string UpdateSourceGitHubFallback {
            get {
                return ResourceManager.GetString("UpdateSourceGitHubFallback", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 ClassIsland 分发中心（兼容，不推荐） 的本地化字符串。
        /// </summary>
        public static string UpdateSourceDistributionCenterCompat {
            get {
                return ResourceManager.GetString("UpdateSourceDistributionCenterCompat", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 GitHub Releases 直接从 ClassFabric 的 GitHub 仓库读取发行版本，无需依赖 Class... 的本地化字符串。
        /// </summary>
        public static string UpdateSourceExplanation {
            get {
                return ResourceManager.GetString("UpdateSourceExplanation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新通道 的本地化字符串。
        /// </summary>
        public static string UpdateChannel {
            get {
                return ResourceManager.GetString("UpdateChannel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 控制应用的更新目标版本。ClassFabric 当前以预览版发行为主，因此默认使用预览版通道；版本的发行节奏和稳定程度因... 的本地化字符串。
        /// </summary>
        public static string UpdateChannelDescription {
            get {
                return ResourceManager.GetString("UpdateChannelDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 强制检查更新 的本地化字符串。
        /// </summary>
        public static string ForceCheckUpdate {
            get {
                return ResourceManager.GetString("ForceCheckUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 强制将应用更新到当前通道上的最新版本，即使此版本比应用当前版本更旧。 的本地化字符串。
        /// </summary>
        public static string ForceCheckUpdateDescription {
            get {
                return ResourceManager.GetString("ForceCheckUpdateDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您已更新到最新版本。 的本地化字符串。
        /// </summary>
        public static string StatusUpToDate {
            get {
                return ResourceManager.GetString("StatusUpToDate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 检测到更新。 的本地化字符串。
        /// </summary>
        public static string StatusUpdateAvailable {
            get {
                return ResourceManager.GetString("StatusUpdateAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已准备好安装更新。 的本地化字符串。
        /// </summary>
        public static string StatusUpdateDownloaded {
            get {
                return ResourceManager.GetString("StatusUpdateDownloaded", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 更新已就绪。 的本地化字符串。
        /// </summary>
        public static string StatusUpdateDeployed {
            get {
                return ResourceManager.GetString("StatusUpdateDeployed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 就绪 的本地化字符串。
        /// </summary>
        public static string WorkingStatusIdle {
            get {
                return ResourceManager.GetString("WorkingStatusIdle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在检查更新… 的本地化字符串。
        /// </summary>
        public static string WorkingStatusCheckingUpdates {
            get {
                return ResourceManager.GetString("WorkingStatusCheckingUpdates", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在下载更新… 的本地化字符串。
        /// </summary>
        public static string WorkingStatusDownloadingUpdates {
            get {
                return ResourceManager.GetString("WorkingStatusDownloadingUpdates", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在部署更新… 的本地化字符串。
        /// </summary>
        public static string WorkingStatusExtractingUpdates {
            get {
                return ResourceManager.GetString("WorkingStatusExtractingUpdates", resourceCulture);
            }
        }
    }
}
