//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassFabric.Assets.Localization.Windows.SettingsWindow {
    using System;


    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassFabric.Assets.Localization.Windows.SettingsWindow.Localization.Windows.SettingsWindow", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 需要重启 的本地化字符串。
        /// </summary>
        public static string RestartRequiredTitle {
            get {
                return ResourceManager.GetString("RestartRequiredTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 部分设置需要重启以应用更改。 的本地化字符串。
        /// </summary>
        public static string RestartRequiredContent {
            get {
                return ResourceManager.GetString("RestartRequiredContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 重启 的本地化字符串。
        /// </summary>
        public static string RestartButton {
            get {
                return ResourceManager.GetString("RestartButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法退出管理 的本地化字符串。
        /// </summary>
        public static string ExitManagementFailedTitle {
            get {
                return ResourceManager.GetString("ExitManagementFailedTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法退出管理：{0} 的本地化字符串。
        /// </summary>
        public static string ExitManagementFailedMessageFmt {
            get {
                return ResourceManager.GetString("ExitManagementFailedMessageFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 正在导出诊断信息… 的本地化字符串。
        /// </summary>
        public static string ExportingDiagnosticsMessage {
            get {
                return ResourceManager.GetString("ExportingDiagnosticsMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导出诊断信息 的本地化字符串。
        /// </summary>
        public static string ExportDiagnosticsHeader {
            get {
                return ResourceManager.GetString("ExportDiagnosticsHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 您正在导出应用的诊断数据。导出的诊断数据将包含应用 30 天内产生的日志、系统及环境信息、应用设置、当前加载的档案、所使... 的本地化字符串。
        /// </summary>
        public static string ExportDiagnosticsContent {
            get {
                return ResourceManager.GetString("ExportDiagnosticsContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        public static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 导出诊断数据 的本地化字符串。
        /// </summary>
        public static string ExportDiagnosticsPickerTitle {
            get {
                return ResourceManager.GetString("ExportDiagnosticsPickerTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 压缩文件 的本地化字符串。
        /// </summary>
        public static string ArchiveFileType {
            get {
                return ResourceManager.GetString("ArchiveFileType", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法打开所选诊断数据文件。 的本地化字符串。
        /// </summary>
        public static string CannotOpenDiagnosticsFile {
            get {
                return ResourceManager.GetString("CannotOpenDiagnosticsFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已导出诊断信息到 {0}。 的本地化字符串。
        /// </summary>
        public static string DiagnosticsExportedToPathFmt {
            get {
                return ResourceManager.GetString("DiagnosticsExportedToPathFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法导出诊断信息 的本地化字符串。
        /// </summary>
        public static string DiagnosticsExportFailed {
            get {
                return ResourceManager.GetString("DiagnosticsExportFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已创建桌面快捷方式。 的本地化字符串。
        /// </summary>
        public static string DesktopShortcutCreated {
            get {
                return ResourceManager.GetString("DesktopShortcutCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法创建桌面快捷方式 的本地化字符串。
        /// </summary>
        public static string DesktopShortcutFailed {
            get {
                return ResourceManager.GetString("DesktopShortcutFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已创建开始菜单快捷方式。 的本地化字符串。
        /// </summary>
        public static string StartMenuShortcutCreated {
            get {
                return ResourceManager.GetString("StartMenuShortcutCreated", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法创建开始菜单快捷方式 的本地化字符串。
        /// </summary>
        public static string StartMenuShortcutFailed {
            get {
                return ResourceManager.GetString("StartMenuShortcutFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 创建快捷换课快捷方式 的本地化字符串。
        /// </summary>
        public static string QuickClassChangeShortcutHeader {
            get {
                return ResourceManager.GetString("QuickClassChangeShortcutHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 快捷换课快捷方式需要启用【注册 Url 协议】选项才能工作。您要启用它吗？ 的本地化字符串。
        /// </summary>
        public static string QuickClassChangeNeedsUrlProtocolContent {
            get {
                return ResourceManager.GetString("QuickClassChangeNeedsUrlProtocolContent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string EnableButton {
            get {
                return ResourceManager.GetString("EnableButton", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 快捷换课.url 的本地化字符串。
        /// </summary>
        public static string QuickClassChangeSuggestedFileName {
            get {
                return ResourceManager.GetString("QuickClassChangeSuggestedFileName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 快捷方式 的本地化字符串。
        /// </summary>
        public static string ShortcutFileType {
            get {
                return ResourceManager.GetString("ShortcutFileType", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法打开所选快捷方式文件。 的本地化字符串。
        /// </summary>
        public static string CannotOpenShortcutFile {
            get {
                return ResourceManager.GetString("CannotOpenShortcutFile", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 已创建快捷换课图标到 {0}。 的本地化字符串。
        /// </summary>
        public static string QuickClassChangeExportedToPathFmt {
            get {
                return ResourceManager.GetString("QuickClassChangeExportedToPathFmt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 无法创建快捷换课图标 的本地化字符串。
        /// </summary>
        public static string QuickClassChangeExportFailed {
            get {
                return ResourceManager.GetString("QuickClassChangeExportFailed", resourceCulture);
            }
        }
    }
}
